# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/game/Kingdoms.ipynb.

# %% auto #0
__all__ = ['WatershedFlow', 'TradeRoute', 'Kingdom', 'GameBoard']

# %% ../../nbs/game/Kingdoms.ipynb #ba445732
import sys
import math
import numpy as np
import pandas as pd
import random
from fastcore.basics import patch
import heapq # for shortest path
from importlib import resources

# %% ../../nbs/game/Kingdoms.ipynb #3847b958
#This is kitchen sink approach to the library. I just didn't know what I needed

from ..plot.primitives import  MapCord , PrimitiveDemo
from ..plot.hex import Hex
from ..styles import StyleCSS,  SVGBuilder

from ..primitives import MapPath, MapSize, MapRect, MapCord 
from ..primitives import HexGrid, HexPosition ,  HexRegion , windy_edge , unique_windy_edge
from ..terrain import Terrain
from ..voronoi import generate_plate_terrain
Terrain.fromSeeds = generate_plate_terrain
from ..climate import ClimatePreset, Climate, TerraDemo
from ..geology import Geology, DrainageBasins, Watershed


# %% ../../nbs/game/Kingdoms.ipynb #59f517f0
from .settlement import CountryFlag

# %% ../../nbs/game/Kingdoms.ipynb #3c7ef09d
from ..weather import TerraDemo
from ..geology import  SoilSystem, DrainageBasins, Geology

# %% ../../nbs/game/Kingdoms.ipynb #378a99f3
from typing import NamedTuple

class WatershedFlow(NamedTuple):
    """ a place holder so we don't recompute flows which can be expensive """
    watershed: Watershed
    flow: float


   

# %% ../../nbs/game/Kingdoms.ipynb #3c181358
class TradeRoute:
    """ going to figure how to link up what we build"""

    def __init__(self, path: [HexPosition],  origin = 0, cost: float=0,  name: str=""):
        self.path = path
        self.cost = cost
        self.name = name
        self.origin = origin

    def destination(self)->HexPosition:
        return self.path[-1]

    @staticmethod
    def decode(s: str) -> 'TradeRoute':
        """Decode TradeRoute from string format."""
        name = ""
        origin = 0
        cost = 0.0
        path = []
        
        for line in s.strip().split('\n'):
            if ':' not in line:
                continue
            key, val = line.split(':', 1)
            if key == 'name':
                name = val
            elif key == 'origin':
                origin = int(val)
            elif key == 'cost':
                cost = float(val)
            elif key == 'path':
                path = [int(h) for h in val.split(',') if h]
        
        return TradeRoute(path=path, origin=origin, cost=cost, name=name)


# %% ../../nbs/game/Kingdoms.ipynb #56309caa
@patch
def encode(self: TradeRoute) -> str:
    """Encode TradeRoute to string format."""
    path_str = ','.join(str(h) for h in self.path)
    lines = [
        f"name:{self.name}",
        f"origin:{self.origin}",
        f"cost:{self.cost}",
        f"path:{path_str}"
    ]
    return '\n'.join(lines)

# %% ../../nbs/game/Kingdoms.ipynb #3c007d45
@patch
def encode(self: HexRegion) -> str:
    """Encode HexRegion as comma-separated hex indices."""
    return ','.join(str(h) for h in sorted(self.hexes))

@staticmethod
def _decode_hexregion(s: str, hexGrid: HexGrid) -> HexRegion:
    """Decode HexRegion from comma-separated hex indices."""
    hexes = set(int(h) for h in s.split(',') if h)
    return HexRegion(hexes=hexes, hexGrid=hexGrid)

HexRegion.decode = _decode_hexregion


# %% ../../nbs/game/Kingdoms.ipynb #63756197
class Kingdom:
    """ This is a terrority run by a single government"""
    def __init__(self, capital_hex: int, region: HexRegion, world: Geology,countryId:int = 0, flag = None):
        self.settlements = [capital_hex]  # capital is first
        self.region = region
        self.world = world
        self.countryId = countryId
        self.captured:[WatershedFlow] = []
        self.routes:[TradeRoute] = []
        self.flag = flag
        self.countryName = ""

        
    
    @classmethod
    def start(cls, world: Geology, scored:[WatershedFlow],palette_name: str = "husl"):
        terrain = world.terrain
        """Create initial kingdoms from best watersheds."""
        kingdoms = []
        i = 1 # lets reserve 0 for unclaimed and -1 for unavailable

    
        # Generate styles using seaborn palette
        flags = CountryFlag.seaborn(palette_name, levels=len(scored)+2) # just so we can index by 1
        saturation = 0.7

        for score in scored:
            ws = score.watershed
            capital = ws.max_flow_hex()[0]
          
            kingdom = cls(capital, ws.region, world, countryId=i,flag=flags[i])
            i += 1
            kingdom.captured.append(score)
            kingdoms.append(kingdom)
        
        return kingdoms

    @staticmethod
    def decode(s: str, world: Geology) -> 'Kingdom':
        """Decode Kingdom from string format."""
        lines = s.strip().split('\n')
        
        countryId = 0
        countryName = ""
        settlements = []
        flag = None
        region = None
        captured = []
        routes = []
        
        i = 0
        while i < len(lines):
            line = lines[i]
            
            if line.startswith('countryId:'):
                countryId = int(line.split(':', 1)[1])
            elif line.startswith('countryName:'):
                countryName = line.split(':', 1)[1]
            elif line.startswith('settlements:'):
                settlements = [int(x) for x in line.split(':', 1)[1].split(',') if x]
            elif line.startswith('flag:'):
                flag = CountryFlag.decode(line.split(':', 1)[1])
            elif line.startswith('+region'):
                region_lines = []
                i += 1
                while i < len(lines) and not lines[i].startswith('-region'):
                    region_lines.append(lines[i])
                    i += 1
                region = HexRegion.decode('\n'.join(region_lines), world.terrain.hexGrid)
            elif line.startswith('+captured:'):
                i += 1
                while i < len(lines) and not lines[i].startswith('-captured'):
                    if lines[i].startswith('+watershed:'):
                        flow = float(lines[i].split(':', 1)[1])
                        ws_lines = []
                        i += 1
                        while i < len(lines) and not lines[i].startswith('-watershed'):
                            ws_lines.append(lines[i])
                            i += 1
                        ws = Watershed.decode('\n'.join(ws_lines), world.terrain)
                        captured.append(WatershedFlow(ws, flow))
                    i += 1
            elif line.startswith('+routes:'):
                i += 1
                route_lines = []
                while i < len(lines) and not lines[i].startswith('-routes'):
                    if lines[i] == '---':
                        if route_lines:
                            routes.append(TradeRoute.decode('\n'.join(route_lines)))
                        route_lines = []
                    else:
                        route_lines.append(lines[i])
                    i += 1
            i += 1
        
        kingdom = Kingdom(settlements[0] if settlements else 0, region, world, countryId, flag)
        kingdom.settlements = settlements
        kingdom.countryName = countryName
        kingdom.captured = captured
        kingdom.routes = routes
        
        return kingdom




# %% ../../nbs/game/Kingdoms.ipynb #c1067f01
@patch
def encode(self: Kingdom) -> str:
    """Encode Kingdom to string format."""
    lines = [
        f"countryId:{self.countryId}",
        f"countryName:{self.countryName}",
        f"settlements:{','.join(str(s) for s in self.settlements)}",
    ]
    
    # Flag
    if self.flag:
        lines.append(f"flag:{self.flag.encode()}")
    
    # Region
    lines.append("+region")
    lines.append(self.region.encode())
    lines.append("-region")
    
    # Captured watersheds - use Watershed.encode()
    if self.captured:
        lines.append(f"+captured:{len(self.captured)}")
        for wf in self.captured:
            lines.append(f"+watershed:{wf.flow}")
            lines.append(wf.watershed.encode())
            lines.append("-watershed")
        lines.append("-captured")
    
    # Routes
    if self.routes:
        lines.append(f"+routes:{len(self.routes)}")
        for route in self.routes:
            lines.append(route.encode())
            lines.append("---")
        lines.append("-routes")
    
    return '\n'.join(lines)


# %% ../../nbs/game/Kingdoms.ipynb #1f91becb
class GameBoard:
    """ This lets us keep track of many of the games global properties"""

    def __init__(self,terrain,top_n=3,year=1900,gender=None):
        self.terrain = terrain
        self.world = Geology(terrain,plates=[])
        self.shedScores = [WatershedFlow(ws, ws.max_flow_hex()[1]) for ws in self.world.basins.sheds]
        self.shedScores.sort(key=lambda x: x[1], reverse=True)

        watershed_map = np.full(len(terrain.elevations), -1)  # -1 = no watershed
        for score in enumerate(self.shedScores):
            ws_id, watFlow = score
            watershed = watFlow[0]
            for hex_idx in watershed.region.hexes:
                watershed_map[hex_idx] = ws_id

        self.watershed_map = watershed_map

        # mark the map where we can have things
        terrain = self.terrain
        countries = np.zeros(len(terrain.elevations))
        for i in range(len(terrain.elevations)):
            if terrain.elevations[i] < 1:
                countries[i] = -1
            if terrain.elevations[i] > terrain.elevationDelta * (len(terrain.colorLevels)-2):
                countries[i] = -1
        
        if len(self.world.basins.sheds) < 0:
            if debug:
                print("no water")
            self.kingdoms = []
            return

        kingdoms = Kingdom.start(self,self.shedScores[:top_n])
        for i, country in enumerate(kingdoms):

            country.countryName =  GameBoard.completeCountry(country.flag.name,country.flag.countryPrefix)
            for h in country.region:
                countries[h] = country.countryId

        terrain.fields["country"] = countries

        self.kingdoms = kingdoms

    @classmethod
    def completeCountry(cls, name ,place, pattern=None, descriptor=None):
        

        # Possessive patterns
        PATTERNS = [
            "{name}'s {place}",      # Karl's Kingdom
            "{place} of {name}",     # Kingdom of Karl
            "{name} {place}",        # Karl Kingdom
        ]

        if not name:
            return ""
        
        # Choose pattern
        if pattern is not None and 0 <= pattern < len(PATTERNS):
            template = PATTERNS[pattern]
        else:
            template = random.choice(PATTERNS)
        
        return template.format(name=name, place=place)
    
    @staticmethod
    def decode(s: str) -> 'GameBoard':
        """Decode GameBoard from string format."""
        lines = s.strip().split('\n')
        
        world = None
        kingdoms = []
        
        i = 0
        while i < len(lines):
            line = lines[i]
            
            if line.startswith('+world'):
                world_lines = []
                i += 1
                while not lines[i].startswith('-world'):
                    world_lines.append(lines[i])
                    i += 1
                world = Geology.decode('\n'.join(world_lines))
            
            elif line.startswith('+kingdoms:'):
                i += 1
                while not lines[i].startswith('-kingdoms'):
                    if lines[i].startswith('+kingdom'):
                        kingdom_lines = []
                        i += 1
                        while not lines[i].startswith('-kingdom'):
                            kingdom_lines.append(lines[i])
                            i += 1
                        kingdoms.append(Kingdom.decode('\n'.join(kingdom_lines), world))
                    i += 1
            
            i += 1
        
        # Create GameBoard without triggering __init__
        board = object.__new__(GameBoard)
        board.terrain = world.terrain
        board.world = world
        board.kingdoms = kingdoms
        
        # Reconstruct derived fields
        board.shedScores = [WatershedFlow(ws, ws.max_flow_hex()[1]) for ws in world.basins.sheds]
        board.shedScores.sort(key=lambda x: x[1], reverse=True)
        
        # Rebuild watershed_map
        watershed_map = np.full(len(board.terrain.elevations), -1)
        for ws_id, watFlow in enumerate(board.shedScores):
            watershed = watFlow.watershed
            for hex_idx in watershed.region.hexes:
                watershed_map[hex_idx] = ws_id
        board.watershed_map = watershed_map
        
        return board

# %% ../../nbs/game/Kingdoms.ipynb #c26aab1d
@patch
def explore(self: GameBoard, countryId) -> Watershed | None:
    country = [x for x in self.kingdoms if x.countryId == countryId][0]
    grid = self.world.terrain.hexGrid
    countries = self.terrain.fields["country"]
    
    candidate_watersheds = []
    
    for direction in HexPosition.directions():
        spot = grid.index_to_hexposition(country.settlements[0])
        place = country.settlements[0]
        
        # Walk in this direction until we leave the kingdom
        while 0 <= place < len(countries) and countries[place] == countryId:
            spot = spot + direction
            place = grid.hexposition_to_index(spot)
        
        # If we hit unclaimed land, check its watershed
        if 0 <= place < len(countries) and countries[place] == 0:
            ws_id = self.watershed_map[place]
            if ws_id >= 0:
                score = self.shedScores[ws_id]
                candidate_watersheds.append(score)
    
    # Return best watershed by flow, or None
    if candidate_watersheds:
        return max(candidate_watersheds, key=lambda x: x[1])
    return None


# %% ../../nbs/game/Kingdoms.ipynb #e7c39535
@patch
def expand_kingdoms(self: GameBoard, max_rounds: int = 100):
    """Expand all kingdoms round-robin style until no more growth possible."""
    countries = self.terrain.fields["country"]
    
    for round_num in range(max_rounds):
        any_growth = False
        
        for kingdom in self.kingdoms:
            score = self.explore(kingdom.countryId)
            
            if score is not None:
                any_growth = True
                # Claim all hexes in this watershed
                for hex_idx in score.watershed.region.hexes:
                    countries[hex_idx] = kingdom.countryId
                    kingdom.region.hexes.add(hex_idx)
                kingdom.captured.append(score)
        
        # Stop if no kingdom could grow
        if not any_growth:
            print(f"Expansion complete after {round_num + 1} rounds")
            break
    
    return self.kingdoms


# %% ../../nbs/game/Kingdoms.ipynb #676f1177
@patch
def countries_overlay(self: GameBoard) -> str:
    """Create overlay showing kingdom territories with windy borders.
    """
   
    overlay = ""
    borders = {}  # Shared border cache
    terrain = self.terrain
    grid = terrain.hexGrid

    for  country in self.kingdoms:
        
        
        style = country.flag.kingStyle(f"{country.flag.name}_{country.countryId}")
        #print(StyleCSS.generate([style]))
        grid.builder.add_style(style)

        for path in country.region.trace_perimeter_cached(
            borders,
            style=style,
            f=unique_windy_edge(iterations=2, offset_min=0.05, offset_max=0.15)
        ):
            overlay += path.svg()

    return overlay


# %% ../../nbs/game/Kingdoms.ipynb #c6ba2e2b
@patch
def settlements_overlay(self: GameBoard, 
                        capital_size: float = 15,
                        city_size: float = 8) -> str:
    """Create overlay showing settlements with stars for capitals and circles for cities.
    
    Uses kingdom style colors with higher saturation for capitals.
    """
    grid = self.terrain.hexGrid
    overlay = ""
    
    for kingdom in self.kingdoms:
        # Create capital style (more saturated version of kingdom color)
        capital_style = kingdom.flag.contrastStyle(f"capital_{kingdom.countryId}")
        # Increase saturation
        capital_style.properties["fill"] = capital_style.saturate(1.5).properties["fill"]
        grid.builder.add_style(capital_style)
        
        # City style (kingdom color)
        city_style = kingdom.flag.contrastStyle(f"city_{kingdom.countryId}")
        
        grid.builder.add_style(city_style)
        
        for i, settlement_idx in enumerate(kingdom.settlements):
            hex_obj = grid.hexes[settlement_idx]
            cx, cy = hex_obj.center.x, hex_obj.center.y
            
            if i == 0:  # Capital - draw star
                points = []
                for j in range(5):
                    # Outer point
                    angle = (j * 144 - 90) * math.pi / 180
                    points.append(MapCord(
                        cx + capital_size * math.cos(angle),
                        cy + capital_size * math.sin(angle)
                    ))
                    # Inner point
                    angle = (j * 144 + 72 - 90) * math.pi / 180
                    inner_r = capital_size * 0.4
                    points.append(MapCord(
                        cx + inner_r * math.cos(angle),
                        cy + inner_r * math.sin(angle)
                    ))
                
                star_path = MapPath(points, capital_style).closed()
                overlay += star_path.drawClosed()
            else:  # Regular city - draw circle
                overlay += f'\t<circle cx="{cx}" cy="{cy}" r="{city_size}" class="{city_style.name}"/>\n'
    
    return overlay


# %% ../../nbs/game/Kingdoms.ipynb #48f4ff95
@patch
def find_adjacent_kingdoms(self: Kingdom, all_kingdoms: list['Kingdom']) -> list[int]:
    """Find kingdoms that share a border with this one."""
    adjacent = []
    outside_hexes = self.region.outside(ring=1)
    
    for i, other in enumerate(all_kingdoms):
        if other is self:
            continue
        
        # Check if any of our outside hexes are in their region
        if any(hex_idx in other.region.hexes for hex_idx in outside_hexes.hexes):
            adjacent.append(i)
    
    return adjacent




# %% ../../nbs/game/Kingdoms.ipynb #cb469ae7
@patch
def movement_cost(self: GameBoard, from_pos: HexPosition, to_pos: HexPosition, origin: int) -> float:
    """Calculate cost to move from one hex to another using HexPositions.
    
    Args:
        from_pos: Starting HexPosition
        to_pos: Destination HexPosition
        origin: Origin index for converting HexPosition to grid index
    
    Returns infinity for invalid moves (water, out of bounds).
    """
    terrain = self.terrain
    grid = terrain.hexGrid
    
    # Convert to indices to check terrain
    to_idx = grid.hexposition_to_index(to_pos, origin)
    from_idx = grid.hexposition_to_index(from_pos, origin)
    
    # Check bounds
    if to_idx < 0 or to_idx >= len(terrain.elevations):
        return float('inf')
    
    # Can't cross water
    if terrain.elevations[to_idx] < 1:
        return float('inf')
    
    from_elev = terrain.elevations[from_idx]
    to_elev = terrain.elevations[to_idx]
    
    # Base cost
    base_cost = 1.0
    
    # Elevation gain penalty (climbing is expensive)
    elev_diff = to_elev - from_elev
    if elev_diff > 0:
        # Exponential penalty for climbing
        base_cost += elev_diff * 2.0
    
    return base_cost




# %% ../../nbs/game/Kingdoms.ipynb #825c55fc
@patch
def find_path_dijkstra(self: GameBoard, start_hex: int, end_hex: int) -> list[HexPosition] | None:
    """Find shortest path using Dijkstra's algorithm with elevation costs."""
    #import heapq this is installed in the header

    class BHeapItem:
        def __init__(self, cost, hex_pos):
            self.cost = cost
            self.hex_pos = hex_pos

        def __lt__(self, other):
            return self.cost < other.cost

    grid = self.terrain.hexGrid
    
    # Convert start to HexPosition (using start as origin)
    start_pos = grid.index_to_hexposition(start_hex, start_hex)  # (0,0,0)
    end_pos = grid.index_to_hexposition(end_hex, start_hex)
    
    # Priority queue: (cost, HexPosition)
    queue = [BHeapItem(0, start_pos)]
    costs = {start_pos: 0}
    came_from = {}
    
    while queue:
        item = heapq.heappop(queue)
        current_cost, current = item.cost, item.hex_pos
        
        if current == end_pos:
            # Reconstruct path
            path = []
            while current in came_from:
                path.append(current)
                current = came_from[current]
            path.append(start_pos)
            return list(reversed(path))
        
        # Skip if we've found a better path already
        if current_cost > costs.get(current, float('inf')):
            continue
        
        # Check all 6 neighbors
        for direction in HexPosition.directions():
            neighbor = current + direction
            
            cost = self.movement_cost(current, neighbor, start_hex)
            if cost == float('inf'):
                continue
            
            new_cost = current_cost + cost
            
            if new_cost < costs.get(neighbor, float('inf')):
                costs[neighbor] = new_cost
                came_from[neighbor] = current
                heapq.heappush(queue, BHeapItem(new_cost, neighbor))
    
    return None  # No path found

# %% ../../nbs/game/Kingdoms.ipynb #71a020e6
@patch
def trade_overlay(self: GameBoard, 
                        capital_size: float = 15,
                        city_size: float = 8) -> str:
    """Create overlay showing trade routes between capitals.
    """
    grid = self.terrain.hexGrid
    overlay = ""
    
    for kingdom in self.kingdoms:
        # Create capital style (more saturated version of kingdom color)
        
        arrow_style = StyleCSS(
            f"arrow_{kingdom.countryId}",
            stroke="#5c4033",  # brown/dirt road color
            stroke_width=2,
            fill="#5c4033"
        )

        grid.builder.add_style(arrow_style)

        for route in kingdom.routes:
            origin = grid.index_to_hexposition(route.origin)
            lastPos = route.path[0]
            for pos in route.path:
                if pos != lastPos:
                    start = grid.hexposition_to_index(lastPos, route.origin)
                    end = grid.hexposition_to_index(pos,route.origin)
                    if start >= 0 and end >= 0:
                        overlay += grid.arrow(start, end, arrow_style)
                    else:
                        print("off map")
                lastPos = pos
        
    
    return overlay


# %% ../../nbs/game/Kingdoms.ipynb #d9d6e5ae
@patch
def names_overlay(self: GameBoard) -> str:
    """Create overlay showing kingdom territories with windy borders and labels."""
    terrain = self.terrain
    grid = terrain.hexGrid
    
    
    
    overlay = ""
    for country in self.kingdoms:
        # Add label style
        label_style =  country.flag.labelStyle(f"n_{country.countryId}")
        label_style.properties["stroke"] = "#36454F"
        label_style.properties["fill"] = "none"
        #print(StyleCSS.generate([label_style]))
        grid.builder.add_style(label_style)
        if len(country.region.hexes) > 0:
            # Add country name at centroid
            centroid_idx = country.region.centroid_hex()
            if centroid_idx >= 0 and country.countryName:
                hex_obj = grid.hexes[centroid_idx]
                cx, cy = hex_obj.center.x, hex_obj.center.y
                overlay += f'\t<text x="{cx}" y="{cy}" text-anchor="middle" dominant-baseline="middle" class="{label_style.name}">{country.countryName}</text>\n'

    return overlay

