# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/game/06_tactics.ipynb.

# %% auto #0
__all__ = ['expansion_zones', 'score_expansion_sites', 'assign_groups', 'expand']

# %% ../../nbs/game/06_tactics.ipynb #e6935644
from ..database import ZoomResult, GeoStorageDebugger,GeoStorage, SaveResult, LoadResult, ChunkCover, User
from ..primitives import HexTouchMap, HexPosition, HexGrid, HexDragMap, HexTouchMap, MapCord , PrimitiveDemo, Hex, HexWrapper
from ..core import Terrain, DrainageBasins
from ..styles import StyleCSS, SVGBuilder
from ..plot.primitives import  MapCord , PrimitiveDemo
from ..plot.hex import Hex, HexWrapper
from ..styles import StyleCSS,  SVGBuilder, SVGDef
from ..primitives import MapPath, MapSize, MapRect, MapCord ,HexDragMap, HexTouchMap, HexRegion
from ..overlay import  TerrainDisplay, TerrainOverlay, ClimateOverlay, TerraDemo, DrainageBasins, OverlaySpec
from ..overlay import TerrainDisplay, CreamOverlay, RiverOverlay, ClimateOverlay, OverlayContext
from ..water.soil import SoilSystem

# %% ../../nbs/game/06_tactics.ipynb #fc767e3e
from fastcore.utils import *
from fasthtml.common import *
from fasthtml.jupyter import *
from fastlite import *
import fasthtml.components as fc
import fasthtml.components as fc
import httpx
import random
import pandas as pd
import threading
from dataclasses import dataclass
from datetime import datetime
import numpy as np
import math
from dataclasses import dataclass, field
#| export
import heapq

# %% ../../nbs/game/06_tactics.ipynb #cb8086a6
from .globals import appRoutes,  webMe, globalStore, ensure_user,new_game_page, create_game, create_world, invalidate_cache, showUsers, logging
from .data import Settlement, Kingdom, Piece, TradeRoute, GameBoard, ActiveGame, CountryFlag, _map_point, Squad
from .data import Piece, PieceType, Instruction, InstructionList
from .data import SettlementOverlay, CountryBordersOverlay, KingdomNamesOverlay
from .piece import CountryFlag, DiagramGlyphs,PieceBoard, PieceStep, _move_cost,PieceBoardPlan, PieceList
from scipy.optimize import linear_sum_assignment
from enum import Enum

# %% ../../nbs/game/06_tactics.ipynb #e4a64121
@patch
def place_squad_spiral(settlement:Settlement,squad,  terrain, max_ring=10):
    """Place squad pieces in spiral around settlement, skipping water and occupied hexes.
    
    Args:
        squad: Squad with pieces to place
        settlement: Settlement to spiral around  
        terrain: Terrain object (has hexGrid, elevations)
        max_ring: Maximum spiral radius to search
        
    Returns:
        Number of pieces successfully placed
    """
    grid = terrain.hexGrid
    center = settlement.location
    
    # Collect occupied hexes: settlement location + all citizen locations
    occupied = {center}
    for citizen in settlement.citizens:
        if citizen.location is not None:
            occupied.add(citizen.location)
    
    # Generate spiral outward from center
    spiral = HexPosition.origin().spiral(max_ring)
    
    placed = 0
    for hp in spiral[1:]:  # skip center (settlement itself)
        if placed >= len(squad.pieces):
            break
        
        idx = grid.hexposition_to_index(hp, origin_index=center)
        if idx < 0:
            continue
        
        # Skip water (elevation <= 0)
        if terrain.elevations[idx] <= 0:
            continue
        
        # Skip occupied by settlement citizens
        if idx in occupied:
            continue
        
        squad.pieces[placed].location = idx
        occupied.add(idx)  # prevent stacking within the squad too
        placed += 1
    
    return placed


# %% ../../nbs/game/06_tactics.ipynb #1f255ba8
sim.run(num_turns=25)
show(sim)

# %% ../../nbs/game/06_tactics.ipynb #a4bc36e8
def expansion_zones(colonies: list[int], grid: HexGrid, elevations: np.ndarray,
                    countries: np.ndarray = None) -> tuple[np.ndarray, np.ndarray]:
    """Multi-seed Dijkstra — grow influence zones from colony hexes.
    
    Returns:
        zone_of: array[n_hexes] → colony index (-1 = unclaimed/ocean)
        cost_of: array[n_hexes] → travel cost from owning colony
    """
    n = len(elevations)
    zone_of = np.full(n, -1, dtype=int)
    cost_of = np.full(n, np.inf)
    
    pq = []
    for ci, colony_idx in enumerate(colonies):
        if colony_idx < 0 or elevations[colony_idx] <= 0:
            continue
        zone_of[colony_idx] = ci
        cost_of[colony_idx] = 0.0
        heapq.heappush(pq, (0.0, colony_idx, ci))
    
    while pq:
        cost, current, owner = heapq.heappop(pq)
        
        # Skip if already claimed by someone cheaper
        if cost > cost_of[current]:
            continue
        
        for neighbor in grid.neighborsOf(current):
            if neighbor in grid.invalidRegion:
                continue
            if elevations[neighbor] <= 0:
                continue
            if countries is not None and countries[neighbor] < 0:
                continue
            
            edge_cost = _move_cost(elevations, current, neighbor)
            new_cost = cost + edge_cost
            
            if new_cost < cost_of[neighbor]:
                cost_of[neighbor] = new_cost
                zone_of[neighbor] = owner
                heapq.heappush(pq, (new_cost, neighbor, owner))
    
    return zone_of, cost_of


def score_expansion_sites(zone_of: np.ndarray, cost_of: np.ndarray,
                          grid: HexGrid, elevations: np.ndarray,
                          food_tiers: np.ndarray,
                          n_candidates: int = 5,
                          min_cost: float = 3.0,
                          food_w: float = 1.0,
                          elev_w: float = 0.3,
                          frontier_w: float = 2.0,
                          choke_w: float = 1.5,
                          dist_w: float = 0.1
                          ) -> list[tuple[int, float, int]]:
    """Score hexes as expansion/outpost candidates.
    
    Args:
        zone_of, cost_of: from expansion_zones()
        min_cost: minimum distance from parent colony (don't build next door)
        *_w: scoring weights
    
    Returns:
        List of (hex_idx, score, zone_owner) sorted by score descending
    """
    n = len(elevations)
    scores = []
    
    for i in range(n):
        if zone_of[i] < 0 or elevations[i] <= 0:
            continue
        if cost_of[i] < min_cost:
            continue  # too close to parent colony
        
        tier = int(food_tiers[i]) if i < len(food_tiers) else 0
        elev = max(0, elevations[i])
        
        # Frontier proximity: how close to a zone boundary?
        frontier_score = 0.0
        n_blocked = 0
        for nb in grid.neighborsOf(i):
            if nb in grid.invalidRegion or elevations[nb] <= 0:
                n_blocked += 1
                continue
            if zone_of[nb] >= 0 and zone_of[nb] != zone_of[i]:
                frontier_score = 1.0  # on the border
                break
        
        # Chokepoint: count impassable neighbors (water/mountain/invalid)
        total_nb = len(grid.neighborsOf(i))
        choke_factor = n_blocked / max(1, total_nb)  # 0 = open, 1 = peninsula
        
        score = (tier * food_w
                 + elev * 0.01 * elev_w
                 + frontier_score * frontier_w
                 + choke_factor * choke_w
                 - cost_of[i] * dist_w)
        
        scores.append((i, score, zone_of[i]))
    
    scores.sort(key=lambda x: -x[1])
    
    # Pick top candidates, but spread across zones and space them out
    selected = []
    used_zones = {}  # zone → count
    selected_set = set()
    min_spacing = 4  # minimum hex distance between outposts
    
    for idx, score, zone in scores:
        if len(selected) >= n_candidates:
            break
        
        # Check spacing from already-selected sites
        pos_i = grid.index_to_hexposition(idx)
        too_close = False
        for sel_idx, _, _ in selected:
            pos_j = grid.index_to_hexposition(sel_idx)
            if pos_i.distance(pos_j) < min_spacing:
                too_close = True
                break
        if too_close:
            continue
        
        selected.append((idx, score, zone))
    
    return selected


def assign_groups(groups: list[list[Piece]], targets: list[tuple[int, float, int]],
                  grid: HexGrid, elevations: np.ndarray,
                  countries: np.ndarray = None
                  ) -> dict[str, InstructionList]:
    """Hungarian match piece groups → expansion sites.
    
    Cost for a group = max pathfind cost of any member (bottleneck).
    
    Args:
        groups: list of piece-lists (each group moves together)
        targets: from score_expansion_sites — (hex_idx, score, zone)
    
    Returns:
        Dict mapping piece.id → InstructionList for every piece in matched groups
    """
    n_groups = len(groups)
    n_targets = len(targets)
    if n_groups == 0 or n_targets == 0:
        return {}
    
    INF = 1e9
    cost = np.full((n_groups, n_targets), INF)
    
    # Cache paths: (group_idx, target_idx) → {piece_id: path}
    path_cache = {}
    
    for gi, group in enumerate(groups):
        for tj, (target_idx, _, _) in enumerate(targets):
            group_paths = {}
            max_cost = 0.0
            all_reachable = True
            
            for piece in group:
                if piece.location is None or piece.location < 0:
                    all_reachable = False
                    break
                path = piece.pathfind(target_idx, grid, elevations, countries)
                if not path:
                    all_reachable = False
                    break
                
                pc = sum(_move_cost(elevations, path[k], path[k+1])
                         for k in range(len(path) - 1))
                max_cost = max(max_cost, pc)
                group_paths[piece.id] = path
            
            if all_reachable:
                cost[gi, tj] = max_cost
                path_cache[(gi, tj)] = group_paths
    
    # Hungarian matching
    row_ind, col_ind = linear_sum_assignment(cost)
    
    # Build instructions for each matched piece
    assignments = {}
    for gi, tj in zip(row_ind, col_ind):
        if cost[gi, tj] >= INF:
            continue
        
        group = groups[gi]
        group_paths = path_cache.get((gi, tj), {})
        
        for piece in group:
            path = group_paths.get(piece.id)
            if not path or len(path) < 2:
                continue
            
            rules = InstructionList.path_to_rules(path, grid, start_facing=piece.facing)
            assignments[piece.id] = InstructionList(rules, cursor=0, patrol=False)
    
    return assignments


def expand(colonies: list[int], groups: list[list[Piece]],
           grid: HexGrid, elevations: np.ndarray,
           food_tiers: np.ndarray,
           n_outposts: int = None,
           countries: np.ndarray = None,
           **scoring_kw
           ) -> tuple[dict[str, InstructionList], list[tuple[int, float, int]]]:
    """Full expansion pipeline: zone → score → assign.
    
    Args:
        colonies: hex indices of existing settlements
        groups: piece groups to send out
        n_outposts: how many sites to find (default = len(groups))
        **scoring_kw: passed to score_expansion_sites
    
    Returns:
        (assignments, sites) — piece instructions + chosen outpost locations
    """
    if n_outposts is None:
        n_outposts = len(groups)
    
    # Phase 1: zones
    zone_of, cost_of = expansion_zones(colonies, grid, elevations, countries)
    
    # Phase 2: score sites
    sites = score_expansion_sites(
        zone_of, cost_of, grid, elevations, food_tiers,
        n_candidates=n_outposts, **scoring_kw
    )
    
    # Phase 3: assign groups
    assignments = assign_groups(groups, sites, grid, elevations, countries)
    
    return assignments, sites

