# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/game/Web.ipynb.

# %% auto #0
__all__ = ['app', 'rt', 'server', 'globalStore', 'webMe', 'ActiveGame', 'ensure_user', 'new_game_page', 'hex_clicked', 'showMap',
           'index', 'kingdom_hex_clicked', 'kingdom']

# %% ../../nbs/game/Web.ipynb #7b1b528f
from fastcore.utils import *
from fasthtml.common import *
from fasthtml.jupyter import *
#from fasthtml.jupyter import get_host
from fastlite import *
import fasthtml.components as fc
import httpx
import random
import pandas as pd

# %% ../../nbs/game/Web.ipynb #97767b1b
import logging

for logger_name in ("uvicorn", "uvicorn.error", "uvicorn.access"):
    uv_logger = logging.getLogger(logger_name)
    file_handler = logging.FileHandler('HexServer.txt')
    file_handler.setFormatter(logging.Formatter('%(asctime)s - %(levelname)s - %(message)s'))
    uv_logger.addHandler(file_handler)


# %% ../../nbs/game/Web.ipynb #a654bfd3
from monsterui.all import *


# %% ../../nbs/game/Web.ipynb #d569e2ee
if server: server.stop(); del server
app = FastHTML(hdrs = Theme.violet.headers())
rt = app.route
server = JupyUvi(app)

# %% ../../nbs/game/Web.ipynb #845fcdc6
def webMe(*c): return HTMX(*c, host='', app=app)

# %% ../../nbs/game/Web.ipynb #6ecffc9e
from ..plot.primitives import  MapCord , PrimitiveDemo
from ..plot.hex import Hex, HexWrapper
from ..styles import StyleCSS,  SVGBuilder

from ..primitives import MapPath, MapSize, MapRect, MapCord 
from ..primitives import HexGrid, HexPosition ,  HexRegion , windy_edge , unique_windy_edge
from ..terrain import Terrain
from ..voronoi import generate_plate_terrain
Terrain.fromSeeds = generate_plate_terrain
from ..climate import ClimatePreset, Climate, TerraDemo
from ..geology import Geology, DrainageBasins, Watershed

# %% ../../nbs/game/Web.ipynb #f69f26c3
from .data import GameBoard,Kingdom,TradeRoute,Terrain,StyleCSS, Hex, TerraDemo, Geology, DrainageBasins, CountryFlag, GameStorage, TerrainTemplate, Settlement, Piece

# %% ../../nbs/game/Web.ipynb #7241283a
from ..database import ZoomResult, GeoStorageDebugger,GeoStorage, SaveResult, LoadResult, ChunkCover, User

# %% ../../nbs/game/Web.ipynb #281a0631
import logging

logging.basicConfig(
    filename='base.text',
    level=logging.DEBUG,
    format='%(asctime)s - %(levelname)s - %(message)s'
)

logging.info("getting Started")


# %% ../../nbs/game/Web.ipynb #f21ea33a
@patch
def html(self:Terrain,wrapper:HexWrapper = None)->str:
    grid = self.hexGrid
    if wrapper is None:
        wrapper = HexWrapper(callBack=HexWrapper.route())
    clearStyle = StyleCSS("HexClear",stroke="none",fill="white",opacity=0.1)
    for i, h in enumerate(grid.hexes):
        grid.hexes[i].style = clearStyle
        #grid.hexes[i].label = str(i)
    #self.colorMap()
    grid.builder.add_style(clearStyle)
    grid.update(wrapper=wrapper,layer_name="hexes")
    for i, l in enumerate(grid.builder.layers):
        logging.info(f"layer[{i}] is {l.name}")
    return grid.builder.xml()

# %% ../../nbs/game/Web.ipynb #04540e2b
@dataclass
class ActiveGame:
    board: GameBoard
    cover: ChunkCover
    world_id: int
    country_id: int = 0  # 0 = world view, >0 = zoomed into that kingdom
    selected_piece: str = ""
    selected_settlement: str = ""


# %% ../../nbs/game/Web.ipynb #898f0ca5
globalStore = GameStorage("gameData/WebDebug.db")

# %% ../../nbs/game/Web.ipynb #09b9756f
# Helper to ensure we have a user row
def ensure_user(session) -> int:
    if 'userid' not in session:
        session['userid'] = random.randint(0, 1_000_000)
    uid = session['userid']
    row = globalStore.db.execute("SELECT id FROM user WHERE id = ?", [uid]).fetchone()
    if not row:
        from datetime import datetime
        now = int(datetime.now().timestamp())
        globalStore.users.insert({
            'id': uid, 'username': f'player_{uid}', 'email': '', 'password': '',
            'created': now, 'sessionID': str(uid), 'activeWorld': 0
        })
    return uid



def new_game_page():
    templates = TerrainTemplate.maps  # {'bayArea': 'bayArea_map', ...}
    form = Form(
        Div(
            Label("Map Template", cls="label"),
            Select(
                *[Option(name, value=name) for name in sorted(templates.keys())],
                name="template_name", cls="select select-bordered w-full"
            ),
            cls="form-control"
        ),
        Div(
            Label("Kingdoms", cls="label"),
            Input(type="number", name="kingdoms", value="5", min="1", max="10",
                  cls="input input-bordered w-full"),
            cls="form-control"
        ),
        Div(
            Label("Lakes", cls="label"),
            Input(type="number", name="lakes", value="1", min="0", max="5",
                  cls="input input-bordered w-full"),
            cls="form-control"
        ),
        Div(
            Label("Hex Radius", cls="label"),
            Input(type="number", name="radius", value="25", min="10", max="40",
                  cls="input input-bordered w-full"),
            cls="form-control"
        ),
        Button("Create World", type="submit", cls="btn btn-primary mt-4"),
        action="/create_world", method="post",
        cls="card bg-base-200 shadow-lg p-6 space-y-4 max-w-md mx-auto"
    )
    return Titled("New Game",
        Div(
            H3("Choose Your World", cls="text-2xl font-bold text-center mb-6"),
            form,
            cls="flex flex-col items-center p-12"
        )
    )




# %% ../../nbs/game/Web.ipynb #2343ecc2
@patch
def create_game(self: GameStorage, user_id, template_name="bayArea",
                kingdoms=5, lakes=1, radius=10) -> ActiveGame:
    logging.info(f"create_game: user={user_id} template={template_name} k={kingdoms} lakes={lakes} r={radius}")
    tt = TerrainTemplate()
    terrain = getattr(tt, template_name)()
    logging.info(f"create_game: terrain loaded, {len(terrain.elevations)} hexes")
    
    terrain.carve_to_ocean(num_lakes=lakes)
    terrain.hexGrid.adjustRadius(radius)

    board = GameBoard(terrain, top_n=kingdoms)
    logging.info(f"create_game: GameBoard created, {len(board.kingdoms)} kingdoms")
    board.expand_kingdoms(max_rounds=50)
    logging.info(f"create_game: kingdoms expanded, regions: {[len(k.region.hexes) for k in board.kingdoms]}")

    cover = ChunkCover(terrain, rings=5, halo_rings=1)
    cover.db = self
    cover.save(name=template_name)
    logging.info(f"create_game: cover saved, ident={cover.ident}")
    
    board.save(self, world_id=cover.ident)
    logging.info(f"create_game: board saved to world_id={cover.ident}")

    self.db.execute("UPDATE user SET activeWorld = ? WHERE id = ?",
                    [cover.ident, user_id])
    
    # Verify the write stuck
    check = self.db.execute("SELECT activeWorld FROM user WHERE id = ?", [user_id]).fetchone()
    logging.info(f"create_game: verified activeWorld={check[0] if check else 'NO ROW'} for user={user_id}")
    
    return ActiveGame(board=board, cover=cover, world_id=cover.ident)


# %% ../../nbs/game/Web.ipynb #b9d33047
@patch
def active_board(self: GameStorage, user_id) -> ActiveGame:
    logging.info(f"active_board: looking up user {user_id}")
    row = self.db.execute("SELECT activeWorld FROM user WHERE id = ?", [user_id]).fetchone()
    if not row:
        logging.warning(f"active_board: no user row for {user_id}")
        return None
    if not row[0]:
        logging.warning(f"active_board: activeWorld is {row[0]!r} for user {user_id}")
        return None
    
    world_id = row[0]
    logging.info(f"active_board: world_id={world_id}")
    
    try:
        logging.info(f"active_board: loading cover for world {world_id}")
        cover_result = self.load_cover(world_id)
        logging.info(f"active_board: load_cover status={cover_result.status}")
        if cover_result.status != 'loaded':
            return None
        cover = cover_result.data
        logging.info(f"active_board: cover loaded, {len(cover.terrain.elevations)} hexes")
        
        logging.info(f"active_board: building gameboard")
        board = self.gameboard(world_id, cover.terrain)
        logging.info(f"active_board: gameboard built, {len(board.kingdoms)} kingdoms")
        
        return ActiveGame(board=board, cover=cover, world_id=world_id)
    except Exception as e:
        logging.error(f"active_board: FAILED: {type(e).__name__}: {e}", exc_info=True)
        return None


# %% ../../nbs/game/Web.ipynb #a34289a5
@patch
def create_game(self: GameStorage, user_id, template_name="bayArea",
                kingdoms=5, lakes=1, radius=10) -> ActiveGame:
    tt = TerrainTemplate()
    terrain = getattr(tt, template_name)()  # e.g. tt.bayArea() -> TerraDemo().bayArea_map()
    terrain.carve_to_ocean(num_lakes=lakes)
    terrain.hexGrid.adjustRadius(radius)

    board = GameBoard(terrain, top_n=kingdoms)
    board.expand_kingdoms(max_rounds=50)

    cover = ChunkCover(terrain, rings=5, halo_rings=1)
    cover.db = self
    cover.save(name=template_name)
    board.save(self, world_id=cover.ident)

    self.db.execute("UPDATE user SET activeWorld = ? WHERE id = ?",
                    [cover.ident, user_id])
    return ActiveGame(board=board, cover=cover, world_id=cover.ident)


# %% ../../nbs/game/Web.ipynb #bdd0017a
@rt
def hex_clicked(session, hex_id: int):
    uid = ensure_user(session)
    active = globalStore.active_board(uid)
    if not active:
        return RedirectResponse('/', status_code=303)

    board = active.board
    terrain = board.terrain
    countries = terrain.fields.get("country")

    if countries is None or hex_id < 0 or hex_id >= len(countries):
        debug_msg = f"Invalid hex {hex_id}"
        return (
            P("Invalid hex", id="map"),
            Div(debug_msg, id="debug-panel", hx_swap_oob="true")
        )

    country_id = int(countries[hex_id])

    if country_id > 0:
        # Clicked a kingdom — zoom in
        k = next((k for k in board.kingdoms if k.countryId == country_id), None)
        debug_msg = f"Zooming into {k.countryName if k else f'Kingdom {country_id}'}"
        
        map_content = kingdom(session, country_id)
        return (
            map_content,
            Div(debug_msg, id="debug-panel", hx_swap_oob="true")
        )
    elif country_id == 0:
        debug_msg = f"Hex {hex_id} is unclaimed land"
    else:
        debug_msg = f"Hex {hex_id} is water/mountains"
    
    return (
        P(debug_msg, id="map"),
        Div(debug_msg, id="debug-panel", hx_swap_oob="true")
    )


# %% ../../nbs/game/Web.ipynb #74d7009f
@rt
def showMap(session):
    uid = ensure_user(session)
    active = globalStore.active_board(uid)
    if not active:
        return RedirectResponse('/', status_code=303)

    board = active.board
    terrain = board.terrain
    grid = terrain.hexGrid
    builder = grid.builder

    terrain.colorMap()
    grid.update()
    terrain.compute_climate()

    builder.layers = []
    terrain.terrainCream()

    logging.info("clearing layers")

    builder.adjust("climates", terrain.dottedClimate())
    builder.adjust("settlement", board.settlementOverlay())
    builder.adjust("countries", board.countries_overlay())
    builder.adjust("water", board.world.basins.draw_watersheds())
    builder.adjust("names", board.names_overlay())

    # Kingdom links for left panel
    kingdom_links = []
    for k in board.kingdoms:
        kingdom_links.append(
            A(k.countryName or f"Kingdom {k.countryId}",
              hx_get=f"/kingdom/{k.countryId}",
              hx_target="#map",
              cls="btn btn-ghost btn-sm justify-start")
        )

    wrapper = HexWrapper(callBack=HexWrapper.route())
    
    return (
        # Map content
        Div(NotStr(terrain.html(wrapper=wrapper)), id="map"),
        # Kingdom links (OOB swap into left panel)
        Div(*kingdom_links, id="left-panel-content", hx_swap_oob="true")
    )


# %% ../../nbs/game/Web.ipynb #aafa9789
@rt
def index(session):
    
    uid = ensure_user(session)
    logging.info(f"index: uid={uid}")
    active = globalStore.active_board(uid)
    if active:
        return RedirectResponse('/game', status_code=303)
    return new_game_page()

# %% ../../nbs/game/Web.ipynb #3611814b
@rt
def kingdom_hex_clicked(session, hex_id: int, country_id: int):
    uid = ensure_user(session)
    active = globalStore.active_board(uid)
    if not active:
        return RedirectResponse('/', status_code=303)

    board = active.board
    terrain = board.terrain

    # Re-zoom to get the mapper (cached chunks, should be fast)
    result = globalStore.kingdom_detail(active.world_id, country_id, terrain)
    coarse_idx = result.mapper(hex_id)

    # Figure out who owns this hex on the coarse map
    countries = terrain.fields.get("country")
    if countries is None or coarse_idx < 0 or coarse_idx >= len(countries):
        # Can't resolve — just go back to world
        return RedirectResponse('/showMap', status_code=303)

    owner = int(countries[coarse_idx])

    if owner == country_id or owner <= 0:
        # Case 1: clicked inside current kingdom (or water/unclaimed) → zoom out
        debug_msg = "Zooming out to world view"
        return (
            RedirectResponse('/showMap', status_code=303),
            Div(debug_msg, id="debug-panel", hx_swap_oob="true")
        )
    else:
        # Case 2: clicked a different kingdom → zoom into that one
        k = next((k for k in board.kingdoms if k.countryId == owner), None)
        debug_msg = f"Zooming into {k.countryName if k else f'Kingdom {owner}'}"
        
        map_content = kingdom(session, owner)
        return (
            map_content,
            Div(debug_msg, id="debug-panel", hx_swap_oob="true")
        )



# %% ../../nbs/game/Web.ipynb #d5d3cd44
@rt("/kingdom/{id}")
def kingdom(session, id: int):
    uid = ensure_user(session)
    active = globalStore.active_board(uid)
    if not active:
        return RedirectResponse('/', status_code=303)

    board = active.board
    terrain = board.terrain

    # Zoom into this kingdom
    result = globalStore.kingdom_detail(active.world_id, id, terrain)

    zoomed = result.terrain
    zoomed.hexGrid.adjustRadius(terrain.hexGrid.radius)
    zoomed.colorMap()
    zoomed.hexGrid.update()
    zoomed.compute_climate()

    c2f = result.invert_mapper()

    builder = zoomed.hexGrid.builder
    builder.layers = []
    zoomed.terrainCream()

    builder.adjust("climates", zoomed.dottedClimate())
    builder.adjust("borders", board.countries_overlay(zoomed, c2f))
    builder.adjust("names", board.names_overlay(zoomed, c2f))
    builder.adjust("settle", board.settlementOverlay(zoomed, c2f))

    if result.basins:
        builder.adjust("water", result.basins.draw_watersheds())

    # Hex click handler for zoomed view
    wrapper = HexWrapper(callBack=lambda grid, index: {
        "hx-post": "/kingdom_hex_clicked",
        "hx-vals": f'{{"hex_id":{index},"country_id":{id}}}',
        "hx-target": "#map"
    })

    k = next((k for k in board.kingdoms if k.countryId == id), None)
    title = k.countryName if k else f"Kingdom {id}"

    return Div(
        Div(
            A("← Back to World", href="/showMap", cls="btn btn-sm btn-outline"),
            H4(title, cls="text-lg font-bold"),
            cls="flex items-center gap-4 p-2"
        ),
        P(NotStr(zoomed.html(wrapper=wrapper))),
        id="map"
    )

