"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['sampleHex', 'hexStyle', 'canvas', 'grid', 'arrowLayer', 'sampleGrid', 'showEast', 'showRing', 'line_demo',
           'range_demo', 'rotation_demo']

# %% ../nbs/00_core.ipynb 7
from .primitives import Hex, MapCord 


# %% ../nbs/00_core.ipynb 8
sampleHex = Hex(radius=50,center=MapCord(100,100))

sampleHex.vertices(), "\n-- We round edges so we can compare --\n", sampleHex.edges()

# %% ../nbs/00_core.ipynb 9
from .styles import StyleCSS,  SVGBuilder

# %% ../nbs/00_core.ipynb 10
#some drawing setup 
hexStyle = StyleCSS("HexStyle",fill="yellow",stroke="blue",stroke_width=2)
canvas = SVGBuilder()
canvas.width=200 ;canvas.height=200
canvas.add_style(hexStyle)

#add our hex to the canvas
#some drawing setup 


#add our hex to the canvas
sampleHex = Hex(radius=50,center=MapCord(100,100),style=hexStyle)
canvas.adjust("main",sampleHex.svg())

#show our work
canvas.show()
canvas.adjust("main",sampleHex.svg())

#show our work
canvas.show()

# %% ../nbs/00_core.ipynb 12
from .primitives import HexGrid

def sampleGrid(numRings = 2, fill = "#ff7b00ff"):
    #drawing set up
    hexStyle = StyleCSS("HexStyle",fill=fill,stroke="blue",stroke_width=2)

    #Our new class
    grid = HexGrid.create_centered(numRings,radius=30,style=hexStyle)

    #make sure we are ready to draw
    grid.update()
    return grid

sampleGrid().builder.show()

# %% ../nbs/00_core.ipynb 14
def sampleGrid(hexDim = 2, fill = "white",makeLabels = False):

    #drawing set up
    hexStyle = StyleCSS("HexStyle",fill=fill,stroke="blue",stroke_width=2)
    labelStyle = StyleCSS("labelStyle",fill=fill,stroke="black",stroke_width=1)
    
    grid = HexGrid.create_centered(hexDim,radius=40,style=hexStyle)

    #Need to add styles as we go along
    grid.builder.add_style(labelStyle)

    #itterate through the hexes
    for i in range(len(grid.hexes)):
        if makeLabels:
            grid.hexes[i].label = str(i) 
        grid.hexes[i].labelStyle = labelStyle.name

    grid.update()
    return grid
    

grid = sampleGrid(makeLabels=True)
grid.builder.show()

# %% ../nbs/00_core.ipynb 16
from .primitives import HexPosition , MapPath
grid = sampleGrid()

#mark the treasure
grid.hexes[grid.middle()].label = "X"

#lets have a directions layer
arrowLayer = ""

#Use the realtive position class called HexPosition
for position in HexPosition.directions():
    i = grid.hexposition_to_index(position, 12)
    grid.hexes[i].label = position.label
    arrowLayer += grid.arrow(12,i)

grid.update()

#we can add a layer or update one in a builder using the adjust method
grid.builder.adjust("arrows",arrowLayer)

grid.builder.show()

# %% ../nbs/00_core.ipynb 18
def showEast(middleIndex=12):
    grid = sampleGrid()

    #lets have a directions layer
    arrowLayer = ""
    
    #Mark our starting point
    grid.hexes[middleIndex].label = str(middleIndex)

    #Get a Direction
    eastDir = HexPosition.direction("E")

    #go part way
    i = grid.hexposition_to_index(eastDir, middleIndex)
    grid.hexes[i].label = "near"
    arrowLayer += grid.arrow(middleIndex,i)

    #keep going
    farEast = 2 * eastDir 
    j = grid.hexposition_to_index(farEast, middleIndex)
    grid.hexes[j].label = "far"
    arrowLayer += grid.arrow(i,j)

    grid.update()
    grid.builder.adjust("arrows",arrowLayer)
    return grid.builder.show()
showEast(12)


# %% ../nbs/00_core.ipynb 21
showEast(6)

# %% ../nbs/00_core.ipynb 24
def showRing(middleIndex=12,ring=1):
    grid = sampleGrid()
    
    grid.hexes[middleIndex].label = "X"


    #lets have a directions layer
    arrowLayer = ""
    #Get a Direction
    eastDir = HexPosition.direction("E")

    #go out to the edge
    s = middleIndex
    for k in range(ring):
        i = grid.hexposition_to_index(eastDir, s)
        grid.hexes[i].label = f"r {k+1}"
        arrowLayer += grid.arrow(s,i)
        s = i

    origin = HexPosition.origin()

    #now lets go through the positions. by default it starts in the east like the sunrise.
    positions = origin.ring(ring)
    for pos in positions:
        i = grid.hexposition_to_index(pos,middleIndex ) 
        grid.hexes[i].label = f"r {pos.label}"
        if s != i:
            arrowLayer += grid.arrow(s,i)
        s = i

    grid.update()
    grid.builder.adjust("arrows",arrowLayer)
    return grid.builder.show()
    
showRing(12)

# %% ../nbs/00_core.ipynb 25
showRing(12,ring=2)

# %% ../nbs/00_core.ipynb 34
#??HexPosition.line_to

# %% ../nbs/00_core.ipynb 35
def line_demo(start_idx=20, end_idx=8):
    """Demo showing line drawing between two hexes using cube coordinates"""
    grid = sampleGrid()
    # Clear the axis arrows from sampleGrid
    grid.builder.adjust("axis", "")
    
    # Mark start and end
    grid.hexes[start_idx].label = "Start"
    grid.hexes[end_idx].label = "End"
    
    # Get the hex positions. This defaults to postion 0
    start_pos = grid.index_to_hexposition(start_idx)
    end_pos = grid.index_to_hexposition(end_idx)
    
    # Draw a line between them using cube coordinate interpolation
    path_positions = start_pos.line_to(end_pos)
    
    arrowLayer = ""
    prev_idx = start_idx
    
    for i, pos in enumerate(path_positions[1:], 1):  # Skip first (it's the start)
        curr_idx = grid.hexposition_to_index(pos)
        
        # Label intermediate hexes
        if curr_idx != end_idx and curr_idx >= 0:
            grid.hexes[curr_idx].label = str(i)
        
        # Draw arrow if valid index
        if curr_idx >= 0:
            arrowLayer += grid.arrow(prev_idx, curr_idx)
            prev_idx = curr_idx
    
    grid.update()
    grid.builder.adjust("arrows", arrowLayer)
    return grid.builder.show()

line_demo(20, 8)


# %% ../nbs/00_core.ipynb 37
def range_demo( max_distance=2):
    """Demo showing all hexes within a certain distance"""
    
    grid = sampleGrid(3, fill="lightgray")
    center_idx = grid.middle()

    # Mark center
    grid.hexes[center_idx].label = "0"
    
    # Get center position
    center_pos = grid.index_to_hexposition(center_idx)
    
    # Color hexes by distance
    colors = [StyleCSS(x,fill=x,stroke="blue",stroke_width=2) for x in ["green","yellow", "orange", "red", "purple"]]
    for color in colors:
        grid.builder.add_style(color)
    
    for distance in range(1, max_distance + 1):
        # Get all positions at this distance
        positions = center_pos.ring(distance)
        
        for pos in positions:
            try:
                idx = grid.hexposition_to_index(pos, center_idx)
                if 0 <= idx < len(grid.hexes):
                    grid.hexes[idx].label = str(distance)
                    grid.hexes[idx].style = colors[distance-1]
                    # You could change fill color here if we modify the hex style
            except:
                pass  # Position outside grid
    
    grid.update()
    return grid.builder.show()

range_demo(3)


# %% ../nbs/00_core.ipynb 38
def rotation_demo(center_idx=12):
    """Demo showing rotation around a center hex"""
    grid = sampleGrid()
    # Clear the axis arrows from sampleGrid
    grid.builder.adjust("axis", "")
    
    grid.hexes[center_idx].label = "Center"
    
    # Start with a position to the east
    start_pos = HexPosition.direction("E")
    start_idx = grid.hexposition_to_index(2 * start_pos , center_idx)
    grid.hexes[start_idx].label = "0°"
    
    arrowLayer = ""
    prev_idx = start_idx
    
    # Rotate around 60° at a time
    for i in range(1, 6):
        # Rotate the position
        rotated_pos = 2 * start_pos.rotate(-i)
        curr_idx = grid.hexposition_to_index(rotated_pos, center_idx)
        
        grid.hexes[curr_idx].label = f"{i*60}°"
        arrowLayer += grid.arrow(prev_idx, curr_idx)
        prev_idx = curr_idx
    
    # Close the loop
    arrowLayer += grid.arrow(prev_idx, start_idx)
    
    grid.update()
    grid.builder.adjust("arrows", arrowLayer)
    return grid.builder.show()

rotation_demo(12)


# %% ../nbs/00_core.ipynb 44
from .primitives import HexRegion
