# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/11_Scale.ipynb.

# %% auto #0
__all__ = ['ChunkCover', 'HFFT']

# %% ../nbs/11_Scale.ipynb #e32d9903
import sys
import math
import numpy as np
from fastcore.basics import patch
from collections import deque
#from HexMagic.database import GeoStorage, ChunkedTerrainGenerator, ChunkRef
from .primitives import MapRect, MapCord, MapSize, HexPosition,PrimitiveDemo
from .core import Terrain, TerraDemo



# %% ../nbs/11_Scale.ipynb #75e01985
from .climate import TerrainPatterns, DrainageBasins, Geology, TerraDemo, Terrain, GeoBounds, ClimatePreset, TerrainFactory
from .primitives import MapCord, MapSize, MapRect, MapPath, Hex, HexGrid, HexWrapper, HexPosition, hexBackground, HexRegion, unique_windy_edge, PrimitiveDemo, HexChunk
from .styles import StyleCSS, SVGBuilder
from .geology import Plate
from .geology import River, Watershed
from scipy.ndimage import uniform_filter



# %% ../nbs/11_Scale.ipynb #a9193b35
class ChunkCover:
    """Covers a terrain with HexChunks arranged in patterns."""

    def __init__(self, terrain, rings, halo_rings=1,
        ident:int=None, # an identity for the database
        db = None, # this is a reference for a future datase holding
        ):
        self.terrain = terrain
        self.rings = rings
        self.halo_rings = halo_rings
        self.distance = 2 * rings  # spacing between chunk centers
        self.chunks = []
        self.position_to_index = {}  # {CoverPosition: chunk_index}
        self.origin_index = self._compute_origin_index()
        if ident is None:
            ident = -1
        
        #These will give us persistence
        self.ident = ident
        self.db = db

    def _compute_origin_index(self) -> int:
        """Compute the grid index for the cover's origin (center chunk)."""
        return self.terrain.hexGrid.middle

    @property
    def origin_position(self) -> HexPosition:
        """The CoverPosition of the origin chunk (always 0,0,0)."""
        return HexPosition.origin()

    def chunkAt(self, origin=None) -> HexChunk:
        """Create a chunk with halo centered at the given grid index."""
        grid = self.terrain.hexGrid
        if origin is None:
            origin = grid.middle

        chunk = HexChunk.with_halo(
            HexPosition.origin(), 
            core_rings=self.rings, 
            halo_rings=self.halo_rings
        )
        chunk.origin = origin

        for prop in self.terrain.fields.keys():
            chunk.fields[prop] = np.zeros(len(chunk))

        for i in chunk.iter_with_world():
            source = grid.hexposition_to_index(i.local_pos, origin_index=origin)
            if 0 <= source < len(self.terrain.elevations):
                chunk.elevations[i.idx] = self.terrain.elevations[source]
                for prop in self.terrain.fields.keys():
                    chunk.fields[prop][i.idx] = self.terrain.fields[prop][source]
        return chunk

    def regionAt(self, origin=None, include_halo=False) -> HexRegion:
        """Create a HexRegion covering the chunk area."""
        grid = self.terrain.hexGrid
        if origin is None:
            origin = grid.middle

        region = HexRegion(set(), hexGrid=grid)
        chunk = HexChunk.with_halo(
            HexPosition.origin(), 
            core_rings=self.rings, 
            halo_rings=self.halo_rings
        )
        
        indices = chunk.iter_all() if include_halo else chunk.iter_core()
        for idx in indices:
            pos = chunk.index_to_hexposition(idx)
            source = grid.hexposition_to_index(pos, origin_index=origin)
            if 0 <= source < len(grid.hexes):
                region.hexes.add(source)
        return region

    def compute_spiral_rings(self) -> int:
        """Compute number of chunk rings needed to cover the grid."""
        grid = self.terrain.hexGrid
        min_dim = min(grid.nRows, grid.nCols)
        chunk_diameter = 2 * self.rings
        return max(1, int(np.ceil(min_dim / chunk_diameter / 2)))

    def spiral_chunks(self, n_rings: int = None) -> list[HexChunk]:
        """Generate chunks arranged in a spiral pattern."""
        grid = self.terrain.hexGrid
        
        if n_rings is None:
            n_rings = self.compute_spiral_rings()
        
        positions = HexPosition.origin().spiral(n_rings, distance=self.distance)
        
        self.chunks = []
        self.position_to_index = {}
        
        for pos in positions:
            origin_idx = grid.hexposition_to_index(pos, origin_index=self.origin_index)
            
            if origin_idx < 0 or origin_idx >= len(grid.hexes):
                continue
                
            chunk = self.chunkAt(origin=origin_idx)
            chunk.position = pos
            
            chunk_idx = len(self.chunks)
            self.position_to_index[pos] = chunk_idx
            self.chunks.append(chunk)
        
        return self.chunks

    def coverposition_to_index(self, cover_pos: HexPosition) -> int:
        """Convert a CoverPosition to chunk index. Returns -1 if not found."""
        return self.position_to_index.get(cover_pos, -1)

    def index_to_coverposition(self, chunk_idx: int) -> HexPosition:
        """Convert chunk index to CoverPosition. Returns None if invalid."""
        if 0 <= chunk_idx < len(self.chunks):
            return self.chunks[chunk_idx].position
        return None

    def neighbors_of(self, chunk_idx: int) -> list[int]:
        """Return indices of neighboring chunks. -1 for missing neighbors."""
        pos = self.index_to_coverposition(chunk_idx)
        if pos is None:
            return [-1] * 6
        
        neighbors = []
        for direction in HexPosition.directions():
            neighbor_pos = pos + (direction * self.distance)
            neighbors.append(self.coverposition_to_index(neighbor_pos))
        return neighbors

    def neighbor_in_direction(self, chunk_idx: int, direction: HexPosition) -> int:
        """Return index of neighbor in given direction. -1 if missing."""
        pos = self.index_to_coverposition(chunk_idx)
        if pos is None:
            return -1
        neighbor_pos = pos + (direction * self.distance)
        return self.coverposition_to_index(neighbor_pos)

    
    def encode(self):
        ret = f"+cover:\n"
        ret += f"id:{self.ident}\n"
        ret += f"rings:{self.rings}\n"
        ret += f"halo_rings:{self.halo_rings}\n"
        ret += f"+terrain:\n"
        ret += self.terrain.encode()
        ret += f"-terrain:\n"
        ret += f"-cover:\n"
        return ret

    @staticmethod
    def decode(s: str) -> 'ChunkCover':
        """Parse a formatted string and create a ChunkCover from it."""
        lines = s.strip().split('\n')
        
        rings = None
        halo_rings = None
        terrain_lines = []
        in_terrain = False
        in_cover = False
        ident = None
        
        for line in lines:
            if line.startswith('+cover:'):
                in_cover = True
                continue
            if line.startswith('-cover:'):
                break
            
            if not in_cover:
                continue
                
            if line.startswith('+terrain:'):
                in_terrain = True
                continue
            if line.startswith('-terrain:'):
                in_terrain = False
                continue
                
            if in_terrain:
                terrain_lines.append(line)
            elif line.startswith('rings:'):
                rings = int(line.split(':')[1])
            elif line.startswith('halo_rings:'):
                halo_rings = int(line.split(':')[1])
            elif line.startswith('id:'):
                ident = int(line.split(':')[1])
        
        terrain = Terrain.decode('\n'.join(terrain_lines))
        cover = ChunkCover(terrain, rings=rings, halo_rings=halo_rings,ident=ident)
        return cover





# %% ../nbs/11_Scale.ipynb #7a6434a7
class  HFFT:
    """ Helper Class that implements https://en.wikipedia.org/wiki/Hexagonal_fast_Fourier_transform . """


    def __init__(self,grid:HexGrid,field:np.ndarray):
        """Split elevations into HECS format: (even_rows, odd_rows)."""
        self.grid = grid
        self.field = field
    
        data = field.reshape(grid.nRows, grid.nCols)
        self.even_rows = data[::2].copy()
        self.odd_rows = data[1::2].copy()

    def from_hecs(self) -> np.ndarray:
        """Recombine HECS sub-arrays back to flat array."""
        nRows = self.even_rows.shape[0] + self.odd_rows.shape[0]
        nCols = self.even_rows.shape[1]
        result = np.zeros((nRows, nCols))
        result[::2] = self.even_rows
        result[1::2] = self.odd_rows
        return result.flatten()



# %% ../nbs/11_Scale.ipynb #79efbaa9
@patch
def add_fractal_detail(self: HFFT, upsampled, scale, octaves=3, persistence=0.5, seed=None):
    """Add fractal noise scaled to match local variance."""
    rng = np.random.default_rng(seed)
    
    # Local variance guides noise amplitude
    local_mean = uniform_filter(upsampled, size=scale*2)
    local_var = uniform_filter((upsampled - local_mean)**2, size=scale*2)
    
    noise = np.zeros_like(upsampled)
    for octave in range(octaves):
        freq = 2 ** octave
        amp = persistence ** octave
        noise += amp * rng.standard_normal(upsampled.shape) / freq
    
    return upsampled + noise * np.sqrt(local_var) * 0.3


# %% ../nbs/11_Scale.ipynb #9eb0a1dd
@patch
def forward(self:HFFT) -> tuple[np.ndarray, np.ndarray]:
    """Forward HFFT - returns frequency domain representation."""
    # Standard 2D FFT on each sub-array
    even_fft = np.fft.fft2(self.even_rows)
    odd_fft = np.fft.fft2(self.odd_rows)
    
    # Twiddle factor for the half-sample horizontal shift
    cols = self.odd_rows.shape[1]
    k = np.fft.fftfreq(cols) * np.pi  # half-sample shift
    twiddle = np.exp(-1j * k)
    
    odd_fft = odd_fft * twiddle[np.newaxis, :]
    
    return even_fft, odd_fft


# %% ../nbs/11_Scale.ipynb #894b07fe
@patch
def inverse(self: HFFT, even_fft: np.ndarray, odd_fft: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """Inverse HFFT - returns spatial domain."""
    # Undo twiddle factor
    cols = odd_fft.shape[1]
    k = np.fft.fftfreq(cols) * np.pi
    twiddle = np.exp(1j * k)  # Note: positive exponent to undo
    
    odd_fft = odd_fft * twiddle[np.newaxis, :]
    
    # Inverse FFT
    even_spatial = np.fft.ifft2(even_fft).real
    odd_spatial = np.fft.ifft2(odd_fft).real
    
    return even_spatial, odd_spatial


# %% ../nbs/11_Scale.ipynb #ce139c87
@patch
def upsample_simple(self: HFFT, scale: int = 2, pad_size: int = None) -> tuple[np.ndarray, int, int]:
    """Upsampling with mirror padding to reduce edge artifacts."""
    
    def upsample_2d(arr, scale, pad_size):
        """Standard 2D FFT upsampling with mirror padding."""
        # Default pad size
        if pad_size is None:
            pad_size = max(2, arr.shape[0] // 4)
        
        # Mirror pad before FFT
        padded_arr = np.pad(arr, ((pad_size, pad_size), (pad_size, pad_size)), mode='reflect')
        
        # FFT
        fft = np.fft.fft2(padded_arr)
        ny, nx = padded_arr.shape
        
        # Zero-pad in frequency domain
        target = np.zeros((ny * scale, nx * scale), dtype=complex)
        target[:ny//2, :nx//2] = fft[:ny//2, :nx//2]
        target[:ny//2, -nx//2:] = fft[:ny//2, -nx//2:]
        target[-ny//2:, :nx//2] = fft[-ny//2:, :nx//2]
        target[-ny//2:, -nx//2:] = fft[-ny//2:, -nx//2:]
        
        # Inverse FFT
        result = np.fft.ifft2(target).real * scale**2
        
        # Crop back to remove padding (scaled)
        crop = pad_size * scale
        return result[crop:-crop, crop:-crop]
    
    even_up = upsample_2d(self.even_rows, scale, pad_size)
    odd_up = upsample_2d(self.odd_rows, scale, pad_size)
    
    # Trim to match (handle odd row counts)
    min_rows = min(even_up.shape[0], odd_up.shape[0])
    even_up = even_up[:min_rows]
    odd_up = odd_up[:min_rows]
    nRows = min_rows * 2
    
    result = np.zeros((nRows, even_up.shape[1]))
    result[::2] = even_up
    result[1::2] = odd_up
    
    return result.flatten(), nRows, even_up.shape[1]


# %% ../nbs/11_Scale.ipynb #a4d7bbd7
@patch
def upsample_with_detail(self: HFFT, scale: int = 2, octaves: int = 3, 
                          persistence: float = 0.5) -> tuple[np.ndarray, int, int]:
    """Upsample with added fractal detail."""
    upsampled, nRows, nCols = self.upsample_simple(scale)
    upsampled_2d = upsampled.reshape(nRows, nCols)
    upsampled_2d = self.add_fractal_detail(upsampled_2d, scale, octaves, persistence)
    return upsampled_2d.flatten(), nRows, nCols


# %% ../nbs/11_Scale.ipynb #eae636aa
@patch  
def upsample_progressive(self: HFFT, total_scale: int = 4, 
                         octaves: int = 2, persistence: float = 0.4) -> tuple[np.ndarray, int, int]:
    """Upsample in 2x steps, adding detail at each level."""
    data = self.field.copy()
    nRows, nCols = self.grid.nRows, self.grid.nCols
    
    steps = int(np.log2(total_scale))
    for step in range(steps):
        hfft = HFFT(HexGrid(nRows, nCols, 10, self.grid.style), data)
        upsampled, nRows, nCols = hfft.upsample_simple(scale=2)
        upsampled_2d = upsampled.reshape(nRows, nCols)
        upsampled_2d = hfft.add_fractal_detail(upsampled_2d, scale=2, octaves=octaves, persistence=persistence)
        data = upsampled_2d.flatten()
    
    return data, nRows, nCols


# %% ../nbs/11_Scale.ipynb #3a07da49
@patch
def mapAround(self: ChunkCover, origin=None, alwaysWater=True, water_depth=-100) -> Terrain:
    """Create rectangular terrain around a chunk with edge mirroring for FFT.
    
    Extracts the region covering center + 6 neighbor chunks.
    Uses reflection padding at terrain boundaries to handle edges.
    Invalid (padded) regions are filled with water_depth.
    """
    grid = self.terrain.hexGrid
    if origin is None:
        origin = grid.middle
    
    center_row = origin // grid.nCols
    center_col = origin % grid.nCols
    
    # Region size to cover center + 6 neighbors
    extent = 3 * self.rings + self.halo_rings
    
    # Reshape to 2D for padding
    elev_2d = self.terrain.elevations.reshape(grid.nRows, grid.nCols)
    field_2d = {k: v.reshape(grid.nRows, grid.nCols) for k, v in self.terrain.fields.items()}
    
    # Calculate padding needed
    pad_top = max(0, extent - center_row)
    pad_bottom = max(0, (center_row + extent + 1) - grid.nRows)
    pad_left = max(0, extent - center_col)
    pad_right = max(0, (center_col + extent + 1) - grid.nCols)
    
    # Reflect pad to mirror edges
    elev_padded = np.pad(elev_2d, ((pad_top, pad_bottom), (pad_left, pad_right)), mode='reflect')
    field_padded = {k: np.pad(v, ((pad_top, pad_bottom), (pad_left, pad_right)), mode='reflect') 
                    for k, v in field_2d.items()}
    
    # Extract region around center
    start_row = center_row - extent + pad_top
    start_col = center_col - extent + pad_left
    new_rows = 2 * extent + 1
    new_cols = 2 * extent + 1
    
    new_elev = elev_padded[start_row:start_row+new_rows, start_col:start_col+new_cols].copy()
    new_fields = {k: v[start_row:start_row+new_rows, start_col:start_col+new_cols].copy() 
                  for k, v in field_padded.items()}
    
    # Create new terrain
    new_grid = HexGrid(nRows=new_rows, nCols=new_cols, radius=grid.radius, style=grid.style)
    new_terrain = Terrain(bounds=new_grid.bounds, radius=new_grid.radius)
    new_terrain.hexGrid = new_grid
    new_terrain.elevations = new_elev.flatten()
    new_terrain.fields = {k: v.flatten() for k, v in new_fields.items()}
    
    # Mark invalid regions (from reflection padding)
    invalid = set()
    for row in range(new_rows):
        for col in range(new_cols):
            orig_row = (start_row - pad_top) + row
            orig_col = (start_col - pad_left) + col
            
            if orig_row < 0 or orig_row >= grid.nRows or orig_col < 0 or orig_col >= grid.nCols:
                invalid.add(row * new_cols + col)
    
    # Fill invalid hexes with deep water
    for i in range(len(new_terrain.elevations)):
        if new_terrain.elevations[i] < 1:
            new_terrain.elevations[i] = water_depth

    if invalid and alwaysWater:
        for idx in invalid:
            new_terrain.elevations[idx] = water_depth
    
    new_grid.invalidRegion = invalid
    
    return new_terrain


# %% ../nbs/11_Scale.ipynb #dbc0695b
@patch
def waterAround(self: ChunkCover, origin=None) -> int:
    """Count how many boundary hexes of the invalid region touch water (elev ≤ 0).
    
    Returns 0 if there's no invalid region (fully interior chunk).
    """
    terrain = self.mapAround(origin, alwaysWater=False)
    grid = terrain.hexGrid
    invalid = getattr(grid, 'invalidRegion', set())
    
    if not invalid:
        return 0
    
    invalid_region = HexRegion(invalid, grid)
    boundary = invalid_region.outside()
    
    return sum(1 for idx in boundary.hexes if terrain.elevations[idx] <= 0)


# %% ../nbs/11_Scale.ipynb #0454e298
def _scale_invalid_region(orig_invalid: set, orig_cols: int, new_cols: int, 
                          scale: int, max_idx: int) -> set:
    """Scale invalid region indices by scale factor."""
    new_invalid = set()
    for idx in orig_invalid:
        orig_row = idx // orig_cols
        orig_col = idx % orig_cols
        for dr in range(scale):
            for dc in range(scale):
                new_idx = (orig_row * scale + dr) * new_cols + (orig_col * scale + dc)
                if 0 <= new_idx < max_idx:
                    new_invalid.add(new_idx)
    return new_invalid


@patch
def zoomChunkSimple(self: ChunkCover, origin=None, scale: int = 2, method: str = 'bilinear') -> Terrain:
    """Zoom into a chunk region with simple upsampling (no FFT).
    
    Pipeline: mapAround → terrain.upsample → scale_invalid
    
    Args:
        origin: Center hex index (defaults to grid middle)
        scale: Upsampling factor (default 2)
        method: Interpolation method ('bilinear', 'nearest', etc.)
    
    Returns:
        Upsampled Terrain with invalidRegion scaled appropriately
    """
    # Step 1: Extract region around chunk with reflection padding
    region = self.mapAround(origin)
    
    # Step 2: Upsample using existing terrain method
    up_terrain = region.upsample(scale=float(scale), method=method)
    
    # Step 3: Scale up invalid region
    new_invalid = _scale_invalid_region(
        orig_invalid=region.hexGrid.invalidRegion,
        orig_cols=region.hexGrid.nCols,
        new_cols=up_terrain.hexGrid.nCols,
        scale=scale,
        max_idx=len(up_terrain.hexGrid.hexes)
    )
    up_terrain.hexGrid.invalidRegion = new_invalid
    
    return up_terrain


@patch
def zoomChunk(self: ChunkCover, origin=None, scale: int = 2, 
              progressive: bool = False, octaves: int = 2, 
              persistence: float = 0.4) -> Terrain:
    """Zoom into a chunk region with HFFT upsampling and proper invalid region tracking.
    
    Pipeline: mapAround → HFFT upsample → scale_invalid
    
    Args:
        origin: Center hex index (defaults to grid middle)
        scale: Upsampling factor (default 2, use powers of 2 for progressive)
        progressive: If True, upsample in 2x steps for smoother results (recommended for scale >= 4)
        octaves: Fractal noise octaves for detail (default 2)
        persistence: Fractal noise persistence (default 0.4)
    
    Returns:
        Upsampled Terrain with invalidRegion scaled appropriately
    """
    # Step 1: Extract region around chunk with reflection padding
    region = self.mapAround(origin)
    
    # Step 2: Upsample with HFFT
    hfft = HFFT(region.hexGrid, region.elevations)
    
    if progressive and scale > 2:
        upsampled_elev, new_rows, new_cols = hfft.upsample_progressive(
            total_scale=scale, octaves=octaves, persistence=persistence
        )
    else:
        upsampled_elev, new_rows, new_cols = hfft.upsample_with_detail(
            scale=scale, octaves=octaves, persistence=persistence
        )
    
    # Step 3: Create upsampled terrain
    new_radius = region.hexGrid.radius / scale
    up_grid = HexGrid(nRows=new_rows, nCols=new_cols,
                      radius=new_radius,
                      style=region.hexGrid.style)
    
    up_terrain = Terrain(bounds=up_grid.bounds, radius=new_radius)
    up_terrain.hexGrid = up_grid
    up_terrain.elevations = upsampled_elev
    
    # Step 4: Upsample fields
    for name, field_data in region.fields.items():
        field_hfft = HFFT(region.hexGrid, field_data)
        if progressive and scale > 2:
            up_field, _, _ = field_hfft.upsample_progressive(
                total_scale=scale, octaves=octaves, persistence=persistence
            )
        else:
            up_field, _, _ = field_hfft.upsample_with_detail(
                scale=scale, octaves=octaves, persistence=persistence
            )
        up_terrain.fields[name] = up_field
    
    # Step 5: Scale up invalid region
    new_invalid = _scale_invalid_region(
        orig_invalid=region.hexGrid.invalidRegion,
        orig_cols=region.hexGrid.nCols,
        new_cols=new_cols,
        scale=scale,
        max_idx=len(up_grid.hexes)
    )
    up_grid.invalidRegion = new_invalid
    
    return up_terrain


# %% ../nbs/11_Scale.ipynb #afc5b2e4
@patch
def zoomChunkCombined(self: ChunkCover, origin=None, scale: int = 2, 
                      method: str = 'bilinear', octaves: int = 2, 
                      persistence: float = 0.3, detail_strength: float = 0.2) -> Terrain:
    """Zoom with interpolated base + HFFT detail overlay.
    
    Pipeline: 
    1. mapAround → terrain.upsample (base structure)
    2. HFFT.upsample_progressive → extract detail (high-frequency component)
    3. Blend: base + detail_strength * detail
    
    Args:
        origin: Center hex index
        scale: Upsampling factor
        method: Interpolation method for base ('bilinear', 'cubic')
        octaves: Fractal noise octaves
        persistence: Fractal noise persistence
        detail_strength: How much HFFT detail to add (0-1, default 0.2)
    
    Returns:
        Upsampled Terrain with base interpolation + fractal detail
    """
    # Step 1: Get interpolated base
    region = self.mapAround(origin)
    up_terrain = region.upsample(scale=float(scale), method=method)
    
    # Step 2: Generate HFFT detail
    hfft = HFFT(region.hexGrid, region.elevations)
    if scale > 2:
        hfft_elev, _, _ = hfft.upsample_progressive(
            total_scale=scale, octaves=octaves, persistence=persistence
        )
    else:
        hfft_elev, _, _ = hfft.upsample_with_detail(
            scale=scale, octaves=octaves, persistence=persistence
        )
    
    # Step 3: Extract high-frequency detail (HFFT - interpolated)
    detail = hfft_elev - up_terrain.elevations
    
    # Step 4: Blend
    up_terrain.elevations = up_terrain.elevations + detail_strength * detail
    
    # Step 5: Scale invalid region
    new_invalid = _scale_invalid_region(
        orig_invalid=region.hexGrid.invalidRegion,
        orig_cols=region.hexGrid.nCols,
        new_cols=up_terrain.hexGrid.nCols,
        scale=scale,
        max_idx=len(up_terrain.hexGrid.hexes)
    )
    up_terrain.hexGrid.invalidRegion = new_invalid
    
    return up_terrain


# %% ../nbs/11_Scale.ipynb #c26d0900
@patch
def carve_region_to_mouth(self: ChunkCover, region: set[int], mouth: int) -> None:
    """Carve terrain so all hexes in region drain to mouth via BFS.
    
    Expands inward from mouth, ensuring each hex is higher than its parent.
    Modifies terrain.elevations in place.
    
    Args:
        region: Set of hex indices to carve
        mouth: Boundary hex where water exits (must be in region)
    """
    
    
    terrain = self.terrain
    
    # BFS from mouth inward
    visited = {mouth}
    queue = deque([mouth])
    
    while queue:
        current = queue.popleft()
        current_elev = terrain.elevations[current]
        
        for neighbor in terrain.hexGrid.neighborsOf(current):
            if neighbor < 0 or neighbor in visited or neighbor not in region:
                continue
            
            visited.add(neighbor)
            
            # Carve: neighbor must be higher than current (water flows downhill to mouth)
            if terrain.elevations[neighbor] <= current_elev:
                terrain.elevations[neighbor] = current_elev + 1
            
            queue.append(neighbor)

@patch
def find_region_mouth(self: ChunkCover, region: set[int], downhill_region: set[int]) -> int:
    """Find the boundary hex in region that touches downhill_region.
    
    Returns the hex with lowest elevation among candidates.
    """
    terrain = self.terrain
    candidates = []
    
    for hex_idx in region:
        for neighbor in terrain.hexGrid.neighborsOf(hex_idx):
            if neighbor in downhill_region:
                candidates.append(hex_idx)
                break
    
    if not candidates:
        # Fallback: lowest hex in region
        return min(region, key=lambda h: terrain.elevations[h])
    
    # Pick lowest candidate (most natural drainage point)
    return min(candidates, key=lambda h: terrain.elevations[h])



# %% ../nbs/11_Scale.ipynb #18bf7704
@patch
def carve_upsampled_watersheds(self: ChunkCover, 
                                coarse_flow: dict[int, int],
                                fine_regions: dict[int, set[int]],
                                invalid_hexes: set[int] = None) -> None:
    """Carve all upsampled regions to respect coarse flow directions.
    
    Args:
        coarse_flow: {coarse_hex: downhill_coarse_hex} (-1 if terminal)
        fine_regions: {coarse_hex: set of fine hex indices}
        invalid_hexes: Set of invalid hex indices to skip
    """
    if invalid_hexes is None:
        invalid_hexes = set()
    
    # Filter invalid hexes from all regions
    filtered_regions = {
        k: v - invalid_hexes 
        for k, v in fine_regions.items()
    }
    # Remove empty regions
    filtered_regions = {k: v for k, v in filtered_regions.items() if v}
    
    # Only process hexes that exist in both dicts
    valid_hexes = set(coarse_flow.keys()) & set(filtered_regions.keys())
    
    sorted_coarse = sorted(valid_hexes, 
                           key=lambda h: self.terrain.elevations[list(filtered_regions[h])[0]])
    
    for coarse_hex in sorted_coarse:
        region = filtered_regions[coarse_hex]
        downhill_coarse = coarse_flow[coarse_hex]
        
        if downhill_coarse < 0 or downhill_coarse not in filtered_regions:
            continue
        
        downhill_region = filtered_regions[downhill_coarse]
        mouth = self.find_region_mouth(region, downhill_region)
        self.carve_region_to_mouth(region, mouth)


# %% ../nbs/11_Scale.ipynb #8d109b89
@patch
def project_watersheds(self: ChunkCover, 
                       coarse_basins: DrainageBasins,
                       fine_regions: dict[int, set[int]],
                       fine_terrain: Terrain) -> list[Watershed]:
    """Project coarse watersheds to fine terrain without O(n²) recomputation."""
    watersheds = []
    
    for coarse_shed in coarse_basins.sheds:
        # Collect fine hexes that belong to this watershed
        fine_hexes = set()
        for coarse_hex in coarse_shed.region.hexes:
            if coarse_hex in fine_regions:
                fine_hexes.update(fine_regions[coarse_hex])
        
        # Filter out invalid hexes
        fine_hexes -= fine_terrain.hexGrid.invalidRegion
        
        if not fine_hexes:
            continue
        
        # Create region on fine grid
        fine_region = HexRegion(hexes=fine_hexes, hexGrid=fine_terrain.hexGrid)
        
        # Find mouth (lowest hex in region)
        mouth = min(fine_hexes, key=lambda h: fine_terrain.elevations[h])
        
        # Simple approach: trace rivers from peaks within this region
        # Find local peaks (hexes higher than all neighbors in region)
        peaks = []
        for h in fine_hexes:
            if fine_terrain.elevations[h] <= 0:
                continue
            neighbors = [n for n in fine_terrain.hexGrid.neighborsOf(h) if n in fine_hexes]
            if all(fine_terrain.elevations[h] >= fine_terrain.elevations[n] for n in neighbors):
                peaks.append(h)
        
        # Create rivers from top peaks
        peaks.sort(key=lambda h: fine_terrain.elevations[h], reverse=True)
        rivers = [River.from_peak(fine_terrain, p) for p in peaks[:5]]
        rivers = [r for r in rivers if r is not None]
        
        if rivers:
            merged = River.combine_rivers(rivers)
            river = max(merged, key=lambda r: len(r.hexes)) if merged else River(fine_terrain)
        else:
            river = River(fine_terrain)
        
        # Skip if no valid river was created
        if river.is_empty:
            continue
        
        # Check if drains to ocean
        river.ocean_outlet = mouth if fine_terrain.elevations[mouth] <= 0 else None
        
        watersheds.append(Watershed(
            region=fine_region,
            tributary=river,
            style=coarse_shed.style
        ))
    
    return watersheds


# %% ../nbs/11_Scale.ipynb #9d9f25f1
# Project coarse watersheds to zoomed terrain
# Build mapping: coarse hex -> fine hexes
@patch
def upscaleWater(self:TerraDemo,demoTerr:Terrain,useSimple=True):
    #demoTerr = TerraDemo().sanFran_map()
    demoTerr.compute_weather()
    demoBasins = DrainageBasins(demoTerr)
    cover = ChunkCover(demoTerr, rings=3, halo_rings=1)
    grid = demoTerr.hexGrid

    # Try the right edge near the middle (where there's land)
    # Middle row, last column
    coastal_origin = (grid.nRows // 2) * grid.nCols + (grid.nCols - 1)
    print(f"Testing at index {coastal_origin}, elevation: {demoTerr.elevations[coastal_origin]}")

    # Zoom into that coastal edge
    #zoomed = cover.zoomChunk(origin=coastal_origin, scale=2)
    if useSimple:
        zoomed = cover.zoomChunkSimple(origin=coastal_origin, scale=2)
    else:
        zoomed = cover.zoomChunk(origin=coastal_origin,progressive=True, scale=4)
        
    zoomed.climate = demoTerr.climate
    zoomed.geo = demoTerr.geo # this is wrong, but close enough

    print(f"Zoomed grid: {zoomed.hexGrid.nRows}x{zoomed.hexGrid.nCols}")
    print(f"Invalid hexes: {len(zoomed.hexGrid.invalidRegion)}")

    # Visualize
    zoomed.colorMap()
    zoomed.hexGrid.update()

    scale = 2
    coarse_grid = demoTerr.hexGrid
    fine_grid = zoomed.hexGrid

    # Figure out which coarse hexes map to which fine hexes
    # The zoom was centered at coastal_origin, so we need the offset
    extent = 3 * cover.rings + cover.halo_rings
    center_row = coastal_origin // coarse_grid.nCols
    center_col = coastal_origin % coarse_grid.nCols

    # Build coarse_flow from demoBasins (hex -> downhill hex)
    coarse_flow = {}
    for shed in demoBasins.sheds:
        directions = demoTerr.flow_directions()
        for h in shed.region.hexes:
            coarse_flow[h] = directions[h]

    # Map coarse hexes to fine hex regions
    fine_regions = {}
    for coarse_row in range(center_row - extent, center_row + extent + 1):
        for coarse_col in range(center_col - extent, center_col + extent + 1):
            if 0 <= coarse_row < coarse_grid.nRows and 0 <= coarse_col < coarse_grid.nCols:
                coarse_idx = coarse_row * coarse_grid.nCols + coarse_col
                
                # Map to fine region
                fine_start_row = (coarse_row - (center_row - extent)) * scale
                fine_start_col = (coarse_col - (center_col - extent)) * scale
                
                fine_hexes = set()
                for dr in range(scale):
                    for dc in range(scale):
                        fine_row = fine_start_row + dr
                        fine_col = fine_start_col + dc
                        if 0 <= fine_row < fine_grid.nRows and 0 <= fine_col < fine_grid.nCols:
                            fine_idx = fine_row * fine_grid.nCols + fine_col
                            if fine_idx not in zoomed.hexGrid.invalidRegion:
                                fine_hexes.add(fine_idx)
                
                if fine_hexes:
                    fine_regions[coarse_idx] = fine_hexes

    print(f"Mapped {len(fine_regions)} coarse hexes to fine regions")

    # Create a ChunkCover for the zoomed terrain to use carving
    zoomed_cover = ChunkCover(zoomed, rings=cover.rings, halo_rings=cover.halo_rings)

    # Carve the upsampled watersheds
    # Carve the upsampled watersheds, skipping invalid hexes
    zoomed_cover.carve_upsampled_watersheds(
        coarse_flow, 
        fine_regions, 
        invalid_hexes=zoomed.hexGrid.invalidRegion
    )



    # Recompute weather for the carved terrain
    zoomed.compute_weather()

    # Now compute watersheds on the zoomed terrain
    zoomed_sheds = cover.project_watersheds(demoBasins, fine_regions, zoomed)
    zoomed_basins = DrainageBasins(zoomed, compute=False)
    zoomed_basins.sheds = zoomed_sheds

    print(f"Found {len(zoomed_sheds)} watersheds in zoomed terrain")

    # Visualize
    zoomed.colorMap()
    zoomed.hexGrid.update()

    # Draw watersheds
    watershed_svg = ""
    for shed in zoomed_sheds:
        watershed_svg += shed.draw()

    #zoomed_basins.draw_watersheds(top_n=5, max_width=fine_grid.radius * 0.5)
    #zoomed.hexGrid.builder.adjust("rivers", watershed_svg)
    zoomed.builder.adjust("watersheds", zoomed_basins.draw_watersheds())
    textStyle = StyleCSS("textStyle", fill="white", font_size="1em", 
                        filter="drop-shadow(2px 2px 1px rgba(0,0,0,.7))")
    zoomed.hexGrid.builder.add_style(textStyle)
    zoomed.hexGrid.builder.add_centered_text(
        f"Zoomed watersheds - {len(zoomed_sheds)} basins",
        y_offset=-zoomed.hexGrid.builder.height/2 + 20,
        class_name=textStyle.name
    )
    #demoTerr.colorMap()
    #demoTerr.hexGrid.update()
    #return demoTerr.hexGrid.builder.show()
    return zoomed.hexGrid.builder.show()

