# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/11_Database.ipynb.

# %% auto #0
__all__ = ['LoadResult', 'SaveResult', 'ChunkRef', 'chunk_to_world', 'world_to_chunk', 'ChunkedTerrainGenerator', 'HexData',
           'HexWeather', 'WatershedMeta', 'TerrainWorld', 'User', 'GeoStorage', 'create_region_coord_mapper',
           'GeoStorageDebugger', 'hex_distance', 'astar_terrain', 'visualize_path', 'refine_coarse_path']

# %% ../nbs/11_Database.ipynb #604269fa
import numpy as np
import sys
import os
import math
from math import radians, cos, sin, sqrt, atan2
import random

#data
from collections import namedtuple
from dataclasses import dataclass,  field, asdict
import json
from typing import List , Optional
from enum import Enum



# %% ../nbs/11_Database.ipynb #3f40cd85
from dataclasses import dataclass
from typing import Optional

from datetime import datetime


# %% ../nbs/11_Database.ipynb #ffbe640f
from fastcore.utils import *
from fasthtml.common import *
from fasthtml.jupyter import *
from fastlite import *
import fasthtml.components as fc
import httpx


# %% ../nbs/11_Database.ipynb #87f4cc2d
from importlib import resources
from pathlib import Path
import tempfile
import shutil
import sqlite3
from dataclasses import dataclass
from typing import Iterator
import numpy as np

# %% ../nbs/11_Database.ipynb #7b40f653
from .climate import TerrainPatterns, DrainageBasins, Geology, TerraDemo, Terrain, GeoBounds, ClimatePreset, TerrainFactory
from .primitives import MapCord, MapSize, MapRect, MapPath, Hex, HexGrid, HexWrapper, HexPosition, hexBackground, HexRegion, unique_windy_edge
from .styles import StyleCSS, SVGBuilder

# %% ../nbs/11_Database.ipynb #480e76c9
from .geology import River, Watershed

# %% ../nbs/11_Database.ipynb #2eb30d94
import asyncio
from dataclasses import dataclass

# %% ../nbs/11_Database.ipynb #43713f55
LoadResult = namedtuple('LoadResult', ['data', 'status', 'context'])
SaveResult = namedtuple('SaveResult', ['id', 'status', 'context'])

# %% ../nbs/11_Database.ipynb #6acb6570
@dataclass
class ChunkRef:
    """Reference to a chunk in the world - uses HexPosition for coordinates."""
    position: HexPosition  # Chunk's position in chunk-space (q+r+s=0)
    rings: int             # Hex rings per chunk
    
    @property
    def center_hex(self) -> HexPosition:
        """World hex coordinates of chunk center."""
        spacing = self.rings * 2
        return spacing * self.position
    
    @property
    def key(self) -> tuple[int, int, int]:
        """Hashable key for dict storage."""
        return (self.position.q, self.position.r, self.position.s)
    
    def __hash__(self):
        return hash(self.key)


def chunk_to_world(chunk: ChunkRef, local_pos: HexPosition) -> HexPosition:
    """Map local hex position within chunk to world coordinates."""
    return chunk.center_hex + local_pos


def world_to_chunk(world_pos: HexPosition, chunk_rings: int) -> tuple[HexPosition, HexPosition]:
    """Map world position to (chunk_position, local_position_within_chunk)."""
    spacing = chunk_rings * 2
    
    chunk_q = world_pos.q // spacing
    chunk_r = world_pos.r // spacing
    chunk_s = -chunk_q - chunk_r
    
    chunk_pos = HexPosition(chunk_q, chunk_r, chunk_s)
    chunk_center = spacing * chunk_pos
    local_pos = world_pos - chunk_center
    
    return chunk_pos, local_pos

# %% ../nbs/11_Database.ipynb #32243ceb
class ChunkedTerrainGenerator:
    """Generate and manage large terrains via chunking."""
    
    def __init__(self, storage: 'GeoStorage', 
                 coarse_radius: float = 100,
                 fine_radius: float = 10,
                 chunk_rings: int = 20,
                 halo_rings: int = 5):
        """
        Args:
            storage: GeoStorage for persistence
            coarse_radius: Hex radius for global overview map
            fine_radius: Hex radius for detailed chunks
            chunk_rings: Rings of hexes per chunk
            halo_rings: Extra rings for edge computation (weather, BFS)
        """
        self.storage = storage
        self.coarse_radius = coarse_radius
        self.fine_radius = fine_radius
        self.chunk_rings = chunk_rings
        self.halo_rings = halo_rings
        
        self.coarse_world_id = None
        self.chunk_world_ids = {}  # ChunkRef.key -> world_id
        self._plates = None
        self._coarse_terrain = None  # Cache for generation
    
    @property
    def scale(self) -> float:
        """Resolution scale factor between coarse and fine."""
        return self.coarse_radius / self.fine_radius
    
    # ─────────────────────────────────────────────────────────
    # Coordinate utilities
    # ─────────────────────────────────────────────────────────
    
    def world_to_chunk_ref(self, world_pos: HexPosition) -> ChunkRef:
        """Get the chunk containing a world position."""
        chunk_pos, _ = world_to_chunk(world_pos, self.chunk_rings)
        return ChunkRef(chunk_pos, self.chunk_rings)
    
    def local_to_world(self, chunk: ChunkRef, local_pos: HexPosition) -> HexPosition:
        """Map local chunk position to world coordinates."""
        return chunk_to_world(chunk, local_pos)
    
    def chunk_center_in_coarse(self, chunk: ChunkRef) -> HexPosition:
        """Get chunk center position in coarse grid coordinates."""
        world_center = chunk.center_hex
        coarse_q = int(world_center.q / self.scale)
        coarse_r = int(world_center.r / self.scale)
        return HexPosition(coarse_q, coarse_r, -coarse_q - coarse_r)
    
    # ─────────────────────────────────────────────────────────
    # Phase 1: Global coarse map
    # ─────────────────────────────────────────────────────────
    
    def generate_coarse(self, bounds: MapRect, 
                        num_plates: int = 15,
                        ocean_fraction: float = 0.4,
                        oceanic_sides: list = None,
                        name: str = "world_coarse",
                        max_lakes = 0
                        
                        ) -> Terrain:
        """Generate low-resolution global map for coastlines and plate structure."""
        
        terrain, plates = Terrain.fromSeeds(
            bounds,
            radius=self.coarse_radius,
            num_plates=num_plates,
            ocean_fraction=ocean_fraction,
            oceanic_sides=oceanic_sides or [],
            subdivisions=2,
        )
        
        # Compute distance from coast at coarse level
        terrain.compute_distance_from_coast()

        if max_lakes is not None:
            terrain.carve_to_ocean(num_lakes=max_lakes)
        
        # Save to storage
        result = self.storage.save_world(terrain, name=name)
        self.coarse_world_id = result.id
        self._plates = plates
        self._coarse_terrain = terrain  # Cache for chunk generation
        
        return terrain
    
    # ─────────────────────────────────────────────────────────
    # Phase 2: Chunk generation
    # ─────────────────────────────────────────────────────────
    
    def chunk_refs(self, max_ring: int) -> Iterator[ChunkRef]:
        """Yield ChunkRefs in spiral order from center outward."""
        for ring in range(max_ring + 1):
            for pos in HexPosition.origin().ring(ring):
                yield ChunkRef(pos, self.chunk_rings)
    
    def chunks_for_coarse(self, coarse_grid: HexGrid) -> Iterator[ChunkRef]:
        """Yield ChunkRefs covering the coarse grid extent."""
        spacing = self.chunk_rings * 2
        max_extent = max(coarse_grid.nRows, coarse_grid.nCols)
        max_chunk_ring = (max_extent // spacing) + 1
        return self.chunk_refs(max_chunk_ring)
    
    def generate_chunk(self, chunk: ChunkRef, coarse_terrain: Terrain = None) -> Terrain:
        """Generate detailed chunk by upsampling coarse region."""
        
        coarse = coarse_terrain or self._coarse_terrain
        if coarse is None:
            raise ValueError("No coarse terrain available")
        
        # Get chunk center in coarse coordinates
        coarse_center = self.chunk_center_in_coarse(chunk)
        
        # Calculate extraction radius in coarse hexes
        # Need enough to cover chunk + halo after upsampling
        coarse_rings = int((self.chunk_rings + self.halo_rings) / self.scale) + 2
        
        # Extract coarse region around chunk center
        extract_result = self.storage.extract_region(
            self.coarse_world_id,
            coarse_center.q, coarse_center.r, coarse_center.s,
            rings=coarse_rings,
            padding=1
        )
        
        if extract_result.status == 'extracted' and extract_result.data is not None:
            chunk_coarse = extract_result.data
        else:
            # Fallback: use full coarse terrain (less efficient)
            chunk_coarse = coarse
        
        # Upsample to fine resolution
        fine_terrain = chunk_coarse.upsample(scale=self.scale, method='bilinear')
        
        # Add deterministic local detail
        self._add_detail(fine_terrain, chunk)
        
        # Set chunk-specific metadata
        fine_terrain.climate = coarse.climate
        fine_terrain.geo = self._compute_chunk_bounds(chunk, coarse.geo)
        
        return fine_terrain
    
    def _add_detail(self, terrain: Terrain, chunk: ChunkRef):
        """Add fractal noise for local variation (deterministic per chunk)."""
        seed = hash(chunk.key) % (2**31)
        np.random.seed(seed)
        
        noise_scale = terrain.elevationDelta * 0.1
        terrain.elevations += np.random.uniform(
            -noise_scale, noise_scale, len(terrain.elevations)
        )
    
    def _compute_chunk_bounds(self, chunk: ChunkRef, world_geo: GeoBounds) -> GeoBounds:
        """Compute geographic bounds for a chunk."""
        if world_geo is None:
            return None
        
        # TODO: proper subdivision based on chunk position and size
        # For now, return world bounds (weather computation will still work)
        return world_geo
    
    # ─────────────────────────────────────────────────────────
    # Phase 3: Weather computation
    # ─────────────────────────────────────────────────────────
    
    def compute_chunk_weather(self, chunk_terrain: Terrain) -> Terrain:
        """Compute weather for a chunk."""
        if 'distance_to_coast' not in chunk_terrain.fields:
            chunk_terrain.compute_distance_from_coast()
        
        if chunk_terrain.climate:
            chunk_terrain.compute_weather()
        
        return chunk_terrain
    
    # ─────────────────────────────────────────────────────────
    # Phase 4: Save/Load
    # ─────────────────────────────────────────────────────────
    
    def save_chunk(self, terrain: Terrain, chunk: ChunkRef) -> int:
        """Save a chunk to storage."""
        p = chunk.position
        name = f"chunk_{p.q}_{p.r}_{p.s}"
        
        # Trim halo before saving
        core_terrain = self._trim_halo(terrain, chunk.rings)
        
        result = self.storage.save_world(core_terrain, name=name)
        self.chunk_world_ids[chunk.key] = result.id
        
        # Save weather if computed
        if 'temperature' in core_terrain.fields:
            self.storage.save_weather(core_terrain, result.id, season="annual")
        
        return result.id
    
    def load_chunk(self, chunk: ChunkRef) -> Terrain:
        """Load a chunk from storage."""
        world_id = self.chunk_world_ids.get(chunk.key)
        if world_id is None:
            return None
        result = self.storage.load_world(world_id)
        return result.data if result.status == 'loaded' else None
    
    def load_chunk_at(self, world_pos: HexPosition) -> Terrain:
        """Load the chunk containing a world position."""
        chunk = self.world_to_chunk_ref(world_pos)
        return self.load_chunk(chunk)
    
    def _trim_halo(self, terrain: Terrain, core_rings: int) -> Terrain:
        """Remove halo hexes, keep only core region."""
        grid = terrain.hexGrid
        
        # Find hexes within core_rings of center
        core_indices = set()
        for i in range(len(grid.hexes)):
            pos = grid.index_to_hexposition(i, origin_index=grid.middle)
            if abs(pos) <= core_rings:
                core_indices.add(i)
        
        if len(core_indices) == len(grid.hexes):
            return terrain  # No halo to trim
        
        # Create trimmed grid and terrain
        core_region = HexRegion(core_indices, grid)
        trimmed_grid, trimmed_region, mapper = core_region.crop_to_centered_grid(
            style=grid.style, 
            padding=0
        )
        
        # Build trimmed terrain
        trimmed = Terrain.__new__(Terrain)
        trimmed.hexGrid = trimmed_grid
        trimmed.elevations = np.zeros(len(trimmed_grid.hexes))
        trimmed.fields = {}
        trimmed.seaLevel = terrain.seaLevel
        trimmed.elevationDelta = terrain.elevationDelta
        trimmed.climate = terrain.climate
        trimmed.geo = terrain.geo
        trimmed.colorLevels = terrain.colorLevels
        trimmed.path = ""
        
        # Map data from old to new indices
        for new_idx in range(len(trimmed_grid.hexes)):
            old_idx = mapper(new_idx)
            if 0 <= old_idx < len(terrain.elevations):
                trimmed.elevations[new_idx] = terrain.elevations[old_idx]
                for field_name, field_data in terrain.fields.items():
                    if field_name not in trimmed.fields:
                        trimmed.fields[field_name] = np.zeros(len(trimmed_grid.hexes))
                    trimmed.fields[field_name][new_idx] = field_data[old_idx]
        
        return trimmed
    
    # ─────────────────────────────────────────────────────────
    # Index mapping
    # ─────────────────────────────────────────────────────────
    
    def create_chunk_mapper(self, chunk: ChunkRef, chunk_grid: HexGrid):
        """Create mapper from chunk grid index to world HexPosition."""
        def mapper(chunk_idx: int) -> HexPosition:
            local_pos = chunk_grid.index_to_hexposition(chunk_idx, origin_index=chunk_grid.middle)
            return chunk_to_world(chunk, local_pos)
        return mapper
    
    def create_world_to_chunk_mapper(self, chunk: ChunkRef, chunk_grid: HexGrid):
        """Create mapper from world HexPosition to chunk grid index."""
        def mapper(world_pos: HexPosition) -> int:
            local_pos = world_pos - chunk.center_hex
            return chunk_grid.hexposition_to_index(local_pos, origin_index=chunk_grid.middle)
        return mapper
    
    


# %% ../nbs/11_Database.ipynb #21f4c247
@dataclass  
class HexData:
    id: int = None
    world_id: int = 0
    q: int = 0
    r: int = 0
    s: int = 0
    grid_index: int = 0
    elevation: float = 0.0
    latitude: Optional[float] = None
    longitude: Optional[float] = None
    distance_from_coast: Optional[float] = None
    watershed_id: Optional[int] = None  # NEW: FK to WatershedMeta
    modified: int = 0


# %% ../nbs/11_Database.ipynb #a40e12c3
@dataclass
class HexWeather:
    """Weather data for a hex at a point in time."""
    id: int = None
    world_id: int = 0
    q: int = 0
    r: int = 0
    s: int = 0
    # Core weather fields
    temperature: float = 0.0           # °C
    precipitation: float = 0.0         # mm/year
    humidity: Optional[float] = None   # %
    # Derived/computed fields
    climate_pet: Optional[float] = None          # potential evapotranspiration
    aridity_index: Optional[float] = None
    temp_seasonality: Optional[float] = None
    precip_seasonality: Optional[float] = None
    distance_from_coast: Optional[float] = None  # hex units
    # Temporal
    season: str = ""                   # e.g., "annual", "summer", "winter"
    modified: int = 0


# %% ../nbs/11_Database.ipynb #34fc4847
@dataclass
class WatershedMeta:
    """Metadata for a stored watershed."""
    id: int = None
    world_id: int = 0
    name: str = ""
    # Terminal hex (outlet)
    terminal_q: int = 0
    terminal_r: int = 0
    terminal_s: int = 0
    is_ocean: bool = True
    # Stats
    total_flow: float = 0.0
    area_hexes: int = 0
    # Encoded data
    river_tree: str = ""   # River.encode()
    style: str = ""        # StyleCSS.encode()
    created: int = 0
    modified: int = 0

# %% ../nbs/11_Database.ipynb #4698a4e4
@dataclass
class TerrainWorld:
    """Metadata for a stored terrain."""
    id: int = None
    name: str = ""
    hex_radius: float = 25.0
    nrows: int = 0
    ncols: int = 0
    sea_level: float = 0.0
    elevation_delta: float = 90.0
    # Encoded extras (climate, geo bounds, etc)
    extras: str = ""
    created: int = 0
    modified: int = 0



# %% ../nbs/11_Database.ipynb #e3c63ae8
@dataclass
class User:
    username: str
    email: str
    password: str
    created: int  # Unix timestamp
    sessionID: str
    activeWorld: int # a link into world_id for world 
    id: int = None

# %% ../nbs/11_Database.ipynb #7362b49f
class GeoStorage:

    def __init__(self, custom_path=None):
        path = GeoStorage.get_db_path(custom_path)
        self.path = path
        self.createDB()

    def createDB(self):
        db = database(self.path)
        self.db = db

        # Create tables using dataclasses
        db.create(TerrainWorld, pk='id', if_not_exists=True, transform=True)
        db.create(HexData, pk='id', if_not_exists=True, transform=True)
        db.create(User, pk='id', if_not_exists=True, transform=True)

        db.create(HexWeather, pk='id', if_not_exists=True, transform=True)

        # NEW: Watershed table
        db.create(WatershedMeta, pk='id', if_not_exists=True, transform=True)

        # After creating tables
        db.execute("CREATE INDEX IF NOT EXISTS idx_hex_world ON hex_data(world_id)")
        db.execute("CREATE INDEX IF NOT EXISTS idx_hex_coords ON hex_data(world_id, q, r, s)")
        db.execute("CREATE INDEX IF NOT EXISTS idx_hex_grid ON hex_data(world_id, grid_index)")


        db.execute("CREATE INDEX IF NOT EXISTS idx_hex_temporal ON hex_data(world_id, q, r, s, modified DESC)")

        

         # NEW: Index for watershed queries
        db.execute("CREATE INDEX IF NOT EXISTS idx_hex_watershed ON hex_data(world_id, watershed_id)")
        db.execute("CREATE INDEX IF NOT EXISTS idx_watershed_world ON watershed_meta(world_id)")

        # Indices for weather queries
        db.execute("CREATE INDEX IF NOT EXISTS idx_weather_world ON hex_weather(world_id)")
        db.execute("CREATE INDEX IF NOT EXISTS idx_weather_coords ON hex_weather(world_id, q, r, s)")
        db.execute("CREATE INDEX IF NOT EXISTS idx_weather_temporal ON hex_weather(world_id, q, r, s, modified DESC)")
        db.execute("CREATE INDEX IF NOT EXISTS idx_weather_season ON hex_weather(world_id, season)")

        self.weather = db.t.hex_weather

        

        # Store table references using db.t notation
        self.users = db.t.user
        self.hexes = db.t.hex_data
        self.worlds = db.t.terrain_world
        self.watersheds = db.t.watershed_meta  # Add table reference

        
        
        # Populate templates (after tables exist)
        #self.populate_templates()


    @staticmethod
    def get_db_path(custom_path=None):
        """Get database path. Tries package data, falls back to user directory."""
        if custom_path:
            return custom_path
        
        # Try package data directory first
        try:
            db_dir = resources.files('HexMagic').joinpath('data/db')
            db_path = Path(db_dir) / 'hexmagic.db'
            # Test if writable
            db_path.parent.mkdir(parents=True, exist_ok=True)
            db_path.touch(exist_ok=True)
            return str(db_path)
        except (PermissionError, OSError):
            # Fallback to user directory
            data_dir = Path.home() / '.hexmagic' / 'data'
            data_dir.mkdir(parents=True, exist_ok=True)
            return str(data_dir / 'hexmagic.db')

    def __enter__(self):
        return self

    def __exit__(self, *args):
        self.db.close()

    
    @staticmethod
    def _get(obj, key):
        """Get attribute from dict or object."""
        return obj[key] if isinstance(obj, dict) else getattr(obj, key)

# %% ../nbs/11_Database.ipynb #b823b32e
#this might be something we don't export
@patch
def reset_database(self:GeoStorage):
    """Delete and recreate database. USE WITH CAUTION!"""
    db_path = Path(self.path)  # Convert string to Path
    
    if db_path.exists():
        db_path.unlink()

    self.createDB()



# %% ../nbs/11_Database.ipynb #40dbcf6f
@patch
def _latest_hex_subquery(self: GeoStorage, world_id: int, as_of: int = None) -> str:
    """SQL subquery for latest hex state, optionally at a point in time."""
    time_clause = f"AND modified <= {as_of}" if as_of else ""
    return f"""
        SELECT world_id, q, r, s, MAX(modified) as max_mod
        FROM hex_data
        WHERE world_id = {world_id} {time_clause}
        GROUP BY world_id, q, r, s
    """




# %% ../nbs/11_Database.ipynb #533d8b0b
@patch
def query_hexes_latest(self: GeoStorage, world_id: int, as_of: int = None) -> list:
    """Get most recent version of each hex, optionally at a specific time."""
    subq = self._latest_hex_subquery(world_id, as_of)
    
    cursor = self.db.execute(f"""
        SELECT h.* FROM hex_data h
        INNER JOIN ({subq}) latest 
            ON h.world_id = latest.world_id 
            AND h.q = latest.q AND h.r = latest.r AND h.s = latest.s
            AND h.modified = latest.max_mod
    """)
    
    # Get column names from cursor description
    cols = [d[0] for d in cursor.description]
    rows = [dict(zip(cols, row)) for row in cursor.fetchall()]
    
    return rows


# %% ../nbs/11_Database.ipynb #f8452c1b
@patch
def update_hex(self: GeoStorage, world_id: int, q: int, r: int, s: int,
               elevation: float = None, latitude: float = None, longitude: float = None,
               distance_from_coast: float = None, grid_index: int = None) -> SaveResult:
    """Append a new state for a hex (temporal update)."""
    now = int(datetime.now().timestamp())
    
    record = {
        'world_id': world_id,
        'q': q, 'r': r, 's': s,
        'modified': now
    }
    
    # Get previous state to preserve unchanged fields
    prev = self.query_hexes_in_radius(world_id, q, r, s, radius=0)
    if prev:
        prev = prev[0]
        record['grid_index'] = grid_index if grid_index is not None else GeoStorage._get(prev, 'grid_index')
        record['elevation'] = elevation if elevation is not None else GeoStorage._get(prev, 'elevation')
        record['latitude'] = latitude if latitude is not None else GeoStorage._get(prev, 'latitude')
        record['longitude'] = longitude if longitude is not None else GeoStorage._get(prev, 'longitude')
        record['distance_from_coast'] = distance_from_coast if distance_from_coast is not None else GeoStorage._get(prev, 'distance_from_coast')
    else:
        record['grid_index'] = grid_index or 0
        record['elevation'] = elevation or 0.0
        record['latitude'] = latitude
        record['longitude'] = longitude
        record['distance_from_coast'] = distance_from_coast
    
    try:
        self.hexes.insert(record)
        return SaveResult(None, 'updated', f'hex ({q},{r},{s}) at {now}')
    except Exception as e:
        return SaveResult(None, 'error', str(e))


# %% ../nbs/11_Database.ipynb #e0d9759d
@patch
def query_hexes_in_radius(self: GeoStorage, world_id: int,
                          center_q: int, center_r: int, center_s: int,
                          radius: int, as_of: int = None) -> list:
    """Query latest hexes within radius of a center position."""
    subq = self._latest_hex_subquery(world_id, as_of)
    
    rows = list(self.db.execute(f"""
        SELECT h.* FROM hex_data h
        INNER JOIN ({subq}) latest 
            ON h.world_id = latest.world_id 
            AND h.q = latest.q AND h.r = latest.r AND h.s = latest.s
            AND h.modified = latest.max_mod
        WHERE h.q BETWEEN ? AND ? AND h.r BETWEEN ? AND ?
    """, [
        center_q - radius, center_q + radius,
        center_r - radius, center_r + radius
    ]).fetchall())
    
    if not rows:
        return []
    
    # Hardcode column order to avoid cursor.description issue
    cols = ['id', 'world_id', 'q', 'r', 's', 'grid_index', 'elevation', 
            'latitude', 'longitude', 'distance_from_coast', 'watershed_id', 'modified']
    
    rows = [dict(zip(cols, row)) for row in rows]
    
    # Filter to actual hex distance
    return [row for row in rows
            if max(abs(row['q'] - center_q), abs(row['r'] - center_r), abs(row['s'] - center_s)) <= radius]


# %% ../nbs/11_Database.ipynb #56693d18
@patch
def save_world(self: GeoStorage, terrain: Terrain, name: str = "") -> SaveResult:
    """Save terrain to database. Returns SaveResult(world_id, status, context)."""
    now = int(datetime.now().timestamp())
    
    grid = terrain.hexGrid
    
    # Build extras dict for non-field data
    extras = {}
    if terrain.geo:
        extras['geo'] = terrain.geo.encode() if hasattr(terrain.geo, 'encode') else str(terrain.geo)
    if terrain.climate:
        extras['climate'] = terrain.climate.encode() if hasattr(terrain.climate, 'encode') else str(terrain.climate)
    
    try:
        with self.db.conn:  # Transaction
            # Insert world metadata
            world_result = self.worlds.insert({
                'name': name or f"World_{now}",
                'hex_radius': grid.radius,
                'nrows': grid.nRows,
                'ncols': grid.nCols,
                'sea_level': terrain.seaLevel if isinstance(terrain.seaLevel, (int, float)) else 0.0,
                'elevation_delta': terrain.elevationDelta,
                'extras': json.dumps(extras),
                'created': now,
                'modified': now
            })
            
            world_id = world_result['id'] if isinstance(world_result, dict) else world_result
            
            # Insert hex data
            hex_records = []
            for idx, hex_obj in enumerate(grid.hexes):
                pos = grid.index_to_hexposition(idx)
                
                # Get lat/lon if geo bounds available
                lat, lon = None, None
                if terrain.geo and hasattr(terrain.geo, 'pixel_to_latlon'):
                    center = hex_obj.center
                    # Calculate grid pixel dimensions
                    width = grid.nCols * grid.radius * 1.5 + grid.radius
                    height = grid.nRows * grid.radius * math.sqrt(3) + grid.radius
                    lat, lon = terrain.geo.pixel_to_latlon(center.x, center.y, width, height)

                
                dist_coast = None
                if 'distance_to_ocean' in terrain.fields:
                    dist_coast = float(terrain.fields['distance_to_ocean'][idx])
                
                hex_records.append({
                    'world_id': world_id,
                    'q': pos.q,
                    'r': pos.r,
                    's': pos.s,
                    'grid_index': idx,
                    'elevation': float(terrain.elevations[idx]),
                    'latitude': lat,
                    'longitude': lon,
                    'distance_from_coast': dist_coast,
                    'modified': now
                })
            
            # Batch insert
            for record in hex_records:
                self.hexes.insert(record)
            
            return SaveResult(world_id, 'saved', f'{len(hex_records)} hexes')
    
    except Exception as e:
        return SaveResult(None, 'error', str(e))


# %% ../nbs/11_Database.ipynb #7c809ec1
@patch
def load_world(self: GeoStorage, world_id: int, as_of: int = None) -> LoadResult:
    """Load terrain from database. 
    
    Args:
        world_id: World to load
        as_of: Optional Unix timestamp - load state at this point in time
    
    Returns LoadResult(terrain, status, context).
    """
    try:
        world = self.worlds[world_id]
        if not world:
            return LoadResult(None, 'not_found', f'World {world_id} not found')
        
        radius = GeoStorage._get(world, 'hex_radius')
        nrows = GeoStorage._get(world, 'nrows')
        ncols = GeoStorage._get(world, 'ncols')
        
        width = ncols * radius * 1.5 + radius
        height = nrows * radius * math.sqrt(3) + radius
        bounds = MapRect(MapCord(0, 0), MapSize(width, height))
        
        terrain = Terrain(bounds, radius=radius)
        terrain.hexGrid.nRows = nrows
        terrain.hexGrid.nCols = ncols
        terrain.hexGrid.adjustRadius(radius)
        terrain.elevations = np.zeros(len(terrain.hexGrid.hexes))
        terrain.elevationDelta = GeoStorage._get(world, 'elevation_delta')
        
        # Use temporal query
        hex_rows = self.query_hexes_latest(world_id, as_of=as_of)
        
        for row in hex_rows:
            idx = GeoStorage._get(row, 'grid_index')
            terrain.elevations[idx] = GeoStorage._get(row, 'elevation')
            
            dist = GeoStorage._get(row, 'distance_from_coast')
            if dist is not None:
                if 'distance_to_ocean' not in terrain.fields:
                    terrain.fields['distance_to_ocean'] = np.zeros(len(terrain.elevations))
                terrain.fields['distance_to_ocean'][idx] = dist
        
        extras_str = GeoStorage._get(world, 'extras')
        if extras_str:
            extras = json.loads(extras_str)
        
        time_info = f" as of {as_of}" if as_of else ""
        return LoadResult(terrain, 'loaded', f'{len(hex_rows)} hexes{time_info}')
    
    except Exception as e:
        return LoadResult(None, 'error', str(e))


# %% ../nbs/11_Database.ipynb #51b9aa59
@patch
def extract_region(self: GeoStorage, world_id: int,
                   center_q: int, center_r: int, center_s: int,
                   rings: int, padding: int = 1, as_of: int = None) -> LoadResult:
    """Extract a centered region as a new Terrain.
    
    Returns LoadResult(terrain, status, context)
    """
    world = self.worlds[world_id]
    if not world:
        return LoadResult(None, 'not_found', f'World {world_id} not found')
    
    radius = GeoStorage._get(world, 'hex_radius')
    
    # Query hexes in region
    hex_rows = self.query_hexes_in_radius(world_id, center_q, center_r, center_s, rings, as_of=as_of)
    if not hex_rows:
        return LoadResult(None, 'empty', 'No hexes found in region')
    
    # Create centered grid
    total_rings = rings + padding
    grid = HexGrid.centered(radius=radius, rings=total_rings, style=StyleCSS("simple"))
    
    # Build terrain
    terrain = Terrain.__new__(Terrain)
    terrain.hexGrid = grid
    terrain.elevations = np.zeros(len(grid.hexes))
    terrain.fields = {}
    terrain.elevationDelta = GeoStorage._get(world, 'elevation_delta')
    terrain.seaLevel = GeoStorage._get(world, 'sea_level')
    terrain.climate = None
    terrain.path = ""
    terrain.colorLevels = None
    
    # Compute GeoBounds from extracted hexes
    lats = [GeoStorage._get(r, 'latitude') for r in hex_rows if GeoStorage._get(r, 'latitude') is not None]
    lons = [GeoStorage._get(r, 'longitude') for r in hex_rows if GeoStorage._get(r, 'longitude') is not None]
    
    if lats and lons:
        terrain.geo = GeoBounds(
            lat_min=min(lats), lat_max=max(lats),
            lon_min=min(lons), lon_max=max(lons)
        )

    else:
        terrain.geo = None
    
    # Map DB rows to centered grid
    filled = 0
    
    for row in hex_rows:
        # Position relative to query center
        q = GeoStorage._get(row, 'q') - center_q
        r = GeoStorage._get(row, 'r') - center_r
        s = GeoStorage._get(row, 's') - center_s
        rel_pos = HexPosition(q, r, s)
        
        # Map to centered grid
        new_idx = grid.hexposition_to_index(rel_pos, origin_index=grid.middle)
        if 0 <= new_idx < len(grid.hexes):
            terrain.elevations[new_idx] = GeoStorage._get(row, 'elevation')
            
            dist = GeoStorage._get(row, 'distance_from_coast')
            if dist is not None:
                if 'distance_to_ocean' not in terrain.fields:
                    terrain.fields['distance_to_ocean'] = np.zeros(len(grid.hexes))
                terrain.fields['distance_to_ocean'][new_idx] = dist
            
            filled += 1
    
    return LoadResult(terrain, 'extracted', f'{filled}/{len(hex_rows)} hexes mapped')


# %% ../nbs/11_Database.ipynb #8685abb3
def create_region_coord_mapper(center_q: int, center_r: int, center_s: int, 
                                extracted_grid: HexGrid) -> callable:
    """Create mapper from extracted region index to original world (q,r,s).
    
    Args:
        center_q, center_r, center_s: The center point used for extraction
        extracted_grid: The centered grid from extract_region
    
    Returns:
        Function: new_idx -> (q, r, s) tuple in original world coords
    """
    def mapper(new_idx: int) -> tuple[int, int, int]:
        # Get position relative to extracted grid's center
        rel_pos = extracted_grid.index_to_hexposition(new_idx, origin_index=extracted_grid.middle)
        # Add back the world center offset
        return (center_q + rel_pos.q, center_r + rel_pos.r, center_s + rel_pos.s)
    
    return mapper


# %% ../nbs/11_Database.ipynb #51e2e1c2
@patch
def create_region_index_mapper(self: GeoStorage, world_id: int,
                                center_q: int, center_r: int, center_s: int,
                                extracted_grid: HexGrid) -> callable:
    """Create mapper from extracted region index to original world grid_index.
    
    Args:
        world_id: The source world
        center_q, center_r, center_s: The center point used for extraction
        extracted_grid: The centered grid from extract_region
    
    Returns:
        Function: new_idx -> original_grid_index (or -1 if not in world)
    """
    # Build lookup dict from DB (q,r,s) -> grid_index
    hex_rows = list(self.hexes.rows_where('world_id = ?', [world_id]))
    coord_to_idx = {
        (GeoStorage._get(r, 'q'), GeoStorage._get(r, 'r'), GeoStorage._get(r, 's')): 
        GeoStorage._get(r, 'grid_index')
        for r in hex_rows
    }
    
    def mapper(new_idx: int) -> int:
        rel_pos = extracted_grid.index_to_hexposition(new_idx, origin_index=extracted_grid.middle)
        world_coords = (center_q + rel_pos.q, center_r + rel_pos.r, center_s + rel_pos.s)
        return coord_to_idx.get(world_coords, -1)
    
    return mapper


# %% ../nbs/11_Database.ipynb #eac8b5d2
@patch
def save_weather(self: GeoStorage, terrain: Terrain, world_id: int, 
                 season: str = "annual") -> SaveResult:
    """Save weather data for a terrain to database.
    
    Args:
        terrain: Terrain with weather fields computed
        world_id: World ID to associate weather with
        season: Season identifier (e.g., "annual", "summer", "winter")
    
    Returns:
        SaveResult(count, status, context)
    """
    now = int(datetime.now().timestamp())
    grid = terrain.hexGrid
    
    # Check for required weather fields
    if 'temperature' not in terrain.fields or 'precipitation' not in terrain.fields:
        return SaveResult(None, 'error', 'Missing temperature or precipitation fields')
    
    try:
        with self.db.conn:
            records = []
            for idx in range(len(terrain.elevations)):
                pos = grid.index_to_hexposition(idx)
                
                record = {
                    'world_id': world_id,
                    'q': pos.q,
                    'r': pos.r,
                    's': pos.s,
                    'temperature': float(terrain.fields['temperature'][idx]),
                    'precipitation': float(terrain.fields['precipitation'][idx]),
                    'humidity': float(terrain.fields['humidity'][idx]) if 'humidity' in terrain.fields else None,
                    'climate_pet': float(terrain.fields['climate_pet'][idx]) if 'climate_pet' in terrain.fields else None,
                    'aridity_index': float(terrain.fields['aridity_index'][idx]) if 'aridity_index' in terrain.fields else None,
                    'temp_seasonality': float(terrain.fields['temp_seasonality'][idx]) if 'temp_seasonality' in terrain.fields else None,
                    'precip_seasonality': float(terrain.fields['precip_seasonality'][idx]) if 'precip_seasonality' in terrain.fields else None,
                    'distance_from_coast': float(terrain.fields['distance_to_coast'][idx]) if 'distance_to_coast' in terrain.fields else None,
                    'season': season,
                    'modified': now
                }
                records.append(record)
            
            for record in records:
                self.weather.insert(record)
            
            return SaveResult(len(records), 'saved', f'{len(records)} weather records for season={season}')
    
    except Exception as e:
        return SaveResult(None, 'error', str(e))




# %% ../nbs/11_Database.ipynb #a5616d71
@patch
def load_weather(self: GeoStorage, world_id: int, terrain: Terrain,
                 season: str = "annual", as_of: int = None) -> LoadResult:
    """Load weather data into a terrain's fields.
    
    Args:
        world_id: World ID to load weather for
        terrain: Terrain to populate with weather fields
        season: Season to load
        as_of: Optional timestamp for temporal query
    
    Returns:
        LoadResult(terrain, status, context)
    """
    try:
        # Build temporal subquery
        time_clause = f"AND modified <= {as_of}" if as_of else ""
        
        cursor = self.db.execute(f"""
            SELECT hw.* FROM hex_weather hw
            INNER JOIN (
                SELECT world_id, q, r, s, MAX(modified) as max_mod
                FROM hex_weather
                WHERE world_id = ? AND season = ? {time_clause}
                GROUP BY world_id, q, r, s
            ) latest 
                ON hw.world_id = latest.world_id 
                AND hw.q = latest.q AND hw.r = latest.r AND hw.s = latest.s
                AND hw.modified = latest.max_mod
            WHERE hw.season = ?
        """, [world_id, season, season])
        
        cols = [d[0] for d in cursor.description]
        rows = [dict(zip(cols, row)) for row in cursor.fetchall()]
        
        if not rows:
            return LoadResult(terrain, 'empty', f'No weather data for world={world_id}, season={season}')
        
        # Initialize field arrays
        n_hexes = len(terrain.elevations)
        terrain.fields['temperature'] = np.zeros(n_hexes)
        terrain.fields['precipitation'] = np.zeros(n_hexes)
        terrain.fields['humidity'] = np.zeros(n_hexes)
        terrain.fields['climate_pet'] = np.zeros(n_hexes)
        terrain.fields['aridity_index'] = np.zeros(n_hexes)
        terrain.fields['temp_seasonality'] = np.zeros(n_hexes)
        terrain.fields['precip_seasonality'] = np.zeros(n_hexes)
        terrain.fields['distance_to_coast'] = np.zeros(n_hexes)
        
        # Map weather data to terrain indices
        grid = terrain.hexGrid
        filled = 0
        
        for row in rows:
            pos = HexPosition(row['q'], row['r'], row['s'])
            idx = grid.hexposition_to_index(pos)
            
            if 0 <= idx < n_hexes:
                terrain.fields['temperature'][idx] = row['temperature'] or 0.0
                terrain.fields['precipitation'][idx] = row['precipitation'] or 0.0
                if row['humidity'] is not None:
                    terrain.fields['humidity'][idx] = row['humidity']
                if row['climate_pet'] is not None:
                    terrain.fields['climate_pet'][idx] = row['climate_pet']
                if row['aridity_index'] is not None:
                    terrain.fields['aridity_index'][idx] = row['aridity_index']
                if row['temp_seasonality'] is not None:
                    terrain.fields['temp_seasonality'][idx] = row['temp_seasonality']
                if row['precip_seasonality'] is not None:
                    terrain.fields['precip_seasonality'][idx] = row['precip_seasonality']
                if row['distance_from_coast'] is not None:
                    terrain.fields['distance_to_coast'][idx] = row['distance_from_coast']
                filled += 1
        
        time_info = f" as of {as_of}" if as_of else ""
        return LoadResult(terrain, 'loaded', f'{filled} weather records for season={season}{time_info}')
    
    except Exception as e:
        return LoadResult(None, 'error', str(e))

# %% ../nbs/11_Database.ipynb #ec2c7516
@patch
def save_watersheds(self: GeoStorage, terrain: Terrain, 
                    watersheds: list, world_id: int) -> SaveResult:
    """Save watersheds and assign watershed_id to hexes.
    
    Args:
        terrain: Terrain with computed watersheds
        watersheds: List of Watershed objects
        world_id: World to associate with
    
    Returns:
        SaveResult(count, status, context)
    """
    now = int(datetime.now().timestamp())
    grid = terrain.hexGrid
    
    try:
        with self.db.conn:
            
            
            # Build hex -> watershed mapping
            hex_to_watershed = {}
            
            for i, watershed in enumerate(watersheds):
                # Get terminal position
                terminal_idx = watershed.terminal_hex
                if terminal_idx is not None:
                    terminal_pos = grid.index_to_hexposition(terminal_idx)
                else:
                    terminal_pos = HexPosition(0, 0, 0)
                
                # Calculate stats
                flows = watershed.calculate_flow()
                max_flow = max(flows.values()) if flows else 0
                
                # Save watershed metadata
                ws_record = {
                    'world_id': world_id,
                    'name': f"watershed_{i}",
                    'terminal_q': terminal_pos.q,
                    'terminal_r': terminal_pos.r,
                    'terminal_s': terminal_pos.s,
                    'is_ocean': watershed.is_ocean,
                    'total_flow': max_flow,
                    'area_hexes': len(watershed.region.hexes),
                    'river_tree': watershed.tributary.encode(),
                    'style': watershed.style.encode() if hasattr(watershed.style, 'encode') else str(watershed.style),
                    'created': now,
                    'modified': now
                }
                
                result = self.watersheds.insert(ws_record)
                ws_id = result['id'] if isinstance(result, dict) else result
                
                # Map hexes to this watershed
                for hex_idx in watershed.region.hexes:
                    hex_to_watershed[hex_idx] = ws_id
            
            # Update hex_data with watershed_id
            for hex_idx, ws_id in hex_to_watershed.items():
                pos = grid.index_to_hexposition(hex_idx)
                
                # Insert new record with watershed_id
                self.hexes.insert({
                    'world_id': world_id,
                    'q': pos.q,
                    'r': pos.r,
                    's': pos.s,
                    'grid_index': hex_idx,
                    'elevation': float(terrain.elevations[hex_idx]),
                    'watershed_id': ws_id,
                    'modified': now
                })
            
            return SaveResult(len(watersheds), 'saved', 
                            f'{len(watersheds)} watersheds, {len(hex_to_watershed)} hexes assigned')
    
    except Exception as e:
        return SaveResult(None, 'error', str(e))





@patch
def query_watershed_hexes(self: GeoStorage, world_id: int, 
                          watershed_id: int) -> list:
    """Get all hexes belonging to a specific watershed."""
    cursor = self.db.execute("""
        SELECT h.* FROM hex_data h
        INNER JOIN (
            SELECT world_id, q, r, s, MAX(modified) as max_mod
            FROM hex_data
            WHERE world_id = ? AND watershed_id = ?
            GROUP BY world_id, q, r, s
        ) latest 
            ON h.world_id = latest.world_id 
            AND h.q = latest.q AND h.r = latest.r AND h.s = latest.s
            AND h.modified = latest.max_mod
        WHERE h.watershed_id = ?
    """, [world_id, watershed_id, watershed_id])
    
    cols = [d[0] for d in cursor.description]
    return [dict(zip(cols, row)) for row in cursor.fetchall()]


# %% ../nbs/11_Database.ipynb #be577ec8
@patch
def load_watersheds(self: GeoStorage, world_id: int, 
                    terrain: Terrain) -> LoadResult:
    """Load watersheds for a world.
    
    Args:
        world_id: World to load from
        terrain: Terrain to attach watersheds to
    
    Returns:
        LoadResult(watersheds_list, status, context)
    """
    try:
        # Query watershed metadata
        ws_rows = list(self.watersheds.rows_where(
    'world_id = ?', [world_id]
))
        
        
        if not ws_rows:
            return LoadResult([], 'empty', f'No watersheds for world {world_id}')
        
        # Query hex -> watershed mapping
        hex_rows = self.query_hexes_latest(world_id)
        
        # Group hexes by watershed_id
        ws_hexes = {}  # watershed_id -> set of hex indices
        for row in hex_rows:
            ws_id = row.get('watershed_id')
            if ws_id is not None:
                if ws_id not in ws_hexes:
                    ws_hexes[ws_id] = set()
                ws_hexes[ws_id].add(row['grid_index'])
        
        # Reconstruct Watershed objects
        watersheds = []
        for ws_row in ws_rows:
            ws_id = ws_row['id']
            
            
            # Get hexes for this watershed
            hexes = ws_hexes.get(ws_id, set())
            region = HexRegion(hexes=hexes, hexGrid=terrain.hexGrid)
            
            # Decode river
            river_str = ws_row['river_tree']
            river = River.decode(river_str, terrain) if river_str else River(terrain)
            
            # Decode style
            style_str = ws_row['style']
            if style_str:
                style = StyleCSS.decode(style_str)
            else:
                style = StyleCSS(f"ws_{ws_id}", fill="#cccccc")
            
            watershed = Watershed(
                region=region,
                tributary=river,
                style=style
            )
            watersheds.append(watershed)
        
        return LoadResult(watersheds, 'loaded', f'{len(watersheds)} watersheds')
    
    except Exception as e:
        return LoadResult(None, 'error', str(e))

# %% ../nbs/11_Database.ipynb #1c4f6677
class GeoStorageDebugger:
    """Test harness for HexServer with automatic cleanup."""
    
    def __init__(self, keep_on_error=False):
        """
        Args:
            keep_on_error: If True, preserve database when tests fail
        """
        self.temp_dir = tempfile.mkdtemp(prefix='hexmagic_test_')
        self.db_path = os.path.join(self.temp_dir, 'test.db')
        self.server = GeoStorage(custom_path=self.db_path)
        self.keep_on_error = keep_on_error
        self.failed = False
        
    def preserve_db(self, test_name):
        """Copy database to inspection directory."""
        inspect_dir = Path.home() / '.hexmagic' / 'test_failures'
        inspect_dir.mkdir(parents=True, exist_ok=True)
        
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        dest = inspect_dir / f"{test_name}_{timestamp}.db"
        
        shutil.copy2(self.db_path, dest)
        print(f"⚠ Database preserved at: {dest}")
        
    def close(self):
        """Clean up test database."""
        self.server.db.close()
        
        if not self.failed or not self.keep_on_error:
            shutil.rmtree(self.temp_dir)
            print("✓ Test database cleaned up")
        else:
            print(f"⚠ Test database kept at: {self.temp_dir}")
            
    def __enter__(self):
        return self
        
    def __exit__(self, exc_type, exc_val, exc_tb):
        if exc_type is not None:
            self.failed = True
        self.close()


# %% ../nbs/11_Database.ipynb #85702751
@patch
def test_save_load_terrain(self: GeoStorageDebugger):
    """Test saving and loading a terrain."""
    td = TerraDemo()
    terrain = td.aussie_map()
    
    # Save
    save_result = self.server.save_world(terrain, name="Australia Test")
    assert save_result.status == 'saved', f"Save failed: {save_result.status} - {save_result.context}"
    print(f"✓ Saved world {save_result.id}: {save_result.context}")
    
    # Load
    load_result = self.server.load_world(save_result.id)
    assert load_result.status == 'loaded', f"Load failed: {load_result.status} - {load_result.context}"
    print(f"✓ Loaded world: {load_result.context}")
    
    # Verify
    loaded = load_result.data
    assert len(loaded.elevations) == len(terrain.elevations), "Elevation count mismatch"
    assert np.allclose(loaded.elevations, terrain.elevations), "Elevation values don't match"
    print(f"✓ Elevations match ({len(loaded.elevations)} hexes)")


# %% ../nbs/11_Database.ipynb #fe88dd3b
@patch
def test_query_radius(self: GeoStorageDebugger):
    """Test querying hexes by position and radius."""
    td = TerraDemo()
    terrain = td.aussie_map()
    
    # Save
    save_result = self.server.save_world(terrain, name="Query Test")
    assert save_result.status == 'saved'
    
    # Query center region (q=0, r=0, s=0 with radius 5)
    hexes = self.server.query_hexes_in_radius(save_result.id, 0, 0, 0, radius=5)
    
    # Should get some hexes (exact count depends on map)
    print(f"✓ Found {len(hexes)} hexes within radius 5 of origin")
    assert len(hexes) > 0, "Expected some hexes near origin"


# %% ../nbs/11_Database.ipynb #c540e03c
@patch
def test_extract_region(self: GeoStorageDebugger):
    """Test extracting a centered region."""
    td = TerraDemo()
    terrain = td.aussie_map()
    
    # Save full terrain
    save_result = self.server.save_world(terrain, name="Extract Test")
    assert save_result.status == 'saved'
    
    # Extract a region around origin
    result = self.server.extract_region(save_result.id, 0, 0, 0, rings=10)
    assert result.status == 'extracted', f"Extract failed: {result.context}"
    
    extracted = result.data
    print(f"✓ Extracted region: {result.context}")
    print(f"  Grid size: {len(extracted.hexGrid.hexes)} hexes")
    
    # Verify it's centered
    assert extracted.hexGrid.middle is not None
    print(f"  Center index: {extracted.hexGrid.middle}")


# %% ../nbs/11_Database.ipynb #530905ee
@patch
def test_region_mappers(self: GeoStorageDebugger):
    """Test that region mappers correctly translate indices."""
    td = TerraDemo()
    terrain = td.aussie_map()
    
    save_result = self.server.save_world(terrain, name="Mapper Test")
    assert save_result.status == 'saved'
    
    center_q, center_r, center_s = 5, -3, -2
    result = self.server.extract_region(save_result.id, center_q, center_r, center_s, rings=5)
    assert result.status == 'extracted'
    
    extracted = result.data
    grid = extracted.hexGrid
    
    # Test coord mapper
    coord_mapper = create_region_coord_mapper(center_q, center_r, center_s, grid)
    
    # Center of extracted grid should map back to query center
    center_coords = coord_mapper(grid.middle)
    assert center_coords == (center_q, center_r, center_s), f"Center mismatch: {center_coords}"
    print(f"✓ Coord mapper: center maps to {center_coords}")
    
    # Test index mapper  
    idx_mapper = self.server.create_region_index_mapper(
        save_result.id, center_q, center_r, center_s, grid
    )
    
    # Verify some mappings
    valid_count = sum(1 for i in range(len(grid.hexes)) if idx_mapper(i) >= 0)
    print(f"✓ Index mapper: {valid_count}/{len(grid.hexes)} indices map to original")


# %% ../nbs/11_Database.ipynb #06948f27
@patch
def test_save_load_weather(self: GeoStorageDebugger):
    """Test saving and loading weather data."""
    # Use sfTerr which already has weather fields computed
    with open('sf_coast_weather.txt') as f:
        terrain = Terrain.decode(f.read())
    
    # First save the world (need world_id for weather)
    save_world_result = self.server.save_world(terrain, name="SF Weather Test")
    assert save_world_result.status == 'saved', f"World save failed: {save_world_result.context}"
    world_id = save_world_result.id
    print(f"✓ Saved world {world_id}")
    
    # Save weather
    save_weather_result = self.server.save_weather(terrain, world_id, season="annual")
    assert save_weather_result.status == 'saved', f"Weather save failed: {save_weather_result.context}"
    print(f"✓ Saved weather: {save_weather_result.context}")
    
    # Load world (without weather)
    load_world_result = self.server.load_world(world_id)
    assert load_world_result.status == 'loaded'
    loaded_terrain = load_world_result.data
    
    # Verify no weather fields yet
    assert 'temperature' not in loaded_terrain.fields or loaded_terrain.fields['temperature'].sum() == 0
    print(f"✓ Loaded world without weather fields")
    
    # Load weather into terrain
    load_weather_result = self.server.load_weather(world_id, loaded_terrain, season="annual")
    assert load_weather_result.status == 'loaded', f"Weather load failed: {load_weather_result.context}"
    print(f"✓ Loaded weather: {load_weather_result.context}")
    
    # Verify weather data matches
    assert np.allclose(loaded_terrain.fields['temperature'], terrain.fields['temperature']), "Temperature mismatch"
    assert np.allclose(loaded_terrain.fields['precipitation'], terrain.fields['precipitation']), "Precipitation mismatch"
    print(f"✓ Weather data matches original")
    
    # Test seasonal storage - save summer data with modified temps
    terrain.fields['temperature'] = terrain.fields['temperature'] + 5  # Summer is warmer
    save_summer = self.server.save_weather(terrain, world_id, season="summer")
    assert save_summer.status == 'saved'
    print(f"✓ Saved summer weather")
    
    # Load summer and verify it's different from annual
    load_summer = self.server.load_weather(world_id, loaded_terrain, season="summer")
    assert load_summer.status == 'loaded'
    assert loaded_terrain.fields['temperature'].mean() > terrain.fields['temperature'].mean() - 5 + 4  # Should be ~5°C warmer
    print(f"✓ Summer temperatures correctly loaded (warmer than annual)")


# %% ../nbs/11_Database.ipynb #a502739e
@patch
def test_chunked_terrain_generator(self: GeoStorageDebugger):
    """Test chunked terrain generation pipeline."""
    generator = ChunkedTerrainGenerator(
        storage=self.server,
        coarse_radius=50,      # Large hexes for overview
        fine_radius=10,        # Detailed hexes for chunks
        chunk_rings=8,         # Small chunks for testing
        halo_rings=2
    )
    
    # Phase 1: Generate coarse map
    bounds = MapRect(MapCord(0, 0), MapSize(800, 600))
    coarse = generator.generate_coarse(
        bounds,
        num_plates=5,
        ocean_fraction=0.3,
        name="chunked_test_coarse"
    )
    
    assert generator.coarse_world_id is not None, "Coarse world not saved"
    assert len(coarse.elevations) > 0, "Coarse terrain has no hexes"
    print(f"✓ Generated coarse map: {len(coarse.hexGrid.hexes)} hexes, world_id={generator.coarse_world_id}")
    
    # Phase 2: Generate a single chunk at origin
    origin_chunk = ChunkRef(HexPosition(0, 0, 0), generator.chunk_rings)
    chunk_terrain = generator.generate_chunk(origin_chunk, coarse)
    
    assert len(chunk_terrain.elevations) > 0, "Chunk terrain empty"
    assert generator.scale == 5.0, f"Expected scale 5.0, got {generator.scale}"
    print(f"✓ Generated chunk at origin: {len(chunk_terrain.hexGrid.hexes)} hexes")
    
    # Phase 3: Save chunk
    chunk_id = generator.save_chunk(chunk_terrain, origin_chunk)
    assert chunk_id is not None, "Chunk not saved"
    assert origin_chunk.key in generator.chunk_world_ids
    print(f"✓ Saved chunk: world_id={chunk_id}")
    
    # Phase 4: Load chunk back
    loaded_chunk = generator.load_chunk(origin_chunk)
    assert loaded_chunk is not None, "Failed to load chunk"
    assert len(loaded_chunk.elevations) > 0
    print(f"✓ Loaded chunk: {len(loaded_chunk.hexGrid.hexes)} hexes")
    
    # Test coordinate mapping
    world_pos = HexPosition(10, -5, -5)
    chunk_ref = generator.world_to_chunk_ref(world_pos)
    print(f"✓ World pos {world_pos} maps to chunk {chunk_ref.position}")
    
    # Test chunk iteration
    chunks = list(generator.chunk_refs(max_ring=1))
    assert len(chunks) == 7, f"Expected 7 chunks (1 center + 6 ring), got {len(chunks)}"
    print(f"✓ Chunk iteration: {len(chunks)} chunks in ring 0-1")


# %% ../nbs/11_Database.ipynb #cdb17c4b
@patch
def test_save_load_watersheds(self: GeoStorageDebugger):
    """Test watershed save/load."""
    # Load SF terrain with weather
    with open('sf_coast_weather.txt') as f:
        terrain = Terrain.decode(f.read())
        terrain.climate = TerrainPatterns(terrain).weatherPatterns()["mediterranean"]
    
    # Compute watersheds
    basins = DrainageBasins(terrain)
    
    # Save world first
    save_world = self.server.save_world(terrain, name="Watershed Test")
    assert save_world.status == 'saved'
    world_id = save_world.id
    print(f"✓ Saved world {world_id}")
    
    # Save watersheds
    save_ws = self.server.save_watersheds(terrain, basins.sheds, world_id)
    assert save_ws.status == 'saved', f"Failed: {save_ws.context}"
    print(f"✓ Saved watersheds: {save_ws.context}")
    
    # Load world (fresh terrain)
    load_world = self.server.load_world(world_id)
    loaded_terrain = load_world.data
    
    # Load watersheds
    load_ws = self.server.load_watersheds(world_id, loaded_terrain)
    assert load_ws.status == 'loaded', f"Failed: {load_ws.context}"
    print(f"✓ Loaded watersheds: {load_ws.context}")
    
    # Verify counts match
    assert len(load_ws.data) == len(basins.sheds), "Watershed count mismatch"
    print(f"✓ Watershed count matches: {len(load_ws.data)}")
    
    # Test query by watershed
    if load_ws.data:
        first_ws = load_ws.data[0]
        # Get the watershed_id from the DB
        ws_rows = list(self.server.db.t.watershed_meta.rows_where(
            'world_id = ?', [world_id]
        ))
        if ws_rows:
            hexes = self.server.query_watershed_hexes(world_id, ws_rows[0]['id'])
            print(f"✓ Query watershed hexes: {len(hexes)} hexes in watershed 0")


# %% ../nbs/11_Database.ipynb #7d99067c
from .core import *
from .primitives import HexPosition

# %% ../nbs/11_Database.ipynb #6d9448bc
import heapq
from typing import Optional

def hex_distance(a: HexPosition, b: HexPosition) -> int:
    """Manhattan distance in hex coordinates."""
    return (abs(a.q - b.q) + abs(a.r - b.r) + abs(a.s - b.s)) // 2


def astar_terrain(terrain: Terrain, start_idx: int, goal_idx: int, 
                  uphill_penalty: float = 4.0) -> tuple[list[int], float]:
    """A* pathfinding on a Terrain. Returns (path_indices, total_cost)."""
    grid = terrain.hexGrid
    elevations = terrain.elevations
    
    start_pos = grid.index_to_hexposition(start_idx)
    goal_pos = grid.index_to_hexposition(goal_idx)
    
    # Priority queue: (f_score, counter, index)
    counter = 0
    frontier = [(0, counter, start_idx)]
    
    came_from = {start_idx: None}
    g_score = {start_idx: 0.0}
    
    while frontier:
        _, _, current = heapq.heappop(frontier)
        
        if current == goal_idx:
            # Reconstruct path
            path = []
            while current is not None:
                path.append(current)
                current = came_from[current]
            return path[::-1], g_score[goal_idx]
        
        current_pos = grid.index_to_hexposition(current)
        current_elev = elevations[current]
        
        # Check all 6 neighbors
        for neighbor_pos in current_pos.neighbors():
            neighbor_idx = grid.hexposition_to_index(neighbor_pos)
            
            # Skip if out of bounds
            if neighbor_idx < 0 or neighbor_idx >= len(elevations):
                continue
            
            neighbor_elev = elevations[neighbor_idx]
            
            # Skip water (below sea level)
            if neighbor_elev < terrain.seaLevel:
                continue
            
            cost = hex_move_cost(current_elev, neighbor_elev, uphill_penalty)
            tentative_g = g_score[current] + cost
            
            if neighbor_idx not in g_score or tentative_g < g_score[neighbor_idx]:
                g_score[neighbor_idx] = tentative_g
                f = tentative_g + hex_distance(neighbor_pos, goal_pos)
                counter += 1
                heapq.heappush(frontier, (f, counter, neighbor_idx))
                came_from[neighbor_idx] = current
    
    return [], float('inf')  # No path found


def visualize_path(terrain: Terrain, path: list[int], 
                   start_idx: int, goal_idx: int) -> str:
    """Add path visualization to terrain and return SVG."""
    grid = terrain.hexGrid
    
    # Color the path
    for idx in path:
        hex_obj = grid.hexes[idx]
        if idx == start_idx:
            hex_obj.fill = "#00ff00"  # Green start
        elif idx == goal_idx:
            hex_obj.fill = "#ff0000"  # Red goal
        else:
            hex_obj.fill = "#ffff00"  # Yellow path
    
    terrain.hexGrid.update()
    return terrain.builder


# %% ../nbs/11_Database.ipynb #78c4e10f
def astar_terrain(terrain: Terrain, start_idx: int, goal_idx: int, 
                  uphill_penalty: float = 4.0) -> tuple[list[int], float]:
    """A* pathfinding on a Terrain. Returns (path_indices, total_cost)."""
    grid = terrain.hexGrid
    elevations = terrain.elevations
    
    start_pos = grid.index_to_hexposition(start_idx)
    goal_pos = grid.index_to_hexposition(goal_idx)
    
    # Priority queue: (f_score, counter, index)
    counter = 0
    frontier = [(0, counter, start_idx)]
    
    came_from = {start_idx: None}
    g_score = {start_idx: 0.0}
    
    while frontier:
        _, _, current = heapq.heappop(frontier)
        
        if current == goal_idx:
            # Reconstruct path
            path = []
            while current is not None:
                path.append(current)
                current = came_from[current]
            return path[::-1], g_score[goal_idx]
        
        current_elev = elevations[current]
        
        # Use terrain.ring to get neighbor indices
        for neighbor_idx in terrain.ring(current, 1):
            # Skip if out of bounds
            if neighbor_idx < 0 or neighbor_idx >= len(elevations):
                continue
            
            # Skip water (elevationLevel returns -1 for ocean)
            if terrain.elevationLevel(neighbor_idx) < 0:
                cost = 100  # Boats!
            else:
                neighbor_elev = elevations[neighbor_idx]
                cost = hex_move_cost(current_elev, neighbor_elev, uphill_penalty)

            
            #neighbor_elev = elevations[neighbor_idx]
            #cost = hex_move_cost(current_elev, neighbor_elev, uphill_penalty)
            tentative_g = g_score[current] + cost
            
            if neighbor_idx not in g_score or tentative_g < g_score[neighbor_idx]:
                g_score[neighbor_idx] = tentative_g
                neighbor_pos = grid.index_to_hexposition(neighbor_idx)
                f = tentative_g + hex_distance(neighbor_pos, goal_pos)
                counter += 1
                heapq.heappush(frontier, (f, counter, neighbor_idx))
                came_from[neighbor_idx] = current
    
    return [], float('inf')  # No path found


# %% ../nbs/11_Database.ipynb #1d50d380
def refine_coarse_path(generator: ChunkedTerrainGenerator, 
                       coarse: Terrain,
                       coarse_path: list[int],
                       uphill_penalty: float = 4.0) -> tuple[list[HexPosition], float]:
    """Refine a coarse path through fine chunks.
    
    Returns (world_positions, total_cost)
    """
    if len(coarse_path) < 2:
        return [], 0.0
    
    coarse_grid = coarse.hexGrid
    scale = generator.scale
    
    fine_path = []
    total_cost = 0.0
    
    for i in range(len(coarse_path) - 1):
        coarse_idx = coarse_path[i]
        next_coarse_idx = coarse_path[i + 1]
        
        # Get coarse positions
        coarse_pos = coarse_grid.index_to_hexposition(coarse_idx)
        next_coarse_pos = coarse_grid.index_to_hexposition(next_coarse_idx)
        
        # Map to fine world positions (centers of coarse hexes)
        fine_start = HexPosition(
            int(coarse_pos.q * scale),
            int(coarse_pos.r * scale),
            int(coarse_pos.s * scale)
        )
        fine_goal = HexPosition(
            int(next_coarse_pos.q * scale),
            int(next_coarse_pos.r * scale),
            int(next_coarse_pos.s * scale)
        )
        
        # Which chunk contains the start?
        chunk_ref = generator.world_to_chunk_ref(fine_start)
        chunk_terrain = generator.load_chunk(chunk_ref)
        
        if chunk_terrain is None:
            # Chunk not generated - fall back to coarse position
            fine_path.append(fine_start)
            total_cost += 1.0
            continue
        
        # Map world positions to local chunk indices
        chunk_center = chunk_ref.center_hex
        local_start = fine_start - chunk_center
        local_goal = fine_goal - chunk_center
        
        chunk_grid = chunk_terrain.hexGrid
        start_idx = chunk_grid.hexposition_to_index(local_start, origin_index=chunk_grid.middle)
        goal_idx = chunk_grid.hexposition_to_index(local_goal, origin_index=chunk_grid.middle)
        
        # Bounds check
        if start_idx < 0 or goal_idx < 0:
            fine_path.append(fine_start)
            total_cost += 1.0
            continue
        if start_idx >= len(chunk_terrain.elevations) or goal_idx >= len(chunk_terrain.elevations):
            fine_path.append(fine_start)
            total_cost += 1.0
            continue
        
        # Local A* within chunk
        local_path, local_cost = astar_terrain(chunk_terrain, start_idx, goal_idx, uphill_penalty)
        
        if local_path:
            # Convert local indices back to world positions
            for idx in local_path[:-1]:  # Skip last to avoid duplicates
                local_pos = chunk_grid.index_to_hexposition(idx, origin_index=chunk_grid.middle)
                world_pos = local_pos + chunk_center
                fine_path.append(world_pos)
            total_cost += local_cost
        else:
            # No local path - just add the coarse waypoint
            fine_path.append(fine_start)
            total_cost += hex_distance(fine_start, fine_goal)
    
    # Add final goal
    last_coarse_pos = coarse_grid.index_to_hexposition(coarse_path[-1])
    final_pos = HexPosition(
        int(last_coarse_pos.q * scale),
        int(last_coarse_pos.r * scale),
        int(last_coarse_pos.s * scale)
    )
    fine_path.append(final_pos)
    
    return fine_path, total_cost

