# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/14_overlay.ipynb.

# %% auto #0
__all__ = ['OverlaySpec', 'OverlayContext', 'TerrainDisplay', 'TerrainOverlay', 'ClimateOverlay', 'WatershedOverlay',
           'RiverOverlay', 'CreamOverlay', 'SoilOverlay', 'FlowOverlay', 'TemperatureOverlay', 'PrecipitationOverlay',
           'join_paths', 'offset_path', 'wave_svg_path', 'OceanWaveOverlay']

# %% ../nbs/14_overlay.ipynb #257590f1
#import nbdev; nbdev.nbdev_export()
import sys
import math
from fastcore.basics import patch

# %% ../nbs/14_overlay.ipynb #0318af9c
from .plot.primitives import  MapCord , PrimitiveDemo
from .plot.hex import Hex


from .styles import StyleCSS,  SVGBuilder, SVGLayer

# %% ../nbs/14_overlay.ipynb #0a18d26b
from .primitives import MapPath, MapSize, MapRect, MapCord 
from .primitives import HexGrid, HexPosition ,  HexRegion, GosperCurve, windy_edge , unique_windy_edge

import numpy as np

from .terrain import Terrain
from .voronoi import generate_plate_terrain


Terrain.fromSeeds = generate_plate_terrain
from .climate import ClimatePreset, Climate, TerraDemo
from .geology import Geology, DrainageBasins, SoilSystem


# %% ../nbs/14_overlay.ipynb #54b1322a
from .terrainpatterns import TerrainPatterns
from .climate import TerrainFactory

# %% ../nbs/14_overlay.ipynb #e1b67b46
from .terraform import Terraform
from .styles import apply_looping_animation, LoopingLayerAnimation
from .core import TerraDemo
from .primitives import HexTouchMap, HexRegion
from .water.soil import SoilSystem, SoilType


# %% ../nbs/14_overlay.ipynb #54ace1a2
from fastcore.utils import *
from fasthtml.common import *
from fasthtml.jupyter import *
#from fasthtml.jupyter import get_host
from fastlite import *
import fasthtml.components as fc
import httpx
import random
import pandas as pd
import threading
import numpy as np
from dataclasses import dataclass

# %% ../nbs/14_overlay.ipynb #3d59a436
import logging
from dataclasses import dataclass, field
from typing import Callable, Optional

@dataclass
class OverlaySpec:
    """Specification for a single overlay layer."""
    name: str
    renderer: Callable[['OverlayContext'], str]
    requires: set = field(default_factory=set)
    priority: int = 50
    stylized: bool = False       # Use organic region boundaries instead of flat hexes
    edge_fn: Callable = None     # Edge transform for stylized mode (default: unique_windy_edge)


# %% ../nbs/14_overlay.ipynb #a0990fd2
@dataclass
class OverlayContext:
    """Rendering context passed to overlay renderers."""
    terrain: 'Terrain'
    grid: 'HexGrid'
    builder: 'SVGBuilder'
    c2f: dict = None
    extras: dict = field(default_factory=dict)

    def __getattr__(self, name):
        extras = self.__dict__.get('extras', {})
        if name in extras: return extras[name]
        raise AttributeError(f"OverlayContext has no '{name}' — did you forget to pass it?")

    @property
    def available(self):
        keys = {'terrain', 'grid', 'builder'}
        if self.c2f is not None: keys.add('c2f')
        keys |= {k for k, v in self.extras.items() if v is not None}
        return keys

    @classmethod
    def from_terrain(cls, terrain, *, region=None, padding=1, radius=None, **extras):
        """Build context with zoom/radius handling."""
        coarse_basins = None
        basins = extras.get('basins')
        c2f = extras.pop('c2f', None)

        if region is not None:
            if basins is not None:
                coarse_basins = basins
                extras['basins'] = None
            terrain = terrain.zoom(region, padding=padding)
            if c2f is None:
                c2f = getattr(terrain, 'c2f', None)

        grid = terrain.hexGrid
        if radius: grid.adjustRadius(radius)

        # Auto-extract from result
        result = extras.get('result')
        if extras.get('basins') is None and result and hasattr(result, 'basins'):
            extras['basins'] = result.basins
        if extras.get('soil') is None and result and hasattr(result, 'soil'):
            extras['soil'] = result.soil

        extras['coarse_basins'] = coarse_basins
        return cls(terrain=terrain, grid=grid, builder=grid.builder, c2f=c2f, extras=extras)

    def test(self, *overlays):
        """Run overlays with errors propagated — fail fast for debugging."""
        results = {}
        for o in sorted(overlays, key=lambda o: o.priority):
            missing = o.requires - self.available
            if missing:
                raise ValueError(f"'{o.name}' requires {missing} but context has {self.available}")
            svg = o.renderer(self)
            tag = f"SVG ({len(svg)} chars)" if svg else "style-only"
            print(f"  ✓ {o.name:20s} pri={o.priority:<4d} {tag}")
            results[o.name] = svg
        return results


    @property
    def is_zoomed(self):
        """True if rendering a zoomed-in region with coarse→fine mapping."""
        return self.c2f is not None

    def fine_indices(self, coarse_idx):
        """Coarse index → list of fine indices (empty if unmapped)."""
        if self.c2f is None: return [coarse_idx]
        val = self.c2f.get(coarse_idx)
        if val is None: return []
        return val if isinstance(val, list) else [val]

    def fine_first(self, coarse_idx):
        """Coarse index → first fine index, or -1 if unmapped."""
        mapped = self.fine_indices(coarse_idx)
        return mapped[0] if mapped else -1


# %% ../nbs/14_overlay.ipynb #aa709836
@patch
def zoom(self: Terrain, region: HexRegion, padding: int = 1) -> 'Terrain':
    """Create a new Terrain zoomed into a HexRegion, with c2f mapping."""
    new_grid, _, mapper = region.crop_to_centered_grid(
        style=self.hexGrid.style, padding=padding
    )
    if new_grid is None:
        zoomed = self.clone()
        zoomed.c2f = None
        return zoomed

    zoomed = self.clone()
    zoomed.assign_grid(new_grid)

    # Build reverse mapping: old_idx → [new_idx] (list to match _map_point API)
    c2f = {}
    for new_idx in range(len(new_grid.hexes)):
        old_idx = mapper(new_idx)
        if 0 <= old_idx < len(self.elevations):
            zoomed.elevations[new_idx] = self.elevations[old_idx]
            for k in self.fields:
                zoomed.fields[k][new_idx] = self.fields[k][old_idx]
            c2f[old_idx] = [new_idx]

    zoomed.c2f = c2f
    return zoomed


# %% ../nbs/14_overlay.ipynb #d62f7cf3
# Keys that get pulled into extras (not passed to the Div)
_CTX_KEYS = frozenset({
    'basins', 'soil', 'result', 'board', 'c2f',
    'coarse_basins', 'corridors', 'pieces', 'squads',
})

def TerrainDisplay(
    *overlays: OverlaySpec,
    ctx: OverlayContext = None,          # pre-built context
    terrain: 'Terrain' = None,           # OR build from terrain + extras
    region: 'HexRegion' = None,
    padding: int = 1,
    radius=None,
    context_cls=OverlayContext,
    debug=False,
    **kw
):
    # ── Separate context extras from HTML attrs ──
    extras = {k: kw.pop(k) for k in list(kw) if k in _CTX_KEYS}

    if ctx is None:
        if terrain is None:
            raise ValueError("Pass either ctx= or terrain=")
        ctx = context_cls.from_terrain(
            terrain, region=region, padding=padding, radius=radius, **extras
        )

    # ── Phase 1: Run renderers in priority order ──
    sorted_overlays = sorted(overlays, key=lambda o: o.priority)
    collected = []
    for spec in sorted_overlays:
        missing = spec.requires - ctx.available
        if missing:
            logging.warning(f"Skipping {spec.name}: missing {missing}")
            continue
        try:
            svg = spec.renderer(ctx)
            if svg: collected.append((spec.name, svg))
        except Exception as e:
            logging.error(f"Overlay {spec.name} failed: {e}")

    # ── Phase 2: Bake hex styles ──
    stylized_spec = next((s for s in sorted_overlays if s.stylized), None)
    if stylized_spec:
        f = stylized_spec.edge_fn or unique_windy_edge()
        hexes_svg = ctx.grid.styleLayer(f=f, smooth=True)
        ctx.builder.adjust("hexes", hexes_svg)
    else:
        ctx.grid.update()

    # ── Phase 3: Stack SVG overlay layers ──
    for name, svg in collected:
        ctx.builder.adjust(name, svg)

    if debug: return ctx.builder.__ft__()

    return Div(
        HexTouchMap(ctx.grid, cls=kw.pop('map_cls', 'w-full h-full')),
        **kw  # remaining are HTML/HTMX attrs
    )



# %% ../nbs/14_overlay.ipynb #9bb7dd8b
def TerrainOverlay(stylized=False, edge_fn=None, **kw) -> OverlaySpec:
    """Color hexes by elevation. Pass stylized=True for organic region borders."""
    def render(ctx: OverlayContext) -> str:
        ctx.terrain.colorMap()
        return ""
    return OverlaySpec("heights", render, priority=5, stylized=stylized, edge_fn=edge_fn)


# %% ../nbs/14_overlay.ipynb #6192a6af
def ClimateOverlay(levels: int = 5, min_density: float = 0.25, **kw) -> OverlaySpec:
    """Climate zone dots colored by climate type, density by precipitation."""
    def render(ctx: OverlayContext) -> str:
        return ctx.terrain.dottedClimate(flow_levels=levels, min_density=min_density)
    return OverlaySpec("climate", render, priority=40)



def WatershedOverlay(**kw) -> OverlaySpec:
    """Watershed boundary dot overlay."""
    def render(ctx: OverlayContext) -> str:
        if not ctx.result or not hasattr(ctx.result, 'basins') or not ctx.result.basins:
            return ""
        return ctx.result.basins.dotted_watershed_overlay()
    return OverlaySpec("watersheds", render, requires={'result'}, priority=35)


# %% ../nbs/14_overlay.ipynb #b1285833
def RiverOverlay(top_n=8, simplify_k=3, max_width=None, lake_base_size=3, **kw) -> OverlaySpec:
    """River network — projects coarse paths onto fine grid when zoomed."""

    def render(ctx: OverlayContext) -> str:
        coarse_basins = getattr(ctx, 'coarse_basins', None)

        # ── Zoomed: project coarse river geometry ──
        if ctx.is_zoomed and coarse_basins is not None:
            return _render_projected(ctx, coarse_basins)

        # ── Normal (coarse): draw directly ──
        if not getattr(ctx, 'basins', None):
            return ""
        return ctx.basins.draw_watersheds(
            top_n=top_n, simplify_k=simplify_k,
            max_width=max_width, lake_base_size=lake_base_size
        )

    def _render_projected(ctx, coarse_basins):
        grid = ctx.grid
        N    = len(grid.hexes)
        max_w = max_width or grid.radius * 2 / 3

        watersheds = coarse_basins.get_major(top_n)
        if not watersheds:
            return ""

        # Global max flow for consistent width scaling
        global_max_flow = 0
        for ws in watersheds:
            flows = ws.calculate_flow()
            if flows:
                global_max_flow = max(global_max_flow, max(flows.values()))
        log_max = math.log10(global_max_flow + 1) if global_max_flow > 0 else 1

        parts = []
        for shed in watersheds:
            flows = shed.calculate_flow()
            coarse_terrain = shed.terrain

            # ── Rivers: project each segment ──
            for hexes in shed.segments():
                points = []
                mapped_hexes = []

                for h in hexes:
                    if coarse_terrain.elevations[h] <= 0:
                        if points:
                            fine_ocean = ctx.fine_first(h)
                            if 0 <= fine_ocean < N:
                                oc = grid.hexes[fine_ocean].center
                                lc = points[-1]
                                points.append(MapCord((lc.x + oc.x) / 2,
                                                      (lc.y + oc.y) / 2))
                        break

                    fine_idx = ctx.fine_first(h)
                    if 0 <= fine_idx < N:
                        points.append(grid.hexes[fine_idx].center)
                        mapped_hexes.append(h)

                if len(points) < 2:
                    continue

                # Width from flow (log scale)
                widths = []
                for h in mapped_hexes:
                    flow = max(1, flows.get(h, 1))
                    ratio = math.log10(flow + 1) / log_max if log_max > 0 else 0
                    widths.append(1.0 + ratio * (max_w - 1.0))

                avg_width = sum(widths) / len(widths) if widths else 1.0

                # Windiness from gradient
                if len(mapped_hexes) >= 2:
                    drop = (coarse_terrain.elevations[mapped_hexes[0]]
                          - coarse_terrain.elevations[mapped_hexes[-1]])
                    max_elev = max(coarse_terrain.elevations)
                    grad_ratio = min(drop / max_elev, 1.0) if max_elev > 0 else 0
                    windiness = 0.3 - grad_ratio * 0.25
                    iterations = int(5 - grad_ratio * 3)
                else:
                    windiness, iterations = 0.15, 3

                aPath = MapPath(points, style=StyleCSS("dummy"))
                windy = aPath.make_windy(iterations=iterations,
                                         offset_factor=windiness)
                inline = (f"fill:none;stroke:#1565c0;stroke-width:{avg_width:.1f};"
                          f"opacity:0.7;stroke-linecap:round;stroke-linejoin:round")
                parts.append(windy.drawSpline(adds=f'style="{inline}"'))

            # ── Lakes: project terminal basin ──
            if not shed.is_ocean and shed.terminal_hex is not None:
                lake = shed.lake_basin(base_size=lake_base_size, max_hexes=3)
                lake_fine = set()
                for lh in lake.hexes:
                    for fi in ctx.fine_indices(lh):
                        if 0 <= fi < N:
                            lake_fine.add(fi)
                if lake_fine:
                    fine_region = HexRegion(hexes=lake_fine, hexGrid=grid)
                    lake_style = StyleCSS("lake_zoom", fill="#1565c0", stroke="none")
                    grid.builder.add_style(lake_style)
                    parts.append(fine_region.draw(
                        style=lake_style, inset=0.25,
                        f=unique_windy_edge(iterations=3)
                    ))

        return '\n'.join(parts)

    return OverlaySpec("rivers", render, requires=set(), priority=60)


# %% ../nbs/14_overlay.ipynb #e4d3df3c
def CreamOverlay(stylized=False, edge_fn=None, **kw) -> OverlaySpec:
    """Parchment-style base fills. Pass stylized=True for organic region borders."""
    def render(ctx: OverlayContext) -> str:
        terrain, grid, builder = ctx.terrain, ctx.grid, ctx.builder

        terrain_fills = {
            'ocean':     '#E3F2FD',
            'coast':     '#F8F4E8',
            'lowland':   '#FDF5E6',
            'plains':    '#FAF0D4',
            'hills':     '#EFE6D5',
            'highlands': '#E8DFD0',
            'mountain':  '#DED4C4',
        }

        styles = {k: StyleCSS(k, fill=v) for k, v in terrain_fills.items()}
        for s in styles.values():
            builder.add_style(s)

        if 'distance_to_coast' not in terrain.fields:
            terrain.compute_distance_to_coast()

        for i in range(len(terrain.elevations)):
            elev = terrain.elevations[i]
            dist_coast = terrain.fields['distance_to_coast'][i]

            if elev <= 0:                              style = styles['ocean']
            elif dist_coast <= 2 and elev < 200:       style = styles['coast']
            elif elev < 200:                           style = styles['lowland']
            elif elev < 500:                           style = styles['plains']
            elif elev < 1200:                          style = styles['hills']
            elif elev < 2000:                          style = styles['highlands']
            else:                                      style = styles['mountain']

            grid.hexes[i].style = style

        return ""
    return OverlaySpec("cream", render, priority=10, stylized=stylized, edge_fn=edge_fn)


# %% ../nbs/14_overlay.ipynb #3f1810d0
def SoilOverlay(f=None, **kw) -> OverlaySpec:
    """Soil type hatch pattern overlay showing bedrock types."""
    def render(ctx: OverlayContext) -> str:
        soil = getattr(ctx, 'soil', None)
        if soil is None:
            soil = SoilSystem.from_plates(ctx.terrain, [])

        terrain, grid, builder = ctx.terrain, ctx.grid, ctx.builder
        patGen = TerrainPatterns(terrain)
        cols = [x.to_nc() for x in SoilType.standard_types()]

        # Ocean wave pattern
        ocean_hexes = terrain.find_region_at_level(0)
        ocean_region = HexRegion(hexes=ocean_hexes, hexGrid=grid)

        wave = patGen.wavePattern("ocean_waves_pat",
                                  amplitude=4, wavelength=16,
                                  color="#1565C0", fill="#E3F2FD")
        oceanStyle = StyleCSS("ocean", fill="url(#ocean_waves_pat)")
        builder.add_definition(wave)
        builder.add_style(oceanStyle)

        # Soil hatch patterns
        patterns, soilStyles = patGen.namedHatchPattern(cols, stroke_width=4, spacing=8)
        for p in patterns: builder.add_definition(p)
        for s in soilStyles: builder.add_style(s)

        # Set hex styles by soil region
        for i, region in enumerate(soil.regions):
            style = soilStyles[i]
            for h in region:
                grid.hexes[h].style = style

        for i in ocean_region:
            grid.hexes[i].style = oceanStyle

        return ""  # Pure hex style mutation — grid.update() bakes it in
    return OverlaySpec("soil", render, priority=15)


# %% ../nbs/14_overlay.ipynb #e46e6a06
def FlowOverlay(**kw) -> OverlaySpec:
    """Flow direction arrows showing drainage patterns."""
    def render(ctx: OverlayContext) -> str:
        return ctx.terrain.flow_diagram()
    return OverlaySpec("flow", render, priority=42)


# %% ../nbs/14_overlay.ipynb #4208c070
def TemperatureOverlay(ocean_color: str = "#2c5f8d", **kw) -> OverlaySpec:
    """Temperature gradient overlay — purple→blue→green→yellow→red."""
    def render(ctx: OverlayContext) -> str:
        return ctx.terrain.render_icon_temperature(ocean_color=ocean_color)
    return OverlaySpec("temperature", render, priority=41)


# %% ../nbs/14_overlay.ipynb #88d00beb
def PrecipitationOverlay(levels: int = 5, min_density: float = 0.25, 
                          color: str = "#4A90E2", **kw) -> OverlaySpec:
    """Precipitation density dots — denser dots = more rainfall."""
    def render(ctx: OverlayContext) -> str:
        if 'precipitation' not in ctx.terrain.fields:
            ctx.terrain.compute_weather()
        return ctx.terrain.dotted_field(
            field='precipitation',
            flow_levels=levels,
            min_density=min_density,
            color=color
        )
    return OverlaySpec("precipitation", render, priority=43)


# %% ../nbs/14_overlay.ipynb #26d148f7
def join_paths(paths, tolerance=2.0):
    """Join connected MapPath segments into longer continuous paths."""
    if not paths: return paths
    
    remaining = list(paths)
    joined = []
    
    while remaining:
        current_pts = list(remaining.pop(0).points)
        changed = True
        
        while changed:
            changed = False
            for i, seg in enumerate(remaining):
                start, end = seg.points[0], seg.points[-1]
                cur_start, cur_end = current_pts[0], current_pts[-1]
                
                if cur_end.distance(start) < tolerance:
                    current_pts.extend(seg.points[1:])  # skip duplicate point
                    remaining.pop(i); changed = True; break
                elif cur_end.distance(end) < tolerance:
                    current_pts.extend(reversed(seg.points[:-1]))
                    remaining.pop(i); changed = True; break
                elif cur_start.distance(end) < tolerance:
                    current_pts = list(seg.points[:-1]) + current_pts
                    remaining.pop(i); changed = True; break
                elif cur_start.distance(start) < tolerance:
                    current_pts = list(reversed(seg.points[1:])) + current_pts
                    remaining.pop(i); changed = True; break
        
        joined.append(MapPath(points=current_pts, style=paths[0].style))
    
    return joined


# %% ../nbs/14_overlay.ipynb #363af4b9
def offset_path(points, distance):
    """Offset a closed path by `distance` pixels using averaged vertex normals."""
    n = len(points)
    if n < 3: return points
    result = []
    for i in range(n):
        p_prev = points[(i - 1) % n]
        p_curr = points[i]
        p_next = points[(i + 1) % n]

        dx1, dy1 = p_curr.x - p_prev.x, p_curr.y - p_prev.y
        dx2, dy2 = p_next.x - p_curr.x, p_next.y - p_curr.y

        l1 = math.sqrt(dx1**2 + dy1**2) or 1
        l2 = math.sqrt(dx2**2 + dy2**2) or 1

        nx1, ny1 = dy1/l1, -dx1/l1
        nx2, ny2 = dy2/l2, -dx2/l2

        avg_nx = (nx1 + nx2) / 2
        avg_ny = (ny1 + ny2) / 2
        l = math.sqrt(avg_nx**2 + avg_ny**2) or 1

        result.append(MapCord(
            p_curr.x + distance * avg_nx / l,
            p_curr.y + distance * avg_ny / l
        ))
    return result


def _detect_offset_sign(points, grid, ocean_hexes, test_dist=10):
    """Determine which sign of offset pushes toward the ocean interior."""
    n = len(points)
    if n < 10: return 1

    # Use centroid of boundary path as proxy for ocean interior
    cx = sum(p.x for p in points) / n
    cy = sum(p.y for p in points) / n

    # Sample some points, offset both ways, see which is closer to centroid
    step = max(1, n // 8)
    pos_score, neg_score = 0, 0

    pos_pts = offset_path(points, test_dist)
    neg_pts = offset_path(points, -test_dist)

    for i in range(0, n, step):
        dp = (pos_pts[i].x - cx)**2 + (pos_pts[i].y - cy)**2
        dn = (neg_pts[i].x - cx)**2 + (neg_pts[i].y - cy)**2
        if dp < dn:
            pos_score += 1
        else:
            neg_score += 1

    return 1 if pos_score >= neg_score else -1



def wave_svg_path(points, amplitude, wavelength, phase=0):
    """Generate SVG path 'd' string from points with sine perturbation along normals."""
    n = len(points)
    if n < 3: return ""

    cum_dist = 0
    coords = []

    for i in range(n):
        if i > 0:
            dx = points[i].x - points[i-1].x
            dy = points[i].y - points[i-1].y
            cum_dist += math.sqrt(dx**2 + dy**2)

        p_prev = points[(i - 1) % n]
        p_next = points[(i + 1) % n]
        dx = p_next.x - p_prev.x
        dy = p_next.y - p_prev.y
        l = math.sqrt(dx**2 + dy**2) or 1
        nx, ny = dy/l, -dx/l

        wave = amplitude * math.sin(2 * math.pi * cum_dist / wavelength + phase)
        coords.append(MapCord(points[i].x + wave * nx, points[i].y + wave * ny))

    d = f"M {coords[0].x:.1f},{coords[0].y:.1f}"
    for c in coords[1:]:
        d += f" L {c.x:.1f},{c.y:.1f}"
    return d


def OceanWaveOverlay(
    num_waves=5,
    spacing=8,
    amplitude_start=3.0,
    amplitude_decay=0.6,
    wavelength=40,
    stroke_color="#4a7fb5",
    opacity_start=0.5,
    opacity_decay=0.7,
    stroke_width=1.2,
    edge_fn=None,
    **kw
) -> OverlaySpec:
    """Ocean wave lines that follow the coastline and fade outward into the sea."""

    def render(ctx) -> str:
        terrain = ctx.terrain
        grid = ctx.grid

        # 1. Ocean region
        ocean_hexes = {i for i, e in enumerate(terrain.elevations) if e <= 0}
        if not ocean_hexes:
            return ""
        ocean_region = HexRegion(hexes=ocean_hexes, hexGrid=grid)

        borders = {}
        dummy_style = StyleCSS("_wave_boundary", fill="none", stroke="none")
        coast_paths = ocean_region.trace_perimeter_cached(
            borders=borders, f=edge_fn, style=dummy_style
        )
        if not coast_paths:
            return ""

        # 2. Clip path from ocean boundary
        clip_parts = []
        for cp in coast_paths:
            pts = cp.points
            if not pts: continue
            d = f"M {pts[0].x:.1f},{pts[0].y:.1f}"
            for p in pts[1:]:
                d += f" L {p.x:.1f},{p.y:.1f}"
            d += " Z"
            clip_parts.append(d)

        clip_d = " ".join(clip_parts)
        #clip_svg = f'<clipPath id="ocean-wave-clip"><path d="{clip_d}"/></clipPath>'
        #ctx.builder.add_definition(SVGDef("clipPath", "ocean-wave-clip", clip_svg, raw=True))

        # 3. Register wave styles
        amp = amplitude_start
        opacity = opacity_start
        for w in range(num_waves):
            style = StyleCSS(
                f"ocean_wave_{w}",
                fill="none",
                stroke=stroke_color,
                stroke_width=stroke_width,
                opacity=round(opacity, 3),
                stroke_linecap="round"
            )
            ctx.builder.add_style(style)
            amp *= amplitude_decay
            opacity *= opacity_decay

        # 4. Generate wave lines
        #svg_parts = ['<g clip-path="url(#ocean-wave-clip)">']
        svg_parts = ['<g>']

        coast_paths = join_paths(coast_paths, tolerance=grid.radius * 0.5)

        for coast_path in coast_paths:
            pts = coast_path.points
            if len(pts) < 3: continue

            # Smooth the coastline to remove hex-corner artifacts
            smoothed = coast_path.smooth(iterations=3)
            pts = smoothed.points
            
            # Auto-detect which direction is "into the ocean"
            sign = _detect_offset_sign(pts, grid, ocean_hexes, test_dist=spacing * 2)
            
            amp = amplitude_start
            for w in range(num_waves):
                dist = sign * spacing * (w + 1)
                offset_pts = offset_path(pts, dist)
                phase = w * 1.2

                d = wave_svg_path(offset_pts, amp, wavelength, phase)
                if d:
                    svg_parts.append(f'<path d="{d}" class="ocean_wave_{w}"/>')

                amp *= amplitude_decay

        svg_parts.append('</g>')
        return '\n'.join(svg_parts)

    return OverlaySpec("ocean_waves", render, priority=20)

