# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_terrain.ipynb.

# %% auto #0
__all__ = ['EARTH_RADIUS_M', 'TerraDemo', 'GeoBounds', 'ClimatePreset', 'Terrain', 'USGSTerrainFetcher']

# %% ../nbs/03_terrain.ipynb #91bb6416
#standard
import numpy as np
import sys
import os
import math
from math import radians, cos, sin, sqrt, atan2
import random

from importlib import resources
import asyncio

#data
from collections import namedtuple
from dataclasses import dataclass,  field, asdict
from typing import List
from enum import Enum
import copy

#Jeremy
from dialoghelper import * 
from fastcore.basics import patch
from fasthtml.common import *
from fasthtml.jupyter import *
import httpx

# unique
from treelib import Tree
import heapq

# %% ../nbs/03_terrain.ipynb #a00c60ae
from .styles import StyleCSS, SVGBuilder,SVGLayer, SVGPatternLoader, preview, app, rt, StyleDemo

from .primitives import MapCord, MapSize, MapRect, MapPath, Hex, HexGrid, HexRegion, HexWrapper, HexPosition, PrimitiveDemo, HexTouchMap

# %% ../nbs/03_terrain.ipynb #e71cfd34
class TerraDemo:
    def __init__(self):
        self.help = ""

# %% ../nbs/03_terrain.ipynb #f32d3273
@dataclass
class GeoBounds:
    """Geographic bounds in lat/lon."""
    lat_min: float
    lat_max: float
    lon_min: float
    lon_max: float
    
    @property
    def lat_center(self):
        return (self.lat_min + self.lat_max) / 2
    
    @property
    def lon_center(self):
        return (self.lon_min + self.lon_max) / 2
    
    @property
    def lat_span(self):
        return self.lat_max - self.lat_min
    
    @property
    def lon_span(self):
        return self.lon_max - self.lon_min

# %% ../nbs/03_terrain.ipynb #d445eba7
EARTH_RADIUS_M = 6_371_000  # meters

@patch
def meters_per_degree_lon(self: GeoBounds, lat: float) -> float:
    """Meters per degree longitude at given latitude."""
    return EARTH_RADIUS_M * radians(1) * cos(radians(lat))

@patch
def meters_per_degree_lat(self: GeoBounds) -> float:
    """Meters per degree latitude (nearly constant)."""
    return EARTH_RADIUS_M * radians(1)

@patch
def haversine_distance(self: GeoBounds, lat1: float, lon1: float, 
                       lat2: float, lon2: float) -> float:
    """Great-circle distance in meters between two points."""
    φ1, φ2 = radians(lat1), radians(lat2)
    Δφ = radians(lat2 - lat1)
    Δλ = radians(lon2 - lon1)
    
    a = sin(Δφ/2)**2 + cos(φ1) * cos(φ2) * sin(Δλ/2)**2
    return EARTH_RADIUS_M * 2 * atan2(sqrt(a), sqrt(1-a))

@patch
def pixel_to_latlon(self: GeoBounds, px: float, py: float, 
                    width: float, height: float) -> tuple[float, float]:
    """Convert pixel coords to lat/lon with latitude correction."""
    # Normalize to 0-1
    nx = px / width
    ny = py / height
    
    # Linear in latitude (y maps to lat, inverted since y grows down)
    lat = self.lat_max - ny * self.lat_span
    
    # Longitude adjusted for latitude - use center latitude for now
    # More sophisticated: could interpolate based on current row
    lon = self.lon_min + nx * self.lon_span
    
    return lat, lon

@patch  
def latlon_to_pixel(self: GeoBounds, lat: float, lon: float,
                    width: float, height: float) -> tuple[float, float]:
    """Convert lat/lon to pixel coords."""
    ny = (self.lat_max - lat) / self.lat_span
    nx = (lon - self.lon_min) / self.lon_span
    return nx * width, ny * height

@patch
def area_at_latitude(self: GeoBounds, lat: float, hex_radius_m: float) -> float:
    """Hex area in square meters at given latitude."""
    # Hex area = (3√3/2) * r²
    return (3 * sqrt(3) / 2) * hex_radius_m**2


# %% ../nbs/03_terrain.ipynb #0f6eeacb
@dataclass
class ClimatePreset:
    """Preset parameters for different climate zones."""
    name: str
    lat_range: tuple[float, float]
    base_temp_range: tuple[float, float]  # (south/low, north/high)
    
    # Smith-Barstad precipitation parameters
    wind_speed: float = 10.0
    wind_dir: float = 270.0
    precip_base: float = 0.1
    nm: float = 0.01
    hw: float = 2000.0
    cw: float = 0.002
    conv_time: float = 2000.0
    fall_time: float = 2000.0
    
    # Temperature parameters
    lapse_rate: float = 6.5
    
    # Precipitation thresholds for 5 dot size levels (mm/year)
    # Creates 5 ranges: <bin[0], bin[0]-bin[1], bin[1]-bin[2], bin[2]-bin[3], >bin[3]
    precip_bins: tuple[float, float, float, float] = (400, 800, 1500, 2500)
    
    # Description
    description: str = ""
    
    def get_precip_level(self, precip_mm: float) -> int:
        """Convert precipitation to dot size level (0-4) for this climate."""
        for i, threshold in enumerate(self.precip_bins):
            if precip_mm < threshold:
                return i
        return len(self.precip_bins)  # Highest level (4)
    
    def encode(self) -> str:
        """Encode climate preset to a single line string."""
        bins_str = ','.join(map(str, self.precip_bins))
        parts = [
            self.name,
            f"{self.lat_range[0]},{self.lat_range[1]}",
            f"{self.base_temp_range[0]},{self.base_temp_range[1]}",
            str(self.wind_speed),
            str(self.wind_dir),
            str(self.precip_base),
            str(self.nm),
            str(self.hw),
            str(self.cw),
            str(self.conv_time),
            str(self.fall_time),
            str(self.lapse_rate),
            bins_str,  # Add precip_bins
            self.description.replace('|', '//')  # escape pipe chars
        ]
        return '|'.join(parts)
    
    @staticmethod
    def decode(s: str) -> 'ClimatePreset':
        """Decode climate preset from string."""
        parts = s.split('|')
        lat_range = tuple(map(float, parts[1].split(',')))
        temp_range = tuple(map(float, parts[2].split(',')))
        precip_bins = tuple(map(float, parts[12].split(',')))
        
        return ClimatePreset(
            name=parts[0],
            lat_range=lat_range,
            base_temp_range=temp_range,
            wind_speed=float(parts[3]),
            wind_dir=float(parts[4]),
            precip_base=float(parts[5]),
            nm=float(parts[6]),
            hw=float(parts[7]),
            cw=float(parts[8]),
            conv_time=float(parts[9]),
            fall_time=float(parts[10]),
            lapse_rate=float(parts[11]),
            precip_bins=precip_bins,
            description=parts[13].replace('//', '|') if len(parts) > 13 else ""
        )


# %% ../nbs/03_terrain.ipynb #27d994d9
class Terrain:

    def __init__(self,
    bounds:MapRect, #our canvas size, 
    path: str = "sample.svg", #where are we going to export
    radius: float = 25.0, #default hex size,
    fields:[str] = [],
    colorLevels:[StyleCSS] = StyleCSS.elevations(),
    seaLevel:StyleCSS =  StyleCSS("sealevel",fill ="#81b1e1ff"),
    elevationDelta:float = 90,
    geo:GeoBounds = None,
    climate:ClimatePreset = None
   

    ):
        self.colorLevels = colorLevels
        self.seaLevel = seaLevel
        self.hexGrid = HexGrid.from_bounds(bounds, radius=radius, style=seaLevel)
        self.hexGrid.builder.add_style(seaLevel)
        self.path = path
        self.climate = climate
        

        for  x in self.colorLevels: 
            hover = StyleCSS("hover",fill=x.desaturate().properties["fill"],cursor="pointer" )
            #hover = StyleCSS("hover",fill="#007fff",cursor="pointer" )
            x.customize(hover)
            self.hexGrid.builder.add_style(x)
           
        self.elevationDelta = elevationDelta
        self.elevations = np.zeros(len(self.hexGrid.hexes))
        self.fields = {}
        self.geo = geo
        for field in  fields:
            self.fields[field] = np.zeros(len(self.hexGrid.hexes))
       
    @property
    def builder(self):
        return self.hexGrid.builder

    def colorMap(self):
        numHeights = len(self.colorLevels)
        if numHeights < 1:
            return 0
        for i in range(len(self.elevations)):
            height = int(self.elevations[i]  / self.elevationDelta)
            
            aLevel =  self.seaLevel
            if self.elevations[i]  > 0:
                if height < numHeights:
                    aLevel = self.colorLevels[height]
                else:
                    aLevel = self.colorLevels[-1]
            self.hexGrid.hexes[i].style = aLevel
            


    def textElevations(self):
        grid = self.hexGrid 
        nRows = grid.nRows
        nCols =  grid.nCols
        
        i = 0
        for row in range(nRows):
        
            line = "|"
            for col in range(nCols):
                line += f" { int(self.elevations[i]/100):3}"
                i += 1

            print(line + " |")

    def textStyle(self):
        grid = self.hexGrid 
        nRows = grid.nRows
        nCols =  grid.nCols
        
        i = 0
        for row in range(nRows):
        
            line = "|"
            for col in range(nCols):
                line += f" { self.hexGrid.hexes[i].style.name[:3]:3}"
                i += 1

            print(line + " |")
         
    
    def encode(self):
        grid = self.hexGrid 
        nRows = grid.nRows
        nCols = grid.nCols
        ret = f"radius:{self.hexGrid.radius}\n"
        ret += f"size:{self.hexGrid.nRows}^{self.hexGrid.nCols}\n"
        ret += f"path:{self.path}\n"
        field_names = '\t'.join(self.fields.keys())
        ret += f"fields:{field_names}\n"
        
        
        # Add geobounds if present
        if self.geo is not None:
            ret += f"geo:{self.geo.lat_min},{self.geo.lat_max},{self.geo.lon_min},{self.geo.lon_max}\n"
        
        # Add climate if present
        if self.climate is not None:
            ret += f"climate:{self.climate.encode()}\n"
        
        ret += f"+data:\n"
        i = 0
        for row in range(nRows):
            line = []
            for col in range(nCols):
                csv_parts = [str(self.elevations[i])]
                for fieldName in self.fields.keys():
                    csv_parts.append(str(self.fields[fieldName][i]))
                line.append(','.join(csv_parts))
                i += 1
            ret += "\t".join(line) + "\n"
        ret += f"-data:\n"
        
        return ret


    @staticmethod
    def decode(s: str):
        """Parse a formatted string and create a Terrain from it."""
        lines = s.strip().split('\n')
        
        # Parse header
        radius = None
        path = None
        geo = None
        climate = None  # New: store climate preset
        inGrid = False
        nRow = 0
        nCol = 0
        fieldNames = []
        elevations = []
        fieldData = {}
        
        for line in lines:
            if not inGrid:
                if ':' not in line:
                    continue
                val = line.split(':', 1)[1].strip()  # Use maxsplit=1 for climate line
                
                if line.startswith('radius:'):
                    radius = float(val)
                elif line.startswith('size:'):
                    size = val.split('^')
                    nRow = int(size[0])
                    nCol = int(size[1])
                elif line.startswith('path:'):
                    path = val
                elif line.startswith('fields:'):
                    fieldNames = val.split('\t')
                elif line.startswith('geo:'):
                    coords = val.split(',')
                    geo = GeoBounds(
                        lat_min=float(coords[0]),
                        lat_max=float(coords[1]),
                        lon_min=float(coords[2]),
                        lon_max=float(coords[3])
                    )
                elif line.startswith('climate:'):
                    climate = ClimatePreset.decode(val)
                elif line.startswith('+data:'):
                    inGrid = True
                    fieldData = {name: [] for name in fieldNames}
            else:
                if line.startswith('-data:'):
                    break
                else:
                    cells = line.split('\t')
                    for cell in cells:
                        values = cell.split(',')
                        elevations.append(float(values[0]))
                        for i, fieldName in enumerate(fieldNames):
                            fieldData[fieldName].append(float(values[i + 1]))
        
        # Create Terrain object
        bounds = MapRect(MapCord(0, 0), MapSize(nRow * radius, nCol * radius))
        retTerrain = Terrain(bounds=bounds, path=path, radius=radius, climate=climate, geo=geo)
        retTerrain.hexGrid.nRows = nRow
        retTerrain.hexGrid.nCols = nCol
        retTerrain.hexGrid.adjustRadius(radius)
        
        retTerrain.elevations = np.array(elevations)
        retTerrain.fields = {name: np.array(fieldData[name]) for name in fieldNames}
        
        return retTerrain




# %% ../nbs/03_terrain.ipynb #3885dbae
@patch
def clone(self: Terrain) -> 'Terrain':
    """Create a deep copy of this terrain."""
   
    
    # Create new terrain with same basic params
    bounds = MapRect(MapCord(0, 0), MapSize(
        self.hexGrid.nRows * self.hexGrid.radius,
        self.hexGrid.nCols * self.hexGrid.radius
    ))
    
    new_terrain = Terrain(
        bounds=bounds,
        path=self.path,
        radius=self.hexGrid.radius,
        fields=list(self.fields.keys()),
        colorLevels=self.colorLevels,  # These are shared (immutable styles)
        seaLevel=self.seaLevel,
        elevationDelta=self.elevationDelta,
        geo=copy.deepcopy(self.geo) if self.geo else None,
        climate=copy.deepcopy(self.climate) if self.climate else None
    )
    
    # Match grid dimensions
    new_terrain.hexGrid.nRows = self.hexGrid.nRows
    new_terrain.hexGrid.nCols = self.hexGrid.nCols
    new_terrain.hexGrid.adjustRadius(self.hexGrid.radius)
    
    # Deep copy numpy arrays
    new_terrain.elevations = self.elevations.copy()
    new_terrain.fields = {k: v.copy() for k, v in self.fields.items()}
    
    # Copy hex styles
    for i, hex in enumerate(self.hexGrid.hexes):
        new_terrain.hexGrid.hexes[i].style = hex.style

    new_terrain.geo = self.geo
    new_terrain.climate = self.climate
    
    return new_terrain


# %% ../nbs/03_terrain.ipynb #07c19dbd
@patch
def elevationLevel(self: Terrain, idx):
    """Return the elevation level (integer) for a hex by dividing by elevationDelta."""
    if self.elevations[idx] > 0:
        return int(self.elevations[idx] / self.elevationDelta)
    return -1

@patch
def export(self:Terrain,wrapper:HexWrapper = None):
    if wrapper is None:
        wrapper = HexWrapper()

    testStr = self.encode()
    with open(self.path, 'w') as f:
        f.write(testStr)

@patch
def ring(self:Terrain,center,radius=1):
    if radius < 1:
        return [center]
    ring_hexpositions = HexPosition(0, 0, 0).ring(radius)
    ring_indices = [self.hexGrid.hexposition_to_index(hp, center) for hp in ring_hexpositions]
    return [i for i in ring_indices if i >= 0]  # Filter out-of-bounds

# %% ../nbs/03_terrain.ipynb #1b7af861
@patch
def sanFran(self:TerraDemo):
    with resources.files('HexMagic').joinpath('data/templates/san_francisco.txt').open() as f:
    
        myGrid = Terrain.decode(f.read())
    return myGrid

@patch
def agincourt(self:TerraDemo):
    with resources.files('HexMagic').joinpath('data/templates/agincourt.txt').open() as f:
    
        myGrid = Terrain.decode(f.read())
    return myGrid

# %% ../nbs/03_terrain.ipynb #db525d9a
@patch
def demoSanFran(self:TerraDemo):
    sampleMap = self.agincourt()
    sampleMap.elevationDelta = 20
    colors = StyleCSS.seaborn("rocket",13)
    sampleMap.colorLevels = colors
    
    for color in colors:
        sampleMap.hexGrid.builder.add_style(color)

    sampleMap.hexGrid.adjustRadius(5)
    sampleMap.colorMap()
    
    sampleMap.hexGrid.update()
    return sampleMap.hexGrid.builder.show()



# %% ../nbs/03_terrain.ipynb #0bf3d056
@patch
def elevation_borders(self: Terrain)->str:
    """Draw hex borders with stroke color/width based on elevation."""
    
    border_svg = ""
    border_styles = {}
    elevation_styles = StyleCSS.seaborn("YlOrBr", levels=13)[2:8]
    for i, style in enumerate(elevation_styles):
        fill = style.properties["fill"]
        border_styles[i] = (f"stroke:{fill}; stroke-width:{1.5}; opacity:{0.5 + 0.5 * i}", "{style.name}_tacoBell")
    #border_styles[0] =  ("stroke:#5a7a8f; stroke-width:0.5; opacity:0.3", "coastal")

    # Define border styles by elevation level
    oldborder_styles = {
        0: ("stroke:#5a7a8f; stroke-width:0.5; opacity:0.3", "coastal"),  # Sea level - subtle
        1: ("stroke:#7d6e5d; stroke-width:0.8; opacity:0.4", "lowland"),
        2: ("stroke:#8b7d6b; stroke-width:1.0; opacity:0.5", "hills"),
        3: ("stroke:#9d8b73; stroke-width:1.2; opacity:0.6", "highlands"),
        4: ("stroke:#a89579; stroke-width:1.5; opacity:0.7", "mountains"),
        5: ("stroke:red; stroke-width:3; opacity:0.8", "peaks"), # was b5a085
    }
    
    for i, hex in enumerate(self.hexGrid.hexes):
        elev_level = self.elevationLevel(i)
        
        if elev_level >= 0:  # Skip ocean
            style_str, style_name = border_styles.get(
                min(elev_level, 5), 
                border_styles[5]
            )
            
            # Draw just the border (no fill)
            border_svg += f'<polygon points="'
            for point in hex.vertices():
                border_svg += f"{point.x:.0f},{point.y:.0f} "
            border_svg += f'" style="fill:none; {style_str}"/>\n'

    return border_svg

# %% ../nbs/03_terrain.ipynb #aba3882b
@patch
def add_elevation_borders(self: Terrain, layer_name="elevation_borders"):
    """Draw hex borders with stroke color/width based on elevation."""
    
    border_svg = self.elevation_borders()
    
    self.hexGrid.builder.adjust(layer_name, border_svg)
    return self

# %% ../nbs/03_terrain.ipynb #918d5f21
@patch
def tiny(self:TerraDemo):
    mySize = MapSize(120,120)
    myBounds = MapRect(MapCord(0,0), mySize)
    sampleMap =  Terrain(myBounds,radius=30,path = "tiny.svg")

    adjustments =   np.zeros(len(sampleMap.elevations))
    baseHeight = 600
    origin = 5
  
    for i in sampleMap.ring(origin,2):
        adjustments[i] = baseHeight/4
    
    for i in sampleMap.ring(origin,1):
        adjustments[i] = baseHeight/2

    adjustments[origin] = baseHeight

    sampleMap.elevations += adjustments
    return sampleMap

# %% ../nbs/03_terrain.ipynb #d661c399
@patch
def demoTiny(self:TerraDemo):
    

    sampleMap = self.tiny()


    print(sampleMap.encode())
    print("=======")

    sampleMap.hexGrid.adjustRadius(5)
    print(sampleMap.encode())

    print("++===++")
    sampleMap.hexGrid.adjustRadius(50)
    sampleMap.colorMap()
    
    sampleMap.hexGrid.update()

    return sampleMap.hexGrid.builder.show()






# %% ../nbs/03_terrain.ipynb #7dd6c3b9
@patch
def colorRegions(self:Terrain,regions:[HexRegion],fills:[str])->str:
    testBody = ""
    grid = self.hexGrid

    addSet = set()
    for cI, region in enumerate(regions):
        print(f" region {cI} has hexes {len(region.hexes)}")
        
        if cI >= len(fills):
            cI = len(fills) - 1

        fill = fills[cI]
        for i in region.hexes:
            ret = "<polygon points=\""
            hex = grid.hexes[i]
            for point in hex.vertices():
                ret += f"{point.x:.0f},{point.y:.0f} "
            ret += f"\" style=\"fill:{fill}\""
            ret += "/>"

            testBody += "\t" +  ret + "\n"

    return testBody

# %% ../nbs/03_terrain.ipynb #60f29138
@patch
def styleRegion(self:Terrain,region:HexRegion,style:StyleCSS)->str:
    testBody = ""
    grid = self.hexGrid

    
    for i in region.hexes:
        ret = "<polygon points=\""
        hex = grid.hexes[i]
        for point in hex.vertices():
            ret += f"{point.x:.0f},{point.y:.0f} "
        ret += f"\" class=\"{style.name}\""
        ret += "/>"
        testBody += "\t" +  ret + "\n"

    return testBody

# %% ../nbs/03_terrain.ipynb #86004d88
@patch
def cone(self:Terrain, center, adjusted, num_rings, variability=0.0):
    """Create a volcano-like elevation pattern.
    
    Args:
        center: index of center hex
        adjusted: peak height at center
        num_rings: how many rings outward to affect
        variability: amount of random variation (0 = none)
    """
    adjustments = np.zeros(len(self.elevations))
    
    # Center hex
    center_variation = random.uniform(-variability, variability) if variability > 0 else 0
    adjustments[center] = adjusted + center_variation
    
    # Process each ring outward
    for ring_num in range(1, num_rings + 1):
        ring_indices = self.ring(center, ring_num)
        
        for idx in ring_indices:
            # Calculate base height using smooth curve
            distance_ratio = ring_num / num_rings
            base_height = adjusted * (1 - distance_ratio) ** 2
            
            # Get neighbors from inner ring
            hp = self.hexGrid.index_to_hexposition(idx, center)
            neighbor_positions = hp.ring(1)
            neighbor_indices = [self.hexGrid.hexposition_to_index(nhp, center) 
                               for nhp in neighbor_positions]
            
            # Find which neighbors are in the inner ring
            inner_ring_indices = set(self.ring(center, ring_num - 1))
            adjacent_inner = [ni for ni in neighbor_indices 
                            if ni >= 0 and ni in inner_ring_indices]
            
            # Calculate variability based on adjacent inner ring hexes
            if adjacent_inner and variability > 0:
                avg_inner = np.mean([adjustments[i] for i in adjacent_inner])
                variation = random.uniform(-variability, variability)
                # Blend the variation with the inner ring average
                height_variation = (avg_inner - base_height) * 0.3 + variation
            else:
                height_variation = random.uniform(-variability, variability) if variability > 0 else 0
            
            adjustments[idx] = base_height + height_variation
    
    return adjustments


# %% ../nbs/03_terrain.ipynb #e6799e87
@patch
def volcano(self:Terrain, center, adjusted, num_rings, variability=0.0, initial_threshold=0.8):
    """Create a volcano-like elevation pattern with threshold-based coastlines.
    
    Args:
        center: index of center hex
        adjusted: peak height at center
        num_rings: how many rings outward to affect
        variability: amount of random variation (0 = none)
        initial_threshold: starting threshold (decreases each ring outward)
    """
    adjustments = np.zeros(len(self.elevations))
    
    # Center hex (always applied)
    center_variation = random.uniform(-variability, variability) if variability > 0 else 0
    adjustments[center] = adjusted + center_variation
    
    # Process each ring outward
    for ring_num in range(1, num_rings + 1):
        ring_indices = self.ring(center, ring_num)
        
        # Calculate threshold for this ring (decreases as we go outward)
        #threshold = initial_threshold * (1 - ring_num / num_rings)
        threshold = initial_threshold * (ring_num / num_rings)

        
        for idx in ring_indices:
            # Check if this hex passes the threshold
            if random.random() > threshold:
                # Calculate base height using smooth curve
                distance_ratio = ring_num / num_rings
                base_height = adjusted * (1 - distance_ratio) ** 2
                
                # Get neighbors from inner ring
                hp = self.hexGrid.index_to_hexposition(idx, center)
                neighbor_positions = hp.ring(1)
                neighbor_indices = [self.hexGrid.hexposition_to_index(nhp, center) 
                                   for nhp in neighbor_positions]
                
                # Find which neighbors are in the inner ring
                inner_ring_indices = set(self.ring(center, ring_num - 1))
                adjacent_inner = [ni for ni in neighbor_indices 
                                if ni >= 0 and ni in inner_ring_indices]
                
                # Calculate variability based on adjacent inner ring hexes
                if adjacent_inner and variability > 0:
                    avg_inner = np.mean([adjustments[i] for i in adjacent_inner])
                    variation = random.uniform(-variability, variability)
                    # Blend the variation with the inner ring average
                    height_variation = (avg_inner - base_height) * 0.3 + variation
                else:
                    height_variation = random.uniform(-variability, variability) if variability > 0 else 0
                
                adjustments[idx] = base_height + height_variation
    
    return adjustments


# %% ../nbs/03_terrain.ipynb #02434f00
@patch
def demoVolcano(self:TerraDemo):

    mySize = MapSize(480,480)
    myBounds = MapRect(MapCord(0,0), mySize)
    sampleMap =  Terrain(myBounds,radius=15,path = "volcano.svg")
    
    sampleMap.elevations += sampleMap.volcano(center=267,adjusted=500,num_rings=6,variability=0.5,initial_threshold=0.4)
    sampleMap.colorMap()
    sampleMap.hexGrid.update()

    return sampleMap


# %% ../nbs/03_terrain.ipynb #fcf1848e
@patch
def find_peaks(self:Terrain, k, min_height, exclusion_radius=1):
    """Find k largest peaks above min_height with exclusion zones.
    
    Args:
        k: maximum number of peaks to find
        min_height: minimum elevation threshold
        exclusion_radius: how many rings around each peak to exclude
    
    Returns:
        List of indices of peaks (up to k peaks)
    """
 
    # Create max heap of all hexes above threshold
    # Use negative elevation for max heap behavior
    candidates = [(-self.elevations[i], i) 
                  for i in range(len(self.elevations)) 
                  if self.elevations[i] >= min_height]
    
    heapq.heapify(candidates)
    
    peaks = []
    blocked = set()
    
    while len(peaks) < k and candidates:
        neg_elevation, idx = heapq.heappop(candidates)
        
        # Skip if this hex is blocked
        if idx in blocked:
            continue
        
        # Add this peak
        peaks.append(idx)
        
        # Block this peak and surrounding hexes
        for radius in range(exclusion_radius + 1):
            for blocked_idx in self.ring(idx, radius):
                blocked.add(blocked_idx)
    
    return peaks


# %% ../nbs/03_terrain.ipynb #55b7a8b3
@patch
def demoPeakSan(self:TerraDemo):
    sampleMap = self.sanFran()
    peaks = sampleMap.find_peaks(7,0)
    for peak in peaks:
        sampleMap.elevations[peak] = 900
    #sampleMap.elevationDelta = 20
    sampleMap.hexGrid.adjustRadius(5)
    sampleMap.colorMap()
    
    sampleMap.hexGrid.update()
    return sampleMap.hexGrid.builder.show()




# %% ../nbs/03_terrain.ipynb #9674486a
@patch
def lowest_neighbor(self:Terrain, idx):
    """Find the lowest neighbor of idx, or None if idx is a local minimum."""
    neighbors = self.ring(idx)
    current_elev = self.elevations[idx]
    
    lowest_idx = None
    lowest_elev = current_elev
    
    for n in neighbors:
        if self.elevations[n] < lowest_elev:
            lowest_elev = self.elevations[n]
            lowest_idx = n
    
    return lowest_idx

# %% ../nbs/03_terrain.ipynb #63071ac6
@patch
def dot(self:Terrain, 
    points:[MapCord],
    style=StyleCSS("dataPoint",fill="#aa6092ff",stroke="#4bc151ff",stroke_width=0.5),
    layerName="circles",
    radius = 3 ):
   
    # Draw circles at perimeter points

    circle_layer = ""
    for point in points:
        circle_layer += f"""\t<circle cx="{point.x}" cy="{point.y}" r="{radius}" class="{style.name}"/>\n"""
  
    
    self.builder.add_style(style)
    self.builder.adjust(layerName, circle_layer)
    
    

# %% ../nbs/03_terrain.ipynb #da20d057
@patch
def fillRegion(self:Terrain, region:HexRegion):
    """Fill a region with a style."""
    
    fill_layer = ""

    fills=["#d4ff00eb","#ffb300ff","#ff0073ff","#9900ff97","#1e0e45eb"]
    
    flowData = np.zeros(len(self.hexGrid.hexes)) - 1

    for i in region.hexes:
        #print(i)
        flowData[i] = 1

    flowData = [int(x) for x in flowData]
    # Create patterns and overlay
    patternGen = TerrainPatterns(self)
    patterns = patternGen.ballDensity(3,fills=fills)  # 5 levels
    self.makeOverlay(flowData, patterns)
    

# %% ../nbs/03_terrain.ipynb #0eb7a13c
@patch
def colorRegions(self:Terrain,regions:[HexRegion],fills:[str])->str:
    testBody = ""
    grid = self.hexGrid

    addSet = set()
    for cI, region in enumerate(regions):
        print(f" region {cI} has hexes {len(region.hexes)}")
        
        if cI >= len(fills):
            cI = len(fills) - 1

        fill = fills[cI]
        for i in region.hexes:
            ret = "<polygon points=\""
            hex = grid.hexes[i]
            for point in hex.vertices():
                ret += f"{point.x:.0f},{point.y:.0f} "
            ret += f"\" style=\"fill:{fill}\""
            ret += "/>"

            testBody += "\t" +  ret + "\n"

    return testBody

# %% ../nbs/03_terrain.ipynb #9f1642ca
@patch
def demoRegion(self:TerraDemo):
    """Practice building up coord."""
    
    sampleMap = self.sanFran()
    peaks = sampleMap.find_peaks(7,0)
    start = peaks[0]
    region = HexRegion(hexes=set([start]),  hexGrid=sampleMap.hexGrid)
    #region.add(start)
    #print(region.perimeter())
    
    ring_indices = sampleMap.ring(start)
    for idx in ring_indices:
        region.hexes.add(idx)
        
    ring_indices = sampleMap.ring(start,2)
    for idx in ring_indices:
        region.hexes.add(idx)

    # Show the base terrain
    sampleMap.colorMap()
    sampleMap.hexGrid.update()
    #sampleMap.dot(region.perimeter())
    #sampleMap.fillRegion(region)

    pathstyle=StyleCSS("boundaryPath",fill="none",stroke="#ba3ca3ff",stroke_width=3)
    paths = region.trace_perimeter(style=pathstyle)
    sampleMap.builder.add_style(pathstyle)
    
    
    pathLayer = ""
    for path in paths:
        cl = path.closed()
        w = cl.make_windy(iterations=2, offset_factor=0.2)
        pathLayer += w.svg()
        
    sampleMap.builder.adjust("perimeter_path", pathLayer)
    
    #sampleMap.builder.adjust("root","")
    #print(sampleMap.builder.xml())
    
    return sampleMap.hexGrid.builder.show()
 



# %% ../nbs/03_terrain.ipynb #e4804f2d
@patch
def _sample_indexes(self:Terrain, rows, cols, fraction):
    new_rows = int(rows * fraction)
    new_cols = int(cols * fraction)
    arr = np.arange(rows*cols)
    
    # Create new array filled with large values
    new_arr = np.full(new_rows * new_cols, np.inf)
    
    # Map each original element to new position
    for r in range(rows):
        for c in range(cols):
            new_r = int(r * fraction)
            new_c = int(c * fraction)
            if new_r < new_rows and new_c < new_cols:
                idx = new_r * new_cols + new_c
                new_arr[idx] = int(min(new_arr[idx], arr[r * cols + c]))
    
    return new_arr, new_rows, new_cols

# %% ../nbs/03_terrain.ipynb #db741ee8
@patch
def convolution(self: Terrain, field, shape:[HexPosition], fraction, weights = None, method='weighted_avg'):
    """sample any field array using hex ring sampling.
    
    Args:
        field: numpy array of values to downsample (same length as hexes)
        shape: List of HexPosition offsets defining the sampling pattern (e.g., from ring() or spiral())
        new_grid: HexGrid for the downsampled result
        weights: Optional weights for each position in shape
        method: 'weighted_avg', 'max', 'min', or 'mode' (for categorical)
    
    Returns:
        Downsampled array matching new_grid size
    """
    
    grid = self.hexGrid
    destIndex, new_rows, new_cols = self._sample_indexes( self.hexGrid.nRows, self.hexGrid.nCols, fraction)
    # Calculate new grid size
    new_size = new_rows * new_cols
    new_field = np.zeros(new_size)
    
    # Default weights if none provided
    if weights is None:
        weights = np.ones(len(shape))
    
    # Iterate through new grid
    for new_idx, sampling_index in enumerate(destIndex):
        values = []
        valid_weights = []

        for i, offset in enumerate(shape):
            old_idx = self.hexGrid.hexposition_to_index(offset, int(sampling_index))
            if 0 <= old_idx < len(field):
                values.append(field[old_idx])
                valid_weights.append(weights[i])
        
        # If no valid samples, use 0
        if len(values) == 0:
            new_field[new_idx] = 0
            continue
            
        values = np.array(values)
        valid_weights = np.array(valid_weights)
        
        # Apply aggregation method
        if method == 'weighted_avg':
            new_field[new_idx] = np.average(values, weights=valid_weights)
        elif method == 'max':
            new_field[new_idx] = np.max(values)
        elif method == 'min':
            new_field[new_idx] = np.min(values)
        elif method == 'mode':
            # For categorical data - weighted mode
            unique_vals = np.unique(values)
            best_val = unique_vals[0]
            best_weight = 0
            for val in unique_vals:
                val_weight = np.sum(valid_weights[values == val])
                if val_weight > best_weight:
                    best_weight = val_weight
                    best_val = val
            new_field[new_idx] = best_val
    
    return new_field, new_rows, new_cols

# %% ../nbs/03_terrain.ipynb #1c5cf798
@patch
def scaled_simple(self: Terrain, scale: float):
    """Create a scaled terrain that maintains proportional grid dimensions"""
    radius = self.hexGrid.radius 

    def hexes_in_range(n):
        """ finding all hexes within distance N from origin: """
        results = []
        for q in range(-n, n + 1):
            for r in range(max(-n, -q - n), min(n, -q + n) + 1):
                s = -q - r
                results.append(HexPosition(q, r, s))
        return results



    ring_pattern = hexes_in_range(1)

    nextEl , nRows, nCols  = self.convolution( self.elevations, ring_pattern, scale)

    grid =  HexGrid (
        nRows = nRows,
        nCols = nCols,
        radius = radius,
        style = self.hexGrid.style)

    mySize = MapSize(400, 400) #we are droping these
    myBounds = MapRect(MapCord(0,0), mySize)
    sampleMap = Terrain(myBounds, radius=15)
    sampleMap.hexGrid = grid

    sampleMap.elevations = nextEl

    # Copy style properties
    sampleMap.colorLevels = self.colorLevels.copy() if self.colorLevels else None
    sampleMap.elevationDelta = self.elevationDelta
    sampleMap.seaLevel = self.seaLevel

# Use the downsample_field meth

    return sampleMap

    

# %% ../nbs/03_terrain.ipynb #1f8b319f
@patch
def _sample_indexes_np(self: Terrain, rows, cols, fraction):
    new_rows = int(rows * fraction)
    new_cols = int(cols * fraction)
    
    r = np.arange(rows)
    c = np.arange(cols)
    rr, cc = np.meshgrid(r, c, indexing='ij')
    
    new_rr = (rr * fraction).astype(int)
    new_cc = (cc * fraction).astype(int)
    
    valid = (new_rr < new_rows) & (new_cc < new_cols)
    src_idx = (rr * cols + cc).astype(float)
    dst_idx = new_rr * new_cols + new_cc
    
    new_arr = np.full(new_rows * new_cols, np.inf)
    np.minimum.at(new_arr, dst_idx[valid], src_idx[valid])
    
    return new_arr, new_rows, new_cols


# %% ../nbs/03_terrain.ipynb #198cccd8
@patch
def convolution_np(self: Terrain, field, shape, fraction, weights=None, method='weighted_avg'):
    grid = self.hexGrid
    destIndex, new_rows, new_cols = self._sample_indexes_np(grid.nRows, grid.nCols, fraction)
    new_size = new_rows * new_cols
    
    if weights is None:
        weights = np.ones(len(shape))
    weights = np.array(weights)
    
    # Shape offsets as (K, 3) array
    shape_arr = np.array([[hp.q, hp.r, hp.s] for hp in shape])  # (K, 3)
    
    # All sampling origins (M,)
    si = destIndex.astype(int)
    origin_rows = si // grid.nCols
    origin_cols = si % grid.nCols
    origin_q = origin_cols - (origin_rows - (origin_rows & 1)) // 2
    origin_r = origin_rows
    
    # Broadcast: (M,1) + (1,K) → (M,K)
    abs_q = origin_q[:, None] + shape_arr[None, :, 0]
    abs_r = origin_r[:, None] + shape_arr[None, :, 1]
    
    # Cube → offset → index
    rows = abs_r
    cols = abs_q + (abs_r - (abs_r & 1)) // 2
    indices = rows * grid.nCols + cols
    
    # Bounds mask
    valid = (rows >= 0) & (rows < grid.nRows) & (cols >= 0) & (cols < grid.nCols)
    safe_idx = np.where(valid, indices, 0).astype(int)
    
    # Gather all values at once
    values = field[safe_idx]  # (M, K)
    
    # Aggregate
    if method == 'weighted_avg':
        w = np.where(valid, weights[None, :], 0.0)
        w_sum = np.maximum(w.sum(axis=1), 1e-12)
        new_field = (values * w).sum(axis=1) / w_sum
    elif method == 'max':
        values = np.where(valid, values, -np.inf)
        new_field = values.max(axis=1)
        new_field = np.where(np.isinf(new_field), 0, new_field)
    elif method == 'min':
        values = np.where(valid, values, np.inf)
        new_field = values.min(axis=1)
        new_field = np.where(np.isinf(new_field), 0, new_field)
    
    return new_field, new_rows, new_cols


# %% ../nbs/03_terrain.ipynb #d881fe6b
@patch
def scaled(self: Terrain, scale: float):
    """Create a scaled terrain that maintains proportional grid dimensions"""
    radius = self.hexGrid.radius 

    def hexes_in_range(n):
        """ finding all hexes within distance N from origin: """
        results = []
        for q in range(-n, n + 1):
            for r in range(max(-n, -q - n), min(n, -q + n) + 1):
                s = -q - r
                results.append(HexPosition(q, r, s))
        return results



    ring_pattern = hexes_in_range(1)

    nextEl , nRows, nCols  = self.convolution_np( self.elevations, ring_pattern, scale)

    grid =  HexGrid (
        nRows = nRows,
        nCols = nCols,
        radius = radius,
        style = self.hexGrid.style)

    mySize = MapSize(400, 400) #we are droping these
    myBounds = MapRect(MapCord(0,0), mySize)
    sampleMap = Terrain(myBounds, radius=15)
    sampleMap.hexGrid = grid

    sampleMap.elevations = nextEl

    # Copy style properties
    sampleMap.colorLevels = self.colorLevels.copy() if self.colorLevels else None
    sampleMap.elevationDelta = self.elevationDelta
    sampleMap.seaLevel = self.seaLevel

# Use the downsample_field meth

    return sampleMap

    

# %% ../nbs/03_terrain.ipynb #874f6d44
@patch
def field_summary(self: Terrain, field_name):
    """Compact statistical summary of a field."""
    if field_name == "elevations":
        data = self.elevations
    else:
        if field_name not in self.fields:
            return f"Field '{field_name}' not found"
        
        data = self.fields[field_name]
    
    print(f"\n=== {field_name.upper()} ===")
    print(f"Range:  {data.min():.1f} to {data.max():.1f}")
    print(f"Mean:   {data.mean():.1f}")
    print(f"Median: {np.median(data):.1f}")
    print(f"StdDev: {data.std():.1f}")
    
    # Percentiles
    p10, p25, p75, p90 = np.percentile(data, [10, 25, 75, 90])
    print(f"Percentiles: 10%={p10:.1f}, 25%={p25:.1f}, 75%={p75:.1f}, 90%={p90:.1f}")
    
    # Histogram bins
    print(f"\nDistribution:")
    hist, bins = np.histogram(data, bins=8)
    for i in range(len(hist)):
        bar = '█' * int(40 * hist[i] / hist.max())
        print(f"  {bins[i]:7.1f} - {bins[i+1]:7.1f}: {bar} ({hist[i]})")


@patch
def compare_fields(self: Terrain, field1, field2, bins=10):
    """Show correlation between two fields."""
    if field1 not in self.fields or field2 not in self.fields:
        return f"Missing field"
    
    data1 = self.fields[field1]
    data2 = self.fields[field2]
    
    # Correlation
    corr = np.corrcoef(data1, data2)[0, 1]
    
    print(f"\n=== {field1} vs {field2} ===")
    print(f"Correlation: {corr:.3f}")
    
    # Binned comparison
    data1_bins = np.percentile(data1, np.linspace(0, 100, bins+1))
    
    print(f"\n{field1:>12s} | {field2:>12s} (mean)")
    print("-" * 30)
    for i in range(bins):
        mask = (data1 >= data1_bins[i]) & (data1 < data1_bins[i+1])
        if mask.sum() > 0:
            mean2 = data2[mask].mean()
            print(f"{data1_bins[i]:12.1f} | {mean2:12.1f}")


@patch
def field_sizes(self:Terrain):
    print("Elevations",len(self.elevations))
    print("hex",len(self.hexGrid.hexes))
    for field,vals in self.fields.items():
        print("\n\n++++++++++++++")
        print(field,len(vals))
        
        self.field_summary(field)
    print("-------------------------------")

# %% ../nbs/03_terrain.ipynb #418fb80f
@patch
def __ft__(self:Terrain):
    if SVGBuilder.BUILDERHIDE:
        rows = [
            Tr(Td("Rows × Cols"), Td(f"{self.hexGrid.nRows} × {self.hexGrid.nCols}")),
            Tr(Td("Hex Count"),    Td(str(len(self.hexGrid.hexes)))),
            Tr(Td("Radius"),       Td(f"{self.hexGrid.radius}")),
            Tr(Td("Path"),         Td(self.path)),
            Tr(Td("Elevation"),    Td(f"{self.elevations.min():.0f} – {self.elevations.max():.0f}  (μ={self.elevations.mean():.0f})")),
        ]
        
        # Percentiles
        p10, p25, p75, p90 = np.percentile(self.elevations, [10, 25, 75, 90])
        rows.append(Tr(Td("Percentiles"), Td(
            f"10%={p10:.0f}  25%={p25:.0f}  75%={p75:.0f}  90%={p90:.0f}"
        )))
        
        # Elevation level counts
        level_counts = {}
        for i in range(len(self.elevations)):
            lvl = self.elevationLevel(i)
            level_counts[lvl] = level_counts.get(lvl, 0) + 1
        level_parts = []
        for lvl in sorted(level_counts):
            name = "sea" if lvl < 0 else f"L{lvl}"
            level_parts.append(f"{name}:{level_counts[lvl]}")
        rows.append(Tr(Td("Elev Levels"), Td("  ".join(level_parts))))
        
        # Histogram
        hist, bins = np.histogram(self.elevations, bins=8)
        bar_max = hist.max() if hist.max() > 0 else 1
        hist_rows = []
        for i in range(len(hist)):
            bar_width = int(120 * hist[i] / bar_max)
            hist_rows.append(Tr(
                Td(f"{bins[i]:.0f}–{bins[i+1]:.0f}", style="text-align:right; padding-right:6px;"),
                Td(
                    Div(style=f"background:#6a9; width:{bar_width}px; height:12px; display:inline-block; border-radius:2px;"),
                    Span(f" {hist[i]}", style="font-size:11px;")
                )
            ))
        hist_table = Table(*hist_rows, style="border-collapse:collapse; font-size:11px; margin:2px 0;")
        rows.append(Tr(Td("Distribution", style="vertical-align:top;"), Td(hist_table)))
        
        if self.geo:
            g = self.geo
            rows.append(Tr(Td("Geo Bounds"), Td(
                f"Lat {g.lat_min:.3f}–{g.lat_max:.3f}, Lon {g.lon_min:.3f}–{g.lon_max:.3f}"
            )))
        
        if self.climate:
            rows.append(Tr(Td("Climate"), Td(self.climate.name)))
        
        for name, vals in self.fields.items():
            rows.append(Tr(Td(f"Field: {name}"), Td(
                f"{vals.min():.1f} – {vals.max():.1f}  (μ={vals.mean():.1f}, n={len(vals)})"
            )))
        
        return Table(
            Thead(Tr(Th("Property"), Th("Value"))),
            Tbody(*rows),
            style="border-collapse:collapse; font-family:monospace; font-size:13px;",
            cls="terrain-info"
        )
    
    self.colorMap()
    self.hexGrid.update()
    return self.hexGrid.builder.show()


# %% ../nbs/03_terrain.ipynb #8ccc960f
@patch
def upsample(self: Terrain, scale: float = 2.0, method: str = 'bilinear') -> 'Terrain':
    """Upsample terrain by scale factor using hex-aware interpolation.
    
    Args:
        scale: Factor to increase resolution (2.0 = double resolution)
        method: 'nearest', 'bilinear', or 'cubic'
    
    Returns:
        New Terrain at higher resolution
    """
    old_grid = self.hexGrid
    new_radius = old_grid.radius / scale
    
    # Calculate new grid dimensions
    new_rows = int(old_grid.nRows * scale)
    new_cols = int(old_grid.nCols * scale)
    
    # Create new grid
    new_grid = HexGrid(
        nRows=new_rows,
        nCols=new_cols,
        radius=new_radius,
        style=old_grid.style,
        offset=old_grid.offset
    )
    
    # Create new terrain
    new_terrain = Terrain.__new__(Terrain)
    new_terrain.hexGrid = new_grid
    new_terrain.elevations = np.zeros(len(new_grid.hexes))
    new_terrain.fields = {}
    new_terrain.seaLevel = self.seaLevel
    new_terrain.elevationDelta = self.elevationDelta
    new_terrain.climate = self.climate
    new_terrain.geo = self.geo
    new_terrain.colorLevels = self.colorLevels.copy() if self.colorLevels else None
    new_terrain.path = ""
    
    # Upsample elevations
    new_terrain.elevations = _upsample_field(
        self.elevations, old_grid, new_grid, scale, method
    )
    
    # Upsample all fields
    for field_name, field_data in self.fields.items():
        new_terrain.fields[field_name] = _upsample_field(
            field_data, old_grid, new_grid, scale, method
        )
    
    # Add styles to new builder
    if new_terrain.colorLevels:
        for color in new_terrain.colorLevels:
            new_terrain.hexGrid.builder.add_style(color)
    
    return new_terrain


def _upsample_field(field: np.ndarray, old_grid: HexGrid, new_grid: HexGrid, 
                    scale: float, method: str) -> np.ndarray:
    """Upsample a single field array."""
    n_new = len(new_grid.hexes)
    result = np.zeros(n_new)
    
    if method == 'nearest':
        result = _upsample_nearest(field, old_grid, new_grid, scale)
    elif method == 'bilinear':
        result = _upsample_bilinear(field, old_grid, new_grid, scale)
    elif method == 'cubic':
        result = _upsample_cubic(field, old_grid, new_grid, scale)
    else:
        raise ValueError(f"Unknown method: {method}")
    
    return result


def _upsample_nearest(field: np.ndarray, old_grid: HexGrid, new_grid: HexGrid, 
                      scale: float) -> np.ndarray:
    """Nearest neighbor upsampling - fast but blocky."""
    n_new = len(new_grid.hexes)
    result = np.zeros(n_new)
    
    # Build lookup: for each new hex, find nearest old hex
    for new_idx in range(n_new):
        new_center = new_grid.hexes[new_idx].center
        
        # Map new pixel position back to old grid coordinates
        # Account for offset differences
        old_row = int((new_center.y - old_grid.offset.y - old_grid.radius) / (1.5 * old_grid.radius))
        old_col_offset = 0.5 if old_row % 2 == 1 else 0
        old_col = int((new_center.x - old_grid.offset.x - old_grid.radius) / (np.sqrt(3) * old_grid.radius) - old_col_offset)
        
        old_idx = old_grid.row_col_to_index(old_row, old_col)
        if 0 <= old_idx < len(field):
            result[new_idx] = field[old_idx]
    
    return result


def _upsample_bilinear(field: np.ndarray, old_grid: HexGrid, new_grid: HexGrid,
                       scale: float) -> np.ndarray:
    """Bilinear interpolation using 3 nearest hex neighbors."""
    n_new = len(new_grid.hexes)
    result = np.zeros(n_new)
    
    for new_idx in range(n_new):
        new_center = new_grid.hexes[new_idx].center
        
        # Find fractional position in old grid space
        # Convert pixel to approximate old grid row/col (fractional)
        old_row_f = (new_center.y - old_grid.offset.y - old_grid.radius) / (1.5 * old_grid.radius)
        old_col_offset = 0.5 if int(old_row_f) % 2 == 1 else 0
        old_col_f = (new_center.x - old_grid.offset.x - old_grid.radius) / (np.sqrt(3) * old_grid.radius) - old_col_offset
        
        # Get integer and fractional parts
        r0, c0 = int(np.floor(old_row_f)), int(np.floor(old_col_f))
        fr, fc = old_row_f - r0, old_col_f - c0
        
        # Sample surrounding hexes with distance-based weights
        samples = []
        weights = []
        
        for dr in [0, 1]:
            for dc in [0, 1]:
                r, c = r0 + dr, c0 + dc
                idx = old_grid.row_col_to_index(r, c)
                if 0 <= idx < len(field):
                    # Weight by inverse distance (bilinear formula)
                    wr = (1 - fr) if dr == 0 else fr
                    wc = (1 - fc) if dc == 0 else fc
                    w = wr * wc
                    if w > 0:
                        samples.append(field[idx])
                        weights.append(w)
        
        if samples:
            result[new_idx] = np.average(samples, weights=weights)
    
    return result


def _upsample_cubic(field: np.ndarray, old_grid: HexGrid, new_grid: HexGrid,
                    scale: float) -> np.ndarray:
    """Cubic interpolation using ring-1 neighbors (7 samples)."""
    n_new = len(new_grid.hexes)
    result = np.zeros(n_new)
    
    for new_idx in range(n_new):
        new_center = new_grid.hexes[new_idx].center
        
        # Find nearest old hex
        old_row = int((new_center.y - old_grid.offset.y - old_grid.radius) / (1.5 * old_grid.radius))
        old_col_offset = 0.5 if old_row % 2 == 1 else 0
        old_col = int((new_center.x - old_grid.offset.x - old_grid.radius) / (np.sqrt(3) * old_grid.radius) - old_col_offset)
        
        center_idx = old_grid.row_col_to_index(old_row, old_col)
        if center_idx < 0 or center_idx >= len(field):
            continue
        
        center_hex = old_grid.hexes[center_idx]
        
        # Gather center + ring-1 neighbors
        samples = []
        weights = []
        
        # Center hex
        dist = _pixel_distance(new_center, center_hex.center)
        if dist < 0.01:
            result[new_idx] = field[center_idx]
            continue
        
        samples.append(field[center_idx])
        weights.append(1.0 / (dist + 0.1))  # Inverse distance weight
        
        # Ring-1 neighbors
        for neighbor_idx in old_grid.neighborsOf(center_idx):
            if 0 <= neighbor_idx < len(field):
                neighbor_hex = old_grid.hexes[neighbor_idx]
                dist = _pixel_distance(new_center, neighbor_hex.center)
                samples.append(field[neighbor_idx])
                weights.append(1.0 / (dist + 0.1))
        
        if samples:
            result[new_idx] = np.average(samples, weights=weights)
    
    return result


def _pixel_distance(p1: MapCord, p2: MapCord) -> float:
    """Euclidean distance between two pixel coordinates."""
    return np.sqrt((p1.x - p2.x)**2 + (p1.y - p2.y)**2)


# %% ../nbs/03_terrain.ipynb #7df0b167
@patch
def growFromHex(self: Terrain, center_idx, origin=0):
    """Grow a region from center hex at same elevation level."""
    center_elev_level = self.elevationLevel(center_idx)
    
    # Use a queue-based flood fill instead
    hex_set = {center_idx}
    to_check = [center_idx]
    
    while to_check:
        current = to_check.pop(0)
        
        # Check all 6 neighbors
        neighbors = self.ring(current, 1)
        for n_idx in neighbors:
            if n_idx in hex_set:
                continue
            if n_idx < 0 or n_idx >= len(self.elevations):
                continue
            if self.elevationLevel(n_idx) != center_elev_level:
                continue
            
            hex_set.add(n_idx)
            to_check.append(n_idx)
    
    return HexRegion(hexes=hex_set, hexGrid=self.hexGrid)

# %% ../nbs/03_terrain.ipynb #e8a6ff60
@patch
def find_region_at_level(self:Terrain, center_idx):
    """Find all connected hexes within tolerance of center_idx's elevation.
    
    Args:
        center_idx: starting hex index
        tolerance: elevation difference allowed
    
    Returns:
        set of hex indices in the region
    """
    target_elev = self.elevationLevel(center_idx)
    levels = [x for x in range(len(self.elevations)-1) if self.elevationLevel(x) == target_elev]

    return set(levels)


# %% ../nbs/03_terrain.ipynb #c0346afd
@patch
def demoRegion(self:TerraDemo):
    """Practice building up coord."""
    
    sampleMap = self.sanFran()
    peaks = sampleMap.find_peaks(7,0)
    start =  0 # peaks[0]
    region = HexRegion(hexes=sampleMap.find_region_at_level(0), hexGrid=sampleMap.hexGrid)
    for x in sampleMap.find_region_at_level(0):
        region.hexes.add(x)
    
    #region = sampleMap.growFromHex(start)
    

    # Show the base terrain
    sampleMap.colorMap()
    sampleMap.hexGrid.update()
    #sampleMap.dot(region.perimeter())
    #sampleMap.fillRegion(region)

    pathstyle=StyleCSS("boundaryPath",fill="none",stroke="#ba3ca3ff",stroke_width=3)
    paths = region.trace_perimeter(style=pathstyle)
    sampleMap.builder.add_style(pathstyle)
    
    
    pathLayer = ""
    for path in paths:
        if path.points[0].distance(path.points[-1]) < 40:
            cl = path.closed()
        else:
            cl = path
        w = cl.make_windy(iterations=2, offset_factor=0.2)
        pathLayer += w.svg()
        
    sampleMap.builder.adjust("perimeter_path", pathLayer)
    
    #sampleMap.builder.adjust("root","")
    #print(sampleMap.builder.xml())
    
    return sampleMap.hexGrid.builder.show()
 


# %% ../nbs/03_terrain.ipynb #72699439
@patch
def coastline_svg(self:Terrain,pathstyle=StyleCSS("coastPath",fill="none",stroke="#917910ff",stroke_width=3)):
    """Add a coast to the terrain."""
    region = HexRegion(hexes=self.find_region_at_level(0), hexGrid=self.hexGrid)


    for x in self.find_region_at_level(0):
        region.hexes.add(x)
    

    paths = region.trace_perimeter(style=pathstyle,debug=False)
    self.builder.add_style(pathstyle)

    pathLayer = ""
    for path in paths:
        if path.points[0].distance(path.points[-1]) < 40:
            cl = path.closed()
        else:
            cl = path
        curved = cl.make_windy(iterations=1, offset_factor=0.1, seed=42)
        smooth = curved.smooth(iterations=1)
        pathLayer += smooth.svg()
        
    return pathLayer

# %% ../nbs/03_terrain.ipynb #abfe8fd7
@patch
def addCoast(self:Terrain,pathstyle=StyleCSS("coastPath",fill="none",stroke="#917910ff",stroke_width=3)):
    """Add a coast to the terrain."""
    

    pathLayer = self.coastline_svg(pathstyle=pathstyle)
        
   
    self.colorMap()
    self.hexGrid.update()
    self.builder.adjust("coastline", pathLayer)

    

# %% ../nbs/03_terrain.ipynb #d641b174
@patch
def demoCoast(self:TerraDemo):
    """Practice building up coord."""
    
    sampleMap = self.sanFran()
    sampleMap.addCoast()
   
    
    return sampleMap.hexGrid.builder.show()
 



# %% ../nbs/03_terrain.ipynb #afffff06
@patch
def assign_grid(self: Terrain, new_grid: HexGrid):
    """Assign a new HexGrid to this terrain, resetting data arrays.
    
    This replaces the current hexGrid and resets:
    - elevations: zeroed array matching new grid size
    - fields: all field arrays zeroed to new grid size
    
    Use this when you need a differently-shaped grid but want to
    keep the terrain's style settings (colorLevels, seaLevel, etc.)
    
    Args:
        new_grid: The new HexGrid to use
    """
    self.hexGrid = new_grid
    
    # Reset elevations to match new grid size
    num_hexes = len(new_grid.hexes)
    self.elevations = np.zeros(num_hexes)
    
    # Reset all fields to match new grid size
    for field_name in self.fields:
        self.fields[field_name] = np.zeros(num_hexes)
    
    # Re-add styles to new grid's builder
    self.hexGrid.builder.add_style(self.seaLevel)
    for style in self.colorLevels:
        hover = StyleCSS("hover", fill=style.desaturate().properties["fill"], cursor="pointer")
        style.customize(hover)
        self.hexGrid.builder.add_style(style)

# %% ../nbs/03_terrain.ipynb #f7325a76
@dataclass
class USGSTerrainFetcher:
    """Build terrain from USGS EPQS elevation data."""
    
    EPQS_URL = "https://epqs.nationalmap.gov/v1/json"
    
    async def fetch_elevation(self, client: httpx.AsyncClient, lat: float, lon: float) -> float | None:
        """Fetch single elevation point from USGS EPQS."""
        try:
            resp = await client.get(self.EPQS_URL, params={
                'x': lon, 'y': lat,  # Note: x=lon, y=lat
                'units': 'Meters',
                'wkid': 4326,
                'includeDate': 'False'
            }, timeout=10)
            data = resp.json()
            return data.get('value')
        except Exception as e:
            print(f"Error fetching ({lat}, {lon}): {e}")
            return None
    
    async def fetch_batch(self, points: list[tuple[float, float]], 
                          max_concurrent: int = 10) -> list[float | None]:
        """Fetch elevations for multiple points with rate limiting."""
        semaphore = asyncio.Semaphore(max_concurrent)
        
        async def bounded_fetch(client, lat, lon):
            async with semaphore:
                return await self.fetch_elevation(client, lat, lon)
        
        async with httpx.AsyncClient() as client:
            tasks = [bounded_fetch(client, lat, lon) for lat, lon in points]
            return await asyncio.gather(*tasks)
    
    


# %% ../nbs/03_terrain.ipynb #703bc17f
@patch
async def build_terrain(self: USGSTerrainFetcher, geo: GeoBounds, approx_hexes: int = 500,
                        radius: float = 25.0) -> Terrain:
    """Build terrain with latitude-corrected sampling for equal ground coverage."""
    lat_span = geo.lat_span
    lon_span = geo.lon_span
    
    # Use center latitude for initial grid sizing
    center_lat = geo.lat_center
    lon_scale = cos(radians(center_lat))
    
    # Aspect ratio in "real" distances
    aspect = (lon_span * lon_scale) / lat_span
    
    nrows = int(math.sqrt(approx_hexes / aspect))
    ncols = int(nrows * aspect)
    nrows = max(nrows, 2)
    ncols = max(ncols, 2)
    
    width = ncols * radius * 1.5 + radius
    height = nrows * radius * math.sqrt(3) + radius
    bounds = MapRect(MapCord(0, 0), MapSize(width, height))
    
    terrain = Terrain(bounds, radius=radius)
    terrain.geo = geo
    terrain.elevations = np.zeros(len(terrain.hexGrid.hexes))
    
    # Store lat/lon per hex for later use (weather, etc)
    terrain.fields['latitude'] = np.zeros(len(terrain.hexGrid.hexes))
    terrain.fields['longitude'] = np.zeros(len(terrain.hexGrid.hexes))
    
    grid = terrain.hexGrid
    
    points = []
    for idx in range(len(grid.hexes)):
        row = idx // grid.nCols
        col = idx % grid.nCols
        
        # Latitude is linear (rows map evenly to lat)
        lat = geo.lat_max - (row / max(grid.nRows - 1, 1)) * lat_span
        
        # Longitude step adjusted for this row's latitude
        # At higher latitudes, same pixel distance = more degrees longitude
        row_lon_scale = cos(radians(lat))
        if row_lon_scale < 0.1:  # Near poles, clamp to avoid division issues
            row_lon_scale = 0.1
        
        # Effective lon span for this row (in degrees that cover same ground distance)
        effective_lon_span = lon_span * (lon_scale / row_lon_scale)
        lon_offset = (effective_lon_span - lon_span) / 2  # Center the adjusted span
        
        lon = (geo.lon_min - lon_offset) + (col / max(grid.nCols - 1, 1)) * effective_lon_span
        
        points.append((lat, lon))
        terrain.fields['latitude'][idx] = lat
        terrain.fields['longitude'][idx] = lon
    
    elevations = await self.fetch_batch(points)
    
    for idx, elev in enumerate(elevations):
        terrain.elevations[idx] = elev if elev is not None else 0.0
    
    return terrain

