# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/tutorials/gallery.ipynb.

# %% auto #0
__all__ = ['GalleryItem']

# %% ../../nbs/tutorials/gallery.ipynb #be3b02ae
import sys
import math
import numpy as np
from fastcore.basics import patch
import random

# %% ../../nbs/tutorials/gallery.ipynb #9605fdb4
from ..styles import StyleCSS,  SVGBuilder
from ..primitives import MapPath, MapSize, MapRect, MapCord 
from ..primitives import unique_windy_edge, HexRegion, HexGrid
from ..terrain import Terrain
from ..voronoi import generate_plate_terrain, PlateKind, Plate

Terrain.fromSeeds = generate_plate_terrain
from ..river import River, SoilSystem, ErosionModel
from ..terrainpatterns import TerrainPatterns

from ..climate import ClimatePreset, Climate, TerrainFactory
from ..climate import  Geology
from ..hydrology import DrainageBasins



# %% ../../nbs/tutorials/gallery.ipynb #29a3043e
class GalleryItem:

    def __init__(self,name,description,make,width=400,height=400,path:[str] = []):
        self.name = name
        self.description = description
        self.path = path
        self.width = width
        self.height = height
        self.make = make
        self.world = None

    def current(self)->Geology:
        if self.world is None:
            self.world = self.make(self.width,self.height)
        return self.world
