# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/tmp/drawing.ipynb.

# %% auto 0
__all__ = ['apply_looping_animation']

# %% ../../nbs/tmp/drawing.ipynb 8
#keep
def apply_looping_animation(builder: SVGBuilder, anim: LoopingLayerAnimation):
    """Apply a LoopingLayerAnimation to an SVGBuilder"""
    # Set initial opacities
    for layer_name, opacity in anim.initial_opacities().items():
        for layer in builder.layers:
            if layer.name == layer_name:
                layer.properties['opacity'] = str(opacity)
                break
    
    # Add animation CSS
    if not hasattr(builder, 'custom_animations'):
        builder.custom_animations = []
    builder.custom_animations.append(anim.generate())

